### ISSUE TITLE
bug: holoiso does not download

### ISSUE THREAD

**Issue by flexiondotorg** [quickemu-project/quickemu#1062]
#### Expected behaviour

quickget should download holoiso.

#### Actual behaviour

`quickget holoiso` doesn't return any releases and a release is required.

#### Steps to reproduce the behaviour

`quickget holoiso`.

#### Quickemu output

```
ERROR! You must specify a release.
 - Releases: ⏎
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
Distributor ID:	NixOS
Description:	NixOS 23.11 (Tapir)
Release:	23.11
Codename:	tapir

Linux vader 6.6.25 #1-NixOS SMP PREEMPT_DYNAMIC Thu Apr  4 18:23:07 UTC 2024 x86_64 GNU/Linux
```

**Comment by zen0bit** [comment]
Are you tried that? Worked?
