### ISSUE TITLE
Issue downloading NixOS ISOs

### ISSUE THREAD

**Issue by nfowlie** [quickemu-project/quickemu#1077]
#### Expected behaviour

Download any NixOS ISO with the command quickget nixos {release} [edition]

#### Actual behaviour

Fails to download the ISO

#### Steps to reproduce the behaviour

Attempt to download any NixOS ISO using the quickget command

#### Quickemu output

quickget nixos 23.11 minimal
```
04/18 13:30:18 [ERROR] CUID#7 - Download aborted. URI=https://channels.nixos.org/nixos-23.11/latest-nixos-minimal-x86_64-linux.iso
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://releases.nixos.org/nixos/23.11/nixos-23.11.6418.e402c3eb6d88/nixos-minimal-23.11.6418.e402c3eb6d88-x86_64-linux.iso
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=421

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR! Failed to download https://channels.nixos.org/nixos-23.11/latest-nixos-minimal-x86_64-linux.iso with aria2c. Try running 'quickget' again.
```

#### Linux Distribution & Kernel

LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
Linux name 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux

**Comment by zen0bit** [comment]
try with quickget from master branch
It already solved (Not yet released...)

Just tried...

**Comment by nfowlie** [comment]
Yup, you're right.  Works from the latest master, just not in release.

Thank you, looking forward to the next release.

**Comment by flexiondotorg** [comment]
This is fixed in master via https://github.com/quickemu-project/quickemu/pull/1063 and will be part of the next release.
