### ISSUE TITLE
Regression introduced with new run script

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#1096]
# Fill regresion in new TUI here

### Please put here
If you spot something is bad/missing/wrong or know how to improve current state.
Add it here to easier track what's needed.

I will be constantly updating this issue..

Thanks for cooperation

- [ ] - Line braking between debian current and debian old releases

TODO:
- [ ] - --create-config Not yet implemented 

Just optical bug

But I see it and don't like it

**Comment by flexiondotorg** [comment]
- Debian issues is fixed via https://github.com/quickemu-project/quickemu/commit/409523d4020b887ab5ce721d8cab5114c56fe7d2
- `--create-config` is being tracked via https://github.com/quickemu-project/quickemu/issues/1104
