### ISSUE TITLE
feat: --create-config option not yet implemented

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#1104]
Currently just a stub marked TODO.
This is just a reminder to either add it or comment out the option (and regen docs so it is not mentioned everywhere) before release

**Comment by lj3954** [comment]
> Initial commit included in my PR not yet sure what pass to make_vm..?

I think an operating system shouldn't be taken in, but rather just the name of the VM and a file/URL. Quickget isn't intended for the user to have to manually configure everything. Perhaps some string manipulation should be used to get a good guess of the guest OS. I'll propose a draft implementation tonight.
