### ISSUE TITLE
bug: release 4.9.2 doesn't have a `.deb` file attached

### ISSUE THREAD

**Issue by FWDekker** [quickemu-project/quickemu#1118]
The readme states that, to install on Debian, I can download the `.deb` from the releases and install it. [Release v4.9.1](https://github.com/quickemu-project/quickemu/releases/tag/4.9.1) has a `.deb` in the attachments, but [release v4.9.2](https://github.com/quickemu-project/quickemu/releases/tag/4.9.2) doesn't. I can't find anything in the changelog indicating that this was deprecated, so I suspect it was forgotten / failed to be attached somehow.

Would it still be possible to attach the `.deb` of v4.9.2 (or was its omission intentional)?

**Comment by zen0bit** [comment]
Isn't this already solved for future, (not for 4.9.2) in [#1000](https://github.com/quickemu-project/quickemu/pull/1000)?

**Comment by flexiondotorg** [comment]
Closed via https://github.com/quickemu-project/quickemu/releases/tag/4.9.3
