### ISSUE TITLE
Issues with launching non-Linux VMs in Quickemu

### ISSUE THREAD

**Issue by root-over** [quickemu-project/quickemu#1129]
#### Expected behaviour

I expect the non-Linux VMs (Windows or macOS) to launch successfully and proceed to the login screen or desktop when started with SPICE.

#### Actual behaviour

When attempting to start non-Linux VMs using SPICE, I encounter a continuous loop of a connection screen asking me to click "Connect." Clicking the button causes the same screen to reappear without progressing to the VM's desktop. This issue does not occur with Ubuntu VMs, which start without any problems.

The same thing happen when start without SPICE with this output:
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v9.0.0
 - Host:     "EndeavourOS Linux" running Linux 6.8 (ThinkArch)
 - CPU:       11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
qemu-system-x86_64: -no-hpet: invalid option
cat: windows-10/windows-10.pid: No such file or directory
 - Process:  Starting windows-10.conf as windows-10 ()

#### Additional details

- Attempts to resolve the issue included creating a new VM, reinstalling Quickemu, installing qemu-full, and reinstalling all dependencies via sudo pacman -Rcns quickemu and reinstalling Quickemu via yay.
- The problem was first noticed after a system update using sudo pacman -Syyu.

#### Linux Distribution & Kernel

```LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling
```
![Schermata del 2024-04-30 22-03-42](https://github.com/quickemu-project/quickemu/assets/91559694/6db3968b-352c-4ee1-9dc6-684908d641a9)

**Comment by root-over** [comment]
I solved it by downloading the quickemu file from github and replacing it with the file printed from whereis quickemu

**Comment by fabifont** [comment]
> #### Expected behaviour
> 
> I expect the non-Linux VMs (Windows or macOS) to launch successfully and proceed to the login screen or desktop when started with SPICE.
> #### Actual behaviour
> 
> When attempting to start non-Linux VMs using SPICE, I encounter a continuous loop of a connection screen asking me to click "Connect." Clicking the button causes the same screen to reappear without progressing to the VM's desktop. This issue does not occur with Ubuntu VMs, which start without any problems.
> 
> The same thing happen when start without SPICE with this output: Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v9.0.0
> 
>     * Host:     "EndeavourOS Linux" running Linux 6.8 (ThinkArch)
> 
>     * CPU:       11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
> 
>     * CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
> 
>     * BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
> 
>     * Disk:     windows-10/disk.qcow2 (64G)
> 
>     * CD-ROM:   windows-10/virtio-win.iso
> 
>     * Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
> 
>     * Sound:    intel-hda
> 
>     * ssh:      On host:  ssh user@localhost -p 22220
> 
>     * WebDAV:   On guest: dav://localhost:9843/
> 
>     * smbd:     On guest: smb://10.0.2.4/qemu
> 
>     * Network:  User (virtio-net)
> 
>     * Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
>       or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
> 
>     * Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
>       or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
>       qemu-system-x86_64: -no-hpet: invalid option
>       cat: windows-10/windows-10.pid: No such file or directory
> 
>     * Process:  Starting windows-10.conf as windows-10 ()
> 
> 
> #### Additional details
> 
>     * Attempts to resolve the issue included creating a new VM, reinstalling Quickemu, installing qemu-full, and reinstalling all dependencies via sudo pacman -Rcns quickemu and reinstalling Quickemu via yay.
> 
>     * The problem was first noticed after a system update using sudo pacman -Syyu.
> 
> 
> #### Linux Distribution & Kernel
> 
> ```
> Distributor ID:	EndeavourOS
> Description:	EndeavourOS Linux
> Release:	rolling
> Codename:	rolling
> ```
> 
> ![Schermata del 2024-04-30 22-03-42](https://private-user-images.githubusercontent.com/91559694/326966076-6db3968b-352c-4ee1-9dc6-684908d641a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTkzMjIsIm5iZiI6MTcxNDk5OTAyMiwicGF0aCI6Ii85MTU1OTY5NC8zMjY5NjYwNzYtNmRiMzk2OGItMzUyYy00ZWUxLTlkYzYtNjg0OTA4ZDY0MWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyMzcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjk2N2NkM2U4MmEzOWUwMDAyYTA5ZDgyZTU2OWE2NTE2Yzk4NmFjYWQ5NTZlNWVlZDhjNDAzMDNhM2U3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2r54Dmx6K4EJKzPysR0_BSWgFtQUJaQMA9vCVteYaco)

Hi, I'm having the same problem. I tried switching to quickemu-git from AUR but now it says that the image is corrupted (insane).
