### ISSUE TITLE
feat: add system info capability to quickemu to out useful information when reporting an issue

### ISSUE THREAD

**Issue by flexiondotorg** [quickemu-project/quickemu#1163]
Add a feature to quickemu to out useful system information to request when reporting issues. Examples of useful information are:

- OS
- CPU and CPU capabilities such as as SSE and AVX
- RAM
- GPUs
- Linux kernel
- `qemu` version
- `curl` version

**Comment by TuxVinyards** [comment]
Good idea

**Comment by flexiondotorg** [comment]
I've also updated the issue template: https://github.com/quickemu-project/quickemu/commit/65f065a327807ab2d4e3c6baec66b66065ed8b96
