### ISSUE TITLE
bug: EFI firmware not found on quickemu 4.9.3

### ISSUE THREAD

**Issue by bennydente** [quickemu-project/quickemu#1181]
# Expected behavior
running  ./quickemu --vm windows-10.conf --display spice should run Windows 10 VM

on 4.9.2 version worked fine.

## Actual behavior
running ./quickemu --vm windows-10.conf --display spice got error
ERROR! EFI boot requested but no EFI firmware found.
       Please install OVMF firmware.

# Steps to reproduce the behavior
 ./quickemu --vm windows-10.conf --display spice 

# Additional context
Using Fedora 40 Workstation

## Quickemu output

Run `quickemu` and include the output of the failure below:

ERROR! EFI boot requested but no EFI firmware found.
       Please install OVMF firmware.

## System Information

Quickemu 4.9.3
Distro:	Fedora Linux 40 (Workstation Edition)
Kernel:	Linux 6.8.8-300.fc40.x86_64 x86_64
Memory:	16G

**Comment by flexiondotorg** [comment]
You need to install the dependencies:

- https://github.com/quickemu-project/quickemu/wiki/01-Installation#install-requirements-on-fedora

**Comment by bennydente** [comment]
Hi, I did it and also repeated the command after the new release. thanks.

**Comment by popey** [comment]
Seeing the same on 24.04

```
./ubuntu-24.04.conf 
~/Source/popey/quicktest/vm ~/Source/popey/quicktest/vm
Quickemu 4.9.3 using /usr/bin/qemu-system-x86_64 v8.2.2
 - Host:     Ubuntu 24.04 LTS running Linux 6.8 (ziggy)
 - CPU:      AMD Ryzen 7 PRO 6860Z with Radeon Graphics
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
ERROR! EFI boot requested but no EFI firmware found.
       Please install OVMF firmware.
```

**Comment by flexiondotorg** [comment]
@popey @bennydente Please can you git clone this project and then try `quickemu` in the ovmf branch:

- https://github.com/quickemu-project/quickemu/tree/ovmf

Or bodge your copy of `quickemu` with this patch:

- https://github.com/quickemu-project/quickemu/commit/877b6b96f3b174b572cf72f89f777c16882ca8fd

**Comment by popey** [comment]
Thanks for the prompt fix. I patched the script and all I got was great success. :partying_face: 

```
Quickemu 4.9.3 using /usr/bin/qemu-system-x86_64 v8.2.2
 - Host:     Ubuntu 24.04 LTS running Linux 6.8 (ziggy)
 - CPU:      AMD Ryzen 7 PRO 6860Z with Radeon Graphics
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     ubuntu-24.04/disk.qcow2 (16G)
             Just created, booting from ubuntu-24.04/ubuntu-24.04-desktop-amd64.iso
 - Boot ISO: ubuntu-24.04/ubuntu-24.04-desktop-amd64.iso
 - Display:  SPICE, virtio-gpu, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "ubuntu-24.04" --port 5930 --spice-shared-dir /home/alan/
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-alan ~/alan
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "ubuntu-24.04/ubuntu-24.04-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-24.04/ubuntu-24.04-monitor.socket
 - Serial:   On host:  nc -U "ubuntu-24.04/ubuntu-24.04-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-24.04/ubuntu-24.04-serial.socket
 - Process:  Starting ubuntu-24.04.conf as ubuntu-24.04 (2247476)
 - Viewer:   spicy --title "ubuntu-24.04" --port "5930" --spice-shared-dir "/home/alan/" "" >/dev/null 2>&1 &

```

**Comment by flexiondotorg** [comment]
Thank you :bow: 

I'll turn around a release of 4.9.4 with in the next hour.

**Comment by bennydente** [comment]
Thanks, I confirm now work too.

**Comment by jrullo** [comment]
I'm seeing thsi same issue with Quickemu 4.9.6 using /usr/bin/qemu-system-x86_64 v9.1.1

**Comment by exstntlmsnthrp** [comment]
I would add that I am seeing this issue on EndeavourOS as well. This had previously worked brilliantly and has now thrown this error. I've quickemu 4.9.6 installed via `yay` and the previously mentioned fix isn't working. All related deps are installed as well.

**Comment by mbudak21** [comment]
> I would add that I am seeing this issue on EndeavourOS as well. This had previously worked brilliantly and has now thrown this error. I've quickemu 4.9.6 installed via `yay` and the previously mentioned fix isn't working. All related deps are installed as well.

Same here with Arch, on all machines.
