### ISSUE TITLE
feat: Add network override CLI option

### ISSUE THREAD

**Issue by popey** [quickemu-project/quickemu#1194]
# Expected behavior

Sometimes I'd like to override the network behaviour of quickemu. Specifically I'd like to disconnect the network, or change to a bridged network.

Something like this:

`quickemu --network none`

or

`quickemu --network bridged`

## Actual behavior

There's no option to do this.

Thanks!

**Comment by flexiondotorg** [comment]
From talking with you, I think all you really care about is configuration an offline state.

How does this sound? I'm just going to add a `--offline` argument, which overrides any network configuration with `none`.
