### ISSUE TITLE
bug: --monitor-cmd always fails due to qemu-img check attempt

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#1198]
# Expected behavior

--monitor-cmd works as documented 
## Actual behavior

--monitor-cmd (and presumably other options that work with a running VM) break due to invocation of qemu-img to check the disk, which of course fails as it is in use.

**Comment by flexiondotorg** [comment]
This regress was introduced via:

- https://github.com/quickemu-project/quickemu/commit/d030221214b89370ab0f5a196562639c1bb9808e

In an effort to fix https://github.com/quickemu-project/quickemu/pull/848

Thanks @philclifford for this comment:

- https://github.com/quickemu-project/quickemu/issues/1195#issuecomment-2105395074

**Comment by flexiondotorg** [comment]
The disk health check is a feature that is broken by design: https://github.com/quickemu-project/quickemu/pull/848

- If a VM is running, `qemu-img check` it will always fail
- `quickemu` can start VMs in the background (`--display spice` for example) and the health check then breaks all further use of `quickemu` that operates on a running VM.

**Comment by TuxVinyards** [comment]
This is a general test that I use for my disk maintenance routines to avoid Qemu lock  problems.

```
    # use pgrep with -x exact match to avoid 'kvm-cleanup' processes being detected
    [[ $(pgrep -x kvm) ]] &&  printColor "\n\n  VIRTUAL MACHINE ACTIVITY has been DETECTED \n"   
```
Thinking aloud a bit here,  as just got back from a short break and I haven't  tested.  But would adding this as a conditional  to the disk health checker work?

**Comment by flexiondotorg** [comment]
The implementations, as submitted to `quickemu` in #848 and #993, are both broken. Here is a working implementation: https://github.com/quickemu-project/quickemu/pull/1199/commits/cc97f2f85c4413287b404f3140489423a65e674b
