### ISSUE TITLE
the quick start guide is wrong

### ISSUE THREAD

**Issue by theonekingboo** [quickemu-project/quickemu#1205]
# Expected behavior

With the quickget and quickemu example in the readme should make a VM with "nixos unstable"

## Actual behavior

When you try to do that example, an error will simply show up

# Steps to reproduce the behavior

Take the example in the README for the quick start guide

# Additional context

## Quickemu output

Run `quickemu` or `quickemu` and include the output of the failure below:

```
ERROR! NixOS unstable is not a supported release.

21.05 21.11 22.05 22.11 23.05 23.11

```

I get that getting the actual Unstable ISO would not work because that's not how nixos handles it's unstable versions, but the simple fix would be to add the current release for Nix (nixos 23.11) in the quick start section of the README.

**Comment by flexiondotorg** [comment]
This feature was added to Quickemu 4.9.3 and newer. If you update to the current release of Quickemu you will have the documented behaviour.

**Comment by theonekingboo** [comment]
alright good to know thanks
