### ISSUE TITLE
bug: macOS RecoveryImage.img is deleted by quickget

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1224]
Distro : Arch
De : plasma
quickemu : qemu-git

<pre><code>
quickget macos ventura
</pre></code>

it downloads the RecoveryImage.img but when its finished it deletes it , its removed for the folder all thats left is the opencore.qcow2 and ovmf files

I has to do with the latest git build the release build is fine 

I installed the quickemu-git from arch and it deletes the file I installed quickemu from arch and it does'nt delete the file

git build seems to have a bug that deletes the file after downloaded

**Comment by flexiondotorg** [comment]
Closing this because you are using an old version of Quickemu, please update to 4.9.4:

- https://aur.archlinux.org/packages/quickemu

**Comment by xensurve** [comment]
Sorry My mistake about mentioning the git version , its the quickemu-git from the aur it pulls the latest .. 

https://github.com/quickemu-project/quickemu/issues/935 that swicth is in the latest git pull

**Comment by flexiondotorg** [comment]
Sorry, I understand what you are reporting :+1: 

The issue with the macOS recovery image getting deleted is fixed by this commit: https://github.com/quickemu-project/quickemu/commit/b7b759e7f14d8c3d11b59a9e11752eb9ac93aae9

It is in a feature branch I am working on and will soon be merged into the master branch.

**Comment by xensurve** [comment]
Yes, that is caused by commit https://github.com/quickemu-project/quickemu/commit/8db310035541fd6b0fe17f388aaec914cb20da08. Quickget never sets the QEMU_IMG variable, only quickemu does. There must have been an oversight there.
