### ISSUE TITLE
cat: ./macos.pid: No such file or directory

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1226]
Distro : Arch
De : Plasma
Quickemu 4.9.4 aur

<pre><code>
quickemu  --vm macos-ventura.conf
</pre></code>

ERROR MESSAGE  : cat: ./macos.pid: No such file or directory  

can anyone else confirm this

**Comment by flexiondotorg** [comment]
This is a side effect of https://github.com/quickemu-project/quickemu/issues/1229
