### ISSUE TITLE
 Mouse Issue Windows

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1227]
DISTRO : ARCH
DE : PLASMA
QUICKEMU : 4.9.4

when using windows 10,11 , when the mouse pointer gets near the tak bar it jumps to the host taskbar so you can't click the task bar . windows is unusable, Can someone have a look the mouse passthough please

**Comment by xensurve** [comment]
I can confirm this is also on windows 10 does any one have a fix or know how to get around this , its unusable with out being able to click the task bar

**Comment by wolfsprite** [comment]
Thank you!! 

I could not click anything on the toolbar, sides, or top of screen in the guest VM without that `--mouse 'virtio'` option.
