### ISSUE TITLE
more-info: Release Mouse in windows 10/11 automatically

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1237]
DISTRO : ARCH
DE : PLASMA
QUICKEMU : 4.9.4

the default quickemu mouse switch is set to -- mouse 'tablet' this releases the cursor when the cursor is brought to the edge without having to press  ctrl alt + g to release the mouse but using  tablet mode in windows 10/11 the mouse jumps to host before it gets to the task bar so you can't cick the taskbar in windows its unusable in tablet mode,  but using --mouse 'virtio' you click into the window and the mouse is grabbed and it uses the full aspect of the window and you can then click the taskbar, but you have to press ctrl alt + g to release the mouse

In any linux os with quickemu the default switch works perfectly no issue . you can move the mouse right to the edge of the taskbar and it only  releases the mouse when you go pass it , without having to press ctrl alt + g

so the mouse tablet mode in windows 10/11 has an issue

**Comment by flexiondotorg** [comment]
CLosing due to lack of feedback.
