### ISSUE TITLE
no-template: macos-big-sur/macos-big-sur.pid: No such file or directory

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1239]
# the issue is the path

<pre><code>
/usr/bin/qemu-system-x86_64 \
    -name macos-big-sur,process=macos-big-sur \
    -pidfile macos-big-sur/macos-big-sur.pid \
</pre></code>

any lines that start with macos-big-sur  should begin with ./ not macos-big-sur/

**Comment by flexiondotorg** [comment]
Please complete the issue template.

**Comment by xensurve** [comment]
no wait Im wrong :) let me look at it again
