### ISSUE TITLE
bug: SPICE Window do not working

### ISSUE THREAD

**Issue by bennydente** [quickemu-project/quickemu#1240]
# Expected behavior
command "./quickemu --vm  linuxmint-21.2-cinnamon.conf --display spice" should turn on VM and show Spice Window

# Describe the actual behavior.
command "./quickemu --vm  linuxmint-21.2-cinnamon.conf --display spice"  turn on VM but not show Spice Window

also have same problem with Windows 10 VM.

# Steps to reproduce the behavior
just lunch above command
Also if I check LISTEN port on my host there is not 5930 on LISTEN but only 22220
tcp        0      0 0.0.0.0:22220           0.0.0.0:*               LISTEN

launching command   spicy --title "linuxmint-21.2-cinnamon" --port "5930" 
have this connection refused output
GSpice-Message: 08:22:27.621: main channel: failed to connect
GSpice-Message: 08:22:27.621: channel error: Impossibile connettersi a localhost: Connessione rifiutata

# Additional context

I'm on Fedora 40 host

## System Information
----------------------------------
        Quickemu 4.9.5
----------------------------------
Distro:	Fedora Linux 40 (Workstation Edition)
Kernel:	Linux 6.8.9-300.fc40.x86_64 x86_64
Memory:	16G
GPU:
 - Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by lj3954** [comment]
I can confirm this issue. I'm not exactly sure the cause; my quickemu rewrite works completely fine.

**Comment by LordTlasT** [comment]
I have the same error, I have tried forwarding the port 5930.
```sh
spicy --title "windows-10-English" --port "5930"
```
I get the following error after around a minute:
```
(spicy:34638): GSpice-WARNING **: 10:36:17.107: incomplete link header (-104/16)
GSpice-Message: 10:36:17.107: main channel: failed to connect
```

I have tried installing the `spice-guest-tools` manually on windows, and making it so the service restarts upon crash.

I am on Archlinux and installed the dependencies via the AUR.
l am running quickemu version `4.9.5`.

**Comment by bennydente** [comment]
your fix work. thanks.

**Comment by alexhaydock** [comment]
I'm also on Fedora 40 and I can confirm that the fix in @mjoerg's fork above works to solve the issue.

**Comment by makidoll** [comment]
Thank you so much

**Comment by makew0rld** [comment]
I am also seeing this problem with an Ubuntu guest, so it doesn't seem Windows-specific. I would just get the spice window "connect to spice" pop-up, instead of the actual VM screen, and was unable to connect. Slightly altering quickemu as defined in [this commit](https://github.com/mjoerg/quickemu/commit/5941e87d019094e12fdbed25edef8730d58c6901) worked, as others have found above.

**Comment by makew0rld** [comment]
Looks like there is a PR for this :smile: #1264
