### ISSUE TITLE
Wifi connectivity issue on macOs Big Sur

### ISSUE THREAD

**Issue by N7ghtm4r3** [quickemu-project/quickemu#1250]
Hi, I've create a virtual machine with macOs installed, the `Big Sur` version, and it correctly boots but the networking, in the specific the wifi, doesn't connect successfully because does't find the any networks to connect.
I've read it is needed to use the `bridge=br0` in the related `.conf` file but, also if the bridge has been created on the Ubuntu host machine, when I launch the vm doesn't boot with the message: 
```bash
- Network:  Bridged (br0)
 - Monitor:  On host:  nc -U "macos-big-sur/macos-big-sur-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-big-sur/macos-big-sur-monitor.socket
 - Serial:   On host:  nc -U "macos-big-sur/macos-big-sur-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-big-sur/macos-big-sur-serial.socket
cat: macos-big-sur/macos-big-sur.pid: No such file or directory
 - Process:  Starting macos-big-sur.conf as macos-big-sur ()
``` 
May I have wrong any steps to execute correctly with the bridge or it is possible don't use the brigde and connect directly from the vm machine? Thank you!
-->

# Expected behavior

Wifi connected succesfully 

## Actual behavior

The wifi actually cannot connect or detect any networks

**Comment by lj3954** [comment]
Please provide the contents of the .log file located within your VM directory.

**Comment by N7ghtm4r3** [comment]
The issue solved, I've reinstalled the vm and the wifi started to work, but thank you anyway for the reply
