### ISSUE TITLE
MacOS Sonoma - after install, boot requires user intervention

### ISSUE THREAD

**Issue by ant9000** [quickemu-project/quickemu#1259]
At boot, I'm presented with the following options:

![macos-sonoma](https://github.com/quickemu-project/quickemu/assets/803884/e52b47d7-6ee5-460a-957a-ae13378ffa74)

If no input is received, after a while the bootloader starts the first partition (the one labeled EFI) and then boot stops at a black screen. This is not a problem if the VM is used interactively - but rules out a headless VM. 

Inside MacOS, I have changed the startup disk to the system partition (in the screenshot above, simply named "Disk"): unfortunately, my choice is ignored by the bootloader.

Could this be an issue with regards to NVRAM emulation? Maybe just disabled write support?

Attached is my [quickreport.txt](https://github.com/quickemu-project/quickemu/files/15499892/quickreport.txt) log.

Thanks for any pointer - and for the brilliant job!

Antonio

**Comment by ant9000** [comment]
I tested with `nvram` command: any variable I save into NVRAM does not persist across reboots - this explains why the startup disk selection does not stick.

**Comment by ant9000** [comment]
I had to learn my way about OpenCore, but eventually found how to accomplish my goal - i.e. starting the OS with no user intervention.

In a terminal, mount the EFI partition corresponding to OpenCore:

```
sudo -i
efi_part=/dev/$(diskutil list | grep EFI | grep -v disk0 | awk '{ print $6 }')
diskutil mount $efi_part
```
Edit the OpenCore configuration file  `/Volumes/EFI/EFI/OC/config.plist`, and change `ScanPolicy` value from 0 to 16777475, which corresponds to
```
OC_SCAN_FILE_SYSTEM_LOCK
OC_SCAN_DEVICE_LOCK
OC_SCAN_ALLOW_FS_APFS
OC_SCAN_ALLOW_DEVICE_PCI
```
(see [here](https://oc-scanpolicy.vercel.app/) for an online calculator).

You might also want to hide non relevant partitions, setting `HideAuxiliary` to true (pressing <space> will make everything visibile again).

You can now unmount the partition and reboot:

```
diskutil umount $efi_part
reboot
```

**Comment by ant9000** [comment]
For the record: the above customization does not need to be done from inside MacOS - could be performed on the Linux host too.
The commands for mounting the OpenCore partition are:
```
cd macos-sonoma
mkdir mnt
guestmount -a OpenCore.qcow2 -m /dev/sda1 mnt
```
then you edit the `mnt/EFI/OC/config.plist` as above. To unmount:

```
guestunmount mnt
rmdir mnt
```

**Comment by Rutik7066** [comment]
@ant9000  cann't we simply pass args in extra `-boot drive=c` to start directly using system disk.

**Comment by azun-k** [comment]
@ant9000 i'm having an empty EFI. can you please share how you could generate your EFI's contents? 🙇 

i was using a Ubuntu and created a Sonoma VM by following this: https://github.com/quickemu-project/quickemu/wiki/03-Create-macOS-virtual-machines

**Comment by ant9000** [comment]
I did not generate anything on my own: all the magic was done by Quickemu itself. Haven't rebuilt any VM in a while, though - dunno if my solution is still needed or not.

**Comment by azun-k** [comment]
@ant9000 thanks for the info 🙇. Perhaps, my Ubuntu instance has an issue.
