### ISSUE TITLE
Add spice-app support via virt-viewer; requires virt-viewer 8.0 or newer

### ISSUE THREAD

**Issue by flexiondotorg** [quickemu-project/quickemu#127]
Add support for starting VM via `virt-vewer` 8.0.0 and new by using `--display spice-app`.

**Comment by infokiller** [comment]
I'm interested in this since AFAIK there's no way to ungrab the keyboard from spicy/spice-gtk, see [this recent issue](https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/146).
The developers also state in that issue that spicy is not meant for end users, but for developers & testing.

**Comment by infokiller** [comment]
Looking at the virt-viewer man page, it seems a VM must be registered with libvirt in order to use virt-viewer.
So this issue (and more) will be resolved when https://github.com/quickemu-project/quickemu/issues/437 is resolved

**Comment by flexiondotorg** [comment]
Closed via #510
