### ISSUE TITLE
feat: PXE install testing

### ISSUE THREAD

**Issue by papamoose** [quickemu-project/quickemu#1281]
Add the ability to quickly spin up vm that will test PXE installs in various configurations.

* Network in bridged mode.
* secure boot on or off
* uefi enabled or not

The goal is to test automatic installations (preseed, kickstart, autoyast, etc) via PXE, iPXE, networked grub.

**Comment by flexiondotorg** [comment]
Quickemu supports bridged networking, secure boot on/off and UEFI or legacy boot. Creating the test platform you request is out of scope for the project, but could be implemented as a separate related project :slightly_smiling_face:
