### ISSUE TITLE
feat: update PPA signing key

### ISSUE THREAD

**Issue by papamoose** [quickemu-project/quickemu#1284]
https://launchpad.net/~flexiondotorg/+archive/ubuntu/quickemu

https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854

In Ubuntu 24.04:
```
# apt-get update
...
W: https://ppa.launchpadcontent.net/flexiondotorg/quickemu/ubuntu/dists/noble/InRelease: Signature by key 824A27DD09DEDA33BF7835962EA8F35793D8809A uses weak algorithm (rsa1024)
```

**Comment by marksergeant** [comment]
Confirmed, same here.

**Comment by flexiondotorg** [comment]
There is nothing I can do to affect this change. PPAs will be updated to an RSA 4096 key in due course as described here:

- https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854/6

I am already using an RSA 4096 key to sign my packages.
