### ISSUE TITLE
Feature request: add unattended Windows installation

### ISSUE THREAD

**Issue by pxmqsbqc** [quickemu-project/quickemu#1286]
In deference to its name, I believe Quickemu should add the ability to do an unattended installation of Windows in order to speed up the installation process.

To do this, simply generate an unattend.iso file (e.g., via (https://schneegans.de/windows/unattend-generator/)) containing a configuration xml file and mount it along with the Windows iso.

**Comment by lj3954** [comment]
This feature is already present.
