### ISSUE TITLE
more-info: Every Vm gives error that pid file not found

### ISSUE THREAD

**Issue by snowluminum** [quickemu-project/quickemu#1288]
Any VM says cat: [vm-name].pid no such file or directory.

Running on Ubuntu server 24.04

**Comment by lj3954** [comment]
Please provide the contents of the .log file within your VM directory.

**Comment by printpagestopdf** [comment]
Same problem here, but I changed to development version from git (version 4.9.5) this seems to work

**Comment by snowluminum** [comment]
> Please provide the contents of the .log file within your VM directory.

single line in log
[macos-sonoma.log](https://github.com/user-attachments/files/15957111/macos-sonoma.log)

`qemu-system-x86_64: could not stat pidfile /run/user/1000/pulse/pid: No such file or directory`

**Comment by snowluminum** [comment]
System is fresh install with 2 differences 

Samba was installed not for qemu
default ssh port changed

**Comment by lj3954** [comment]
> > Please provide the contents of the .log file within your VM directory.
> 
> single line in log [macos-sonoma.log](https://github.com/user-attachments/files/15957111/macos-sonoma.log)
> 
> `qemu-system-x86_64: could not stat pidfile /run/user/1000/pulse/pid: No such file or directory`
> 
> contents of macos-sonoma folder
> 
> ![image](https://private-user-images.githubusercontent.com/45245153/342373337-6c7334dd-27b9-4200-a1b4-3f46d9ac0564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDUyMzEsIm5iZiI6MTcxOTI0NDkzMSwicGF0aCI6Ii80NTI0NTE1My8zNDIzNzMzMzctNmM3MzM0ZGQtMjdiOS00MjAwLWExYjQtM2Y0NmQ5YWMwNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZWM4N2RjZjFkZDY1ZmVhNzYxYzY5MDBhYTk1M2IzOWM3MDE3YTEyYzk4MzE1ODgyNmVmMTg3ZDVkZjAwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZR7fjStflTbppdb__kad_jsscWNVfbMWk8zpryFz_Yg)



> > Please provide the contents of the .log file within your VM directory.
> 
> single line in log [macos-sonoma.log](https://github.com/user-attachments/files/15957111/macos-sonoma.log)
> 
> `qemu-system-x86_64: could not stat pidfile /run/user/1000/pulse/pid: No such file or directory`
> 
> contents of macos-sonoma folder
> 
> ![image](https://private-user-images.githubusercontent.com/45245153/342373337-6c7334dd-27b9-4200-a1b4-3f46d9ac0564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDUyMzEsIm5iZiI6MTcxOTI0NDkzMSwicGF0aCI6Ii80NTI0NTE1My8zNDIzNzMzMzctNmM3MzM0ZGQtMjdiOS00MjAwLWExYjQtM2Y0NmQ5YWMwNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZWM4N2RjZjFkZDY1ZmVhNzYxYzY5MDBhYTk1M2IzOWM3MDE3YTEyYzk4MzE1ODgyNmVmMTg3ZDVkZjAwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZR7fjStflTbppdb__kad_jsscWNVfbMWk8zpryFz_Yg)



> > Please provide the contents of the .log file within your VM directory.
> 
> single line in log [macos-sonoma.log](https://github.com/user-attachments/files/15957111/macos-sonoma.log)
> 
> `qemu-system-x86_64: could not stat pidfile /run/user/1000/pulse/pid: No such file or directory`
> 
> contents of macos-sonoma folder
> 
> ![image](https://private-user-images.githubusercontent.com/45245153/342373337-6c7334dd-27b9-4200-a1b4-3f46d9ac0564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDUyMzEsIm5iZiI6MTcxOTI0NDkzMSwicGF0aCI6Ii80NTI0NTE1My8zNDIzNzMzMzctNmM3MzM0ZGQtMjdiOS00MjAwLWExYjQtM2Y0NmQ5YWMwNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZWM4N2RjZjFkZDY1ZmVhNzYxYzY5MDBhYTk1M2IzOWM3MDE3YTEyYzk4MzE1ODgyNmVmMTg3ZDVkZjAwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZR7fjStflTbppdb__kad_jsscWNVfbMWk8zpryFz_Yg)

Looks like you're experiencing an issue with PulseAudio. That is out of the scope of the quickemu project.

**Comment by NestorLiao** [comment]
for me, on nixos, I run:
quickemu --vm nixos-unstable-plasma.conf 
get could not stat pidfile /run/user/1000/pulse/pid
with suffix --display spice:
quickemu --vm nixos-unstable-plasma.conf --display spice
it works to open the vm.
