### ISSUE TITLE
bug: Windows Server has no network post-install

### ISSUE THREAD

**Issue by ralight** [quickemu-project/quickemu#1315]
I created a new vm with 

```
quickget windows-server 2019
quickemu --vm windows-server-2019.conf
```

After carrying out the manual installation and rebooting a few times, there was no networking and no network interface shown in the network settings. Looking in the Device Manager in Control Panel, I could see an Ethernet adapter was present, but "unknown".

I edited the file `windows-server-2019/windows-server-2019.sh` and changed the line `-device virtio-net,netdev=nic` to `-device e1000,netdev=nic` then ran that script by hand. When Windows booted, I had networking available.

**Comment by flexiondotorg** [comment]
This is sort of expected.

Unlike Windows 10 and 11, Quickemu doesn't automatically install the VirtIO drivers for Windows Server editions, so they need to be installed manually. Or, as you did, coerce QEMU to use a well-supported network interface.

I'm not sure how best to tackle this :thinking:

The easiest is to have `quickemu` default to the e1000 device for Windows Server VMs. An optional solution would be to automatically expose/install the VirtIO drivers for Windows Server installs.

**Comment by philclifford** [comment]
How about defaulting to the e1000 device approach (easy and working), then providing the option (parameter or ENV test ? ) for users who wish to "pollute"/enhance their server VM with VirtIO drivers to trigger the installation and configuration of VirtIO. Just thinking that users with use-cases for a server VM might prefer the option whether or not to pre-install anything to their base install.
