### ISSUE TITLE
new-os: missing support for Windows 1.0 through to 8

### ISSUE THREAD

**Issue by piggz** [quickemu-project/quickemu#1351]
From the fun-but-no-at-all-useful pile, i propose it might be nice to easily build obsolete windows versions for historical, fun and educational purposes.  The list would be something like
Windows 1.0
Windows 2.0
Windows 3.0
Windows 3.1
Windows for Workgroups 3.11
Windows 95 (OSR2?)
Windows 98
Windows 98SE
Windows Me
NT 3.1
NT 4.0
Windows 2000
Windows XP
Vista
Windows 7
Windows 8

**Comment by flexiondotorg** [comment]
Sorry, this is out of the scope of the project.
