### ISSUE TITLE
feat: Allow local ISOs

### ISSUE THREAD

**Issue by jon-peel** [quickemu-project/quickemu#1374]
**I confirm this feature has not been previously requested**
- [ X] I have searched the issues and this feature has not previously been requested

**Is your feature request related to a problem? Please describe.**
I am trying to use quickemu to configure a Windows 10 VM.
Because of limited bandwidth, I need to download the ISO on a different computer and copy it over.
Is there an argument I can user on quickget to point to the local ISO?

**Describe the solution you'd like**
Allow me to specify I local Windows 10 ISO.

**Describe alternatives you've considered**
Alternative is to skip quickemu and use virt-manager.

**Comment by lj3954** [comment]
Quickget offers a --create-config option, where you specify a VM name & a path to an image. Unfortunately, quickemu's unattended windows installation isn't currently supported out of the box in this way (tracking: #1369)

**Comment by philclifford** [comment]
If you have the iso locally you can just drop it into the VM directory with the filename the VM expects and quickget should just verify it and be happy.
