### ISSUE TITLE
feat: Enable GPU hardware acceleration

### ISSUE THREAD

**Issue by mb720** [quickemu-project/quickemu#1389]
**I confirm this feature has not been previously requested**
- [x] I have searched the issues and this feature has not previously been requested

**Is your feature request related to a problem? Please describe.**
Video playback in Safari is very slow and stutters. The background video in macOS Sonoma ("Sonoma Horizon") is not rendered:

![screen_2024-07-20_01-09-01](https://github.com/user-attachments/assets/76f2961c-6b47-4b21-9ecf-2beaa243cb1b)

**Describe the solution you'd like**
If possible, the guest OS is able to use the graphics card of the host.

**Describe alternatives you've considered**
None.

**Additional context**
I'm running macOS Sonoma on a Framework 16 laptop inside Arch Linux. The Framework comes with two graphics cards: Radeon RX 7700S and Radeon 780M.

**Comment by lj3954** [comment]
No virtualization software on non-apple hosts is capable of emulating a graphics processor with 3D drivers available for macOS. GPU passthrough is being discussed in #812 and #900, but, regardless, macOS support for AMD GPUs past the 5000 series may be questionable at best (AMD iGPUs are out of the question).

**Comment by mb720** [comment]
Thanks for clarifying this and quickemu in general.

I assume then that there's no way to run macOS Sonoma with decent performance on Linux, right?
