### ISSUE TITLE
bug: quickget is unable to download macOS sonoma

### ISSUE THREAD

**Issue by isasmendiagus** [quickemu-project/quickemu#1391]
**Describe the bug**
Unable to download macos sonoma or any other version of macos

**To Reproduce**
1. Run `quickget macos sonoma`
2. See error
```bash 
Downloading macOS (Sonoma) RecoveryImage
 - URL: 
curl: (3) URL rejected: Malformed input to a URL function
ERROR! Failed to download  with curl.
curl: (3) URL rejected: Malformed input to a URL function
ERROR! Failed to download  with curl.
 WARNING! Verification failed, continuing anyway
rm: cannot remove 'macos-sonoma/RecoveryImage.dmg': No such file or directory
rm: cannot remove 'macos-sonoma/RecoveryImage.chunklist': No such file or directory

```

**Expected behavior**
The tool should download the macOS image

**Additional context**
I'm running quickget on ubuntu 24.04 and was installed from the .deb package

**Comment by siredmar** [comment]
@flexiondotorg i freshly downloaded quickget (002e3665525562386f7c5018cae2a60ac9c2fb12) and i get exactly the same error. Downloading any macos version fails with the same error.

Maybe the address `osrecovery.apple.com` changed?

**Comment by philclifford** [comment]
> Maybe the address `osrecovery.apple.com` changed?
Download of Sonoma seems fine here :shrug:

**Comment by siredmar** [comment]
@philclifford can you tell me which exact version (git commit) you use and the command you are using?
It's still failing on my side :(

**Comment by philclifford** [comment]
just tried from 8eda1e11506ff7948fb2ada8707932ce03bc9dff (latest HEAD) in :scotland: (UK)

``` shell
$ ./quickget macos sonoma
Downloading macOS (Sonoma) RecoveryImage
 - URL: http://oscdn.apple.com/content/downloads/11/58/062-53943/of12aseueo2jnehp03qh5g3o17lx4139t1/RecoveryImage/BaseSystem.dmg
#####                                                                                                                                                                                                                         2.4%^C
```
Could be region-related but I think unlikely.  Do you have any ad-blocking/script filtering stuff between your terminal and their server ?

**Comment by philclifford** [comment]
osrecovery.apple.com is an alias for osrecovery.swu-apple.com.akadns.net.
osrecovery.swu-apple.com.akadns.net has address 17.57.21.52

**Comment by siredmar** [comment]
@philclifford i'm still failing to get this to work. 
Can you tell me which version of bash and curl you got?

```
$ bash --version
bash --version
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
```

```
$ curl --version
curl --version
curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7
Release-Date: 2023-12-06, security patched: 8.5.0-2ubuntu10.4
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

**Comment by siredmar** [comment]
>Could be region-related but I think unlikely. Do you have any ad-blocking/script filtering stuff between your terminal and their server ?

I do have pi-hole running, but also tested it disabling it completely.

**Comment by philclifford** [comment]
@siredmar 
``` text
$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by philclifford** [comment]
A VPN might diagnose region blocking (or add VPN blocking), or maybe spin up a temporary proxy on a VPS (or an exit node there via `tailscale` ...).  Another thought might be they're blocking specific IPs/IP ranges - I'd try using my phone's wifi or take a laptop to the pub but those might not be an option for you.

**Comment by siredmar** [comment]
I grabbed a 30 days free trial of NordVPN and just connected to any random server (it's also in germany). Now the downloads works. 

So i'm not sure what's going on and why curl states this `URL rejected: Malformed input to a URL function`

Maybe this is worth mentioning in the projects Readme that for currently unknown reasons the download might fail and that in such cases a VPN service could help.

**Comment by elwoodhouse** [comment]
I had to turn off my vpn to be able to download the recovery image. Maybe that should be put in the guide if it isn't already.

**Comment by philclifford** [comment]
Note added to https://github.com/quickemu-project/quickemu/wiki/03-Create-macOS-virtual-machines. Will add to man sources for next regeneration.
