### ISSUE TITLE
bug: smb support broken

### ISSUE THREAD

**Issue by mash-graz** [quickemu-project/quickemu#1409]
**I confirm this bug has not already been reported**
- [*] I have searched the issues and this bug has not been reported previously 

...but it's caused by an attempt to fix (#754) another issue (#722)

**Describe the bug**

The samba demon will not be started, because it will not be found by the mechanism suggested in #722 / #754
**It would only work, if "/usr/sbin/" is included in your [search-]PATH**, but that's usually not the case for ordinary users.

**To Reproduce**

As long as this "Fix" doesn't get reverted the qemu-smb-entry will never be used on `debian GNU Linux` systems and similar setups.  

**Expected behavior**

The smb related qemu entry should be used, if samba is installed at the common location on the machine and the PUBLIC directory exists -- i.e. just the old behavior!

Please revert #754

**Comment by philclifford** [comment]
Reverting will, I believe, create a regression for NixOS users.
I may have a solution ..

**Comment by mash-graz** [comment]
A logical OR between both tests concerning the availability of `smbd` could possibly make all users happy.

    ... [[ -e "/usr/sbin/smbd"  || -x "$(command -v smbd)"  ]] ...

Nevertheless, in its present variant it's expecting a system behavior, which simply violates the GNU Linux Filesystem Hierarchy Standard (FHS), where `/usr/sbin/` is reserved for [*binaries used exclusively by the system administrator*](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s10.html).
