### ISSUE TITLE
Set refresh rate?

### ISSUE THREAD

**Issue by GanerCodes** [quickemu-project/quickemu#1411]
Is it possible to set the refresh rate of a VM? if not I think there should be

**Comment by flexiondotorg** [comment]
What refresh rate are you referring to?

**Comment by GanerCodes** [comment]
> What refresh rate are you referring to?

Display refresh rate, it's capped at 60fps currently

**Comment by flexiondotorg** [comment]
The refresh rate is governed by the virtualization drivers; this is not something Quickemu can configure.
