### ISSUE TITLE
bug: BlendOS downloads are broken

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#1437]
**I confirm this bug has not already been reported**
- [x] I have searched the issues and this bug has not been reported previously

**Describe the bug**
The BlendOS website has evolved and our parsing needs to adapt to find release and download info reliably.

**To Reproduce**
run `quickget list` or quickget blendos` 

**Expected behavior**
list output should include a line for BlendOS and we should find the releases (and editions)

**Quickget output**
Run `quickemu` or `quickemu` and include the output of the failure below:

<details>
  <summary>Quickget output</summary>

  ```text
./quickget blendos

BlendOS
 - Credentials:	-
 - Website:	https://blendos.co/
 - Description:	A seamless blend of all Linux distributions. Allows you to have an immutable, atomic and declarative Arch Linux system, with application support from several Linux distributions & Android.
 - Releases:	
 - Editions:	

  ```
</details>

**Comment by lj3954** [comment]
blendOS v4 has only 1 ISO available, releases and editions are no longer relevant.

**Comment by Tetractys** [comment]
I'm new. So, download the ISO and install it via quickemu?
