### ISSUE TITLE
feat: Wait for manual donwload

### ISSUE THREAD

**Issue by Pastitas** [quickemu-project/quickemu#1447]
**I confirm this feature has not been previously requested**
- [X] I have searched the issues and this feature has not previously been requested

**Is your feature request related to a problem? Please describe.**
When the iso download fails the program warns and instructs you to download manually, but this becomes a race against the program if you'd want some processing after the fact for the iso (Ej, windows iso with unattended tweaks).

**Describe the solution you'd like**
Some kind of flag or option that allows for waiting for user input after instructing to manually download.

**Describe alternatives you've considered**
What I've done is download in advance and use the virtio driver download time as a time window to get the iso into the folder

**Comment by lj3954** [comment]
Since #1373, you can create a custom VM with your own Windows ISO; quickget will automatically detect Windows ISOs with a regex and download drivers, unattended setup, etc.
