### ISSUE TITLE
bug: fedora releases shows 41 and beta

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#1462]
**I confirm this bug has not already been reported**
- [x] I have searched the issues and this bug has not been reported previously

**Describe the bug**
`quickget fedora` offers in releases also nonexistent beta and 41 release

`quickget fedora 41 KDE`

```
curl: option : blank argument where content is expected
curl: try 'curl --help' or 'curl --manual' for more information
Downloading Fedora 41 KDE
- URL:
curl: option : blank argument where content is expected
curl: try 'curl --help' or 'curl --manual' for more information
ERROR! Failed to download  with curl.
rm: cannot remove 'fedora-41-KDE/': Is a directory
Making fedora-41-KDE.conf
 - Setting fedora-41-KDE.conf executable

To start your Fedora virtual machine run:
    quickemu --vm fedora-41-KDE.conf
```

So directory and config file was created even if link doesn't exist

**Comment by shawnyeager** [comment]
My assumption is that what it’s returning is `41 Beta`, but there doesn’t appear to be a way of passing that to `quickget` successfully. I’ve tried both of the following, neither of which worked. 

`> quickget fedora 41\ Beta Workstation`

and

`> quickget fedora ‘41 Beta’ Workstation`

**Comment by EugenioMoro** [comment]
`quickget fedora 43 KDE` gives the same issue
