### ISSUE TITLE
bug: macOS Installation hangs

### ISSUE THREAD

**Issue by YuvanMichaelVivenzi** [quickemu-project/quickemu#1482]
**I confirm this bug has not already been reported**
- [x] I have searched the issues and this bug has not been reported previously >> YES

**Describe the bug**
A clear and concise description of what the bug is. >> I have a Apple Logo stuck on less than a minute remaining. 

I force closed the vm and tried again reinstalling, one time I had a system lockup as I ran out of memory including 10G swap space. 

I tried using a 32G swap space and Installing macOS Monterey, after a long time like a few hours it felt like it was going to restart and it just showed a black screen for a while. I have done this 3 times now and I'm getting burnt out, Please tell me what I should do.

CPU: Intel Core i5 with 4 cores (2 cores allotted for big-sur and all 4 cores now for Monterey)
RAM: 4GB (On which both Arch Linux and macOS run) + 32GB swap
GPU: Intel Xeon E-3

Current situation: After installing Monterey today, I now have a black screen on which I force quit the spicy application from File >> Quit.

Below is a screenshot of when I tried installing big sur yesterday and it installed in 6 hours or so and I went through the 30 min waiting time and then I waited from 10:00PM to like 11:30PM when it still said "Less than a minute remaining" I had nothing other than this VM open. 

![IMG_20241016_220839](https://github.com/user-attachments/assets/c6b79bf3-3ae9-4d4c-84d9-30ddde656998)

**Comment by YuvanMichaelVivenzi** [comment]
Deleted all vm's used the git version made a fresh new mojave install that took 10 hrs. And I got to the Welcome screen. So, installation doesn't hang, Just takes a very loooooong time. Guess that's because of my PC.

**Comment by YuvanMichaelVivenzi** [comment]
But my mouse cursor only reaches half of the screen. Making this a new issue.

**Comment by Th1s1sm4ry** [comment]
Experiencing the same thing here. 
Had previously tested with macOS monterey. All default and followed the wiki. Test successful: macOS Monterey booted. 

I deleted the monterey and deciding to use macOS mojave. Configured cores, RAM and disk space to half of my hardware (ie 6 cores, 8GB, 100G).

Estimation says: About 11minutes remaining. Its been about 20min now. My whole system is not responding. Mouse is very slow.
