### ISSUE TITLE
feat: Have a new command-line argument to expose smb folder to share from host to guest

### ISSUE THREAD

**Issue by danhertztech** [quickemu-project/quickemu#1535]
**I confirm this feature has not been previously requested**
- [ x] I have searched the issues and this feature has not previously been requested

**Is your feature request related to a problem? Please describe.**
I am able to use smb on my guest machine to see and interact with files on my host's ~/Public folder (use smb://10.0.2.4/qemu in guest).  I would like to expose my user $HOME folder, or $HOME/documents folder, instead. Is that possible, and if so, what settings do I need to make?

**Describe the solution you'd like**
Run "quickemu --display spice" and add another switch to specify shared smb folder (e.g. "--smb-folder /root/home/username/documents")

**Describe alternatives you've considered**
No alternatives. For now I move the files to the ~/Public folder, and move them back when I'm done accessing them in my VM. Not a good work flow.

**Additional context**
I am on PopOS! (Ubuntu) host, using MacOS Monterey and Windows 11 guests.

I checked the following info:
[https://github.com/quickemu-project/quickemu/wiki/05-Advanced-quickemu-configuration/2f9ba59ba41f3b0bc38fd32f9ef2395d830acca3#samba---](https://github.com/quickemu-project/quickemu/wiki/05-Advanced-quickemu-configuration/2f9ba59ba41f3b0bc38fd32f9ef2395d830acca3#samba---)

[https://www.reddit.com/r/commandline/comments/v85fmx/comment/ibz09si/](https://www.reddit.com/r/commandline/comments/v85fmx/comment/ibz09si/)

Thank you for your assistance!

**Comment by lj3954** [comment]
The --public-dir command line flag is what you're looking for.

**Comment by danhertztech** [comment]
Thanks so much...works perfectly. I appreciate the clear explanation, and that you took the time to respond. Vert thoughtful of you.
