### ISSUE TITLE
Windows 10 and 11 crash every other boot

### ISSUE THREAD

**Issue by Lukewh** [quickemu-project/quickemu#162]
#### Expected behaviour

Windows 10 and 11 boot ;)

#### Actual behaviour

Occasionally, the VM crashes at the 'BIOS' stage, and no Windows spinner displays.

#### Steps to reproduce the behaviour

Now I'm writing this report, it's not happening. I will endeavour to find a way to reproduce it consistently.

#### Quickemu output

```
~/vms quickemu --vm windows-11.conf 
Quickemu 2.2.7 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.04 running Linux 5.11 (graeme-nolegs)
 - CPU:      Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 1 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/luke/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11.swtpm-sock (36330)
 - Process:  Starting windows-11.conf as windows-11 (36332)

```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

uname -a
Linux graeme-nolegs 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SneWs** [comment]
@charles-hood on Ubuntu the command `echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs` as mentioned in the output fixed sporading bluescreens and boot hangs for myself for both Windows 10 and 11

**Comment by Lukewh** [comment]
@SneWs interesting, I'll try that on the machine that is hitting the issue. I noticed in the Quickemu output there's a built in command for MSR which I ran on my main machine that it was happening on, and it hasn't happened since 🤔

**Comment by charles-hood** [comment]
I'm still having this problem.

**Comment by flexiondotorg** [comment]
I am still seeing Windows 10 fail to start every other boot attempt.

**Comment by flexiondotorg** [comment]
Things I've ruled out as causes:

  * Disabling hyper-threading doesn't help
  * Disabling SecureBoot doesn't help

**Comment by cowboygeneral** [comment]
From within the Windows guest, launch a cmd prompt with Admin privileges
type: powercfg -h off
(this turns off hibernation and thus also turns off fastboot)
