### ISSUE TITLE
Add paths to OVMF firmware on NixOS to quickemu

### ISSUE THREAD

**Issue by FedX-sudo** [quickemu-project/quickemu#166]
#### Expected behaviour

I run `quickemu --vm <vm-config.conf> and a vm starts. 

#### Actual behaviour

I run `quickemu --vm <vm-config.conf>` and get `ERROR! EFI boot requested but no EFI firmware found.`
This is only present on 2.2.7, rolling back to 2.2.6 fixes the issue. 

#### Steps to reproduce the behaviour

I believe this is a highly specific use-case, and the following steps will be required: 

1.  A System76 Open Firmware or other Coreboot computer. 
2.  NixOS is installed on the computer. 
3. Quickemu is installed by compileing the package from nixpkgs (IE, clone the repo and run `nix-build -A quickemu` then `nix-env -i /path/to/output/of/build`). 
4. There is no step 4. 

#### Quickemu output

```Quickemu 2.2.7 using /nix/store/f0n7f930xvlps710n52np2f1skwj6p90-qemu-6.1.0/bin/qemu-system-x86_64 v6.1.0
 - Host:     "NixOS 21.11 (Porcupine)" running Linux 5.10 (SpaceBusOS)
 - CPU:      11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
ERROR! EFI boot requested but no EFI firmware found.
```
#### Linux Distribution & Kernel

* NixOS 21.11 Porcupine
* Kernel 5.10.75 
* Potentialy important to note as well: 2021 System76 Galago Pro (Galp5). 

Run the following and paste the output.

```bash
lsb_release --all 
No LSB modules are available.
Distributor ID: NixOS
Description:    NixOS 21.11 (Porcupine)
Release:        21.11
Codename:       porcupine

uname -a 
Linux SpaceBusOS 5.10.75 #1-NixOS SMP Wed Oct 20 09:45:06 UTC 2021 x86_64 GNU/Linux

```

**Comment by flexiondotorg** [comment]
@FedX-sudo Please submit a PR with the correct OVMF paths for NixOS :+1:

**Comment by FedX-sudo** [comment]
I have been working on that, but I have an issue where it is not properly copying EFI vars from the Nix path. It may be an issue in the way I have installed it, but I am unsure at this moment...

**Comment by FedX-sudo** [comment]
Update, it looks like NixOS protects copying the fd file type, so I will need to do some more debugging, and perhaps point quickemu at the base path instead of the copied one.

**Comment by flexiondotorg** [comment]
@FedX-sudo Perhaps `quickget` could be updated to download EFI VARS just as macOS does?

**Comment by FedX-sudo** [comment]
@flexiondotorg That is what I am thinking, where could I get those URLs?

**Comment by 0x4A6F** [comment]
There are two patches I'd like to propose, see NixOS/nixpkgs#149409 that should fix this problem.

- ensuring writable EFI_VARS files
- overriding OVMF file lookups

Are they looking okayish to open two PRs?

**Comment by FedX-sudo** [comment]
Thank you so much! This works perfectly!
