### ISSUE TITLE
Pull data using libosinfo

### ISSUE THREAD

**Issue by charles-hood** [quickemu-project/quickemu#216]
Enhancement Request:
Instead of hard coding info about each OS in the script, lookup the data in osinfo-db using libosinfo.

Ref:  https://libosinfo.org/

Libosinfo provides command line tools for extracting info from the osinfo-db, so it should be fairly straightforward to call from a bash script. The database includes the download location of installable ISO images and Live CDs for many many different OSes. This should allow quickemu to grow the number of OSes it supports very quickly and easily, without hard coding each one into the script, resulting in a cleaner and more generic script. When new OSes or OS versions are added to osinfo-db, quickemu will be able to take advantage of them right away, automatically. Quickemu can focus on it's core logic of making things easy, and making reasonable default choices, without getting bogged down with all the metadata.

**Comment by flexiondotorg** [comment]
There is certainly useful data in osinfo-db, but for many of the desktop Linux distros that Quickget knows about the osinfo-db entries are very out of date. More so, when we refer to macOS and Windows.

I'll leave this here for consideration, but I don't see any immediate value in using osinfo-db.

**Comment by flexiondotorg** [comment]
I see limited value in doing this. Closing this, but will consider in the future.
