### ISSUE TITLE
Cannot install Windows 10 or 11 with Spice display

### ISSUE THREAD

**Issue by ymauray** [quickemu-project/quickemu#231]
#### Expected behavior

Windows-10 (or 11) vm newly created, start the VM. Spice display pops up. Click inside, press a key, VM boots from CD/DVD

#### Actual behaviour

Spice display pops up. Click inside, press a key. Nothing happens, and focus is grabbed.

#### Quickemu output

```
quickemu --vm windows-10.conf --display spice
Quickemu 2.3.2 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.04 running Linux 5.11 (heimdall)
 - CPU:      Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 1 Thread(s), 4G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
             Looks unused, booting from windows-10/Win10_21H1_French_x64.iso
 - Boot ISO: windows-10/Win10_21H1_French_x64.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-10" --port 5930 --spice-shared-dir /home/yannick/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Process:  Starting windows-10.conf as windows-10 (479724)
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

$ uname -a
Linux heimdall 5.11.0-40-lowlatency #44-Ubuntu SMP PREEMPT Wed Oct 20 21:15:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mackncheesiest** [comment]
I had to go through the installation with the default `sdl` display, but once installation was complete, I was able to use the `spice` display option

**Comment by Jai-JAP** [comment]
Same Issue on Ubuntu 20.04 with Win 10 / 11 installation

**Comment by Ryoh-a** [comment]
When I tried installing it started similar to the above mentioned problem. I'd leave it for a bit and then Windows would get to the "press any key..." part but it wouldn't register a key press fro some reason. I'd have to wait until it failed to the shell, then follow the steps posted in a previous replay.

[Process outlined here](
https://github.com/quickemu-project/quickemu/issues/86#issuecomment-1057224372)

After a little patience it worked
