### ISSUE TITLE
Regolith github / aws slow to arrive for 1.6 releases

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#237]
Just a note that downloads of the release branches of Regolith (1.6) are broken today 
Discovered in testing/validation. So any reports of breakage of `quickget` for them need re-directing upstream 
for now.

**Comment by philclifford** [comment]
It seems they have an ongoing issue - the 1.6 releases can be downloaded but nothing starts arriving from AWS (then end of the redirects from the github release link) for around 3 minutes. So you just have to wait.

**Comment by flexiondotorg** [comment]
Is this our issue to fix @philclifford?

**Comment by philclifford** [comment]
Definitely not our problem, but worth leaving a note about while they fix
it I thought, not that anyone has reported problems.

**Comment by flexiondotorg** [comment]
I'll close this. If there is not an actual problem and we unable to resolve it there is little point keeping an open issue for it.
