### ISSUE TITLE
ERROR! Qemu 6.0.0 or newer is required, detected 4.2.1.

### ISSUE THREAD

**Issue by hdhnl** [quickemu-project/quickemu#247]
#### Expected behaviour

Quickemu Installation. :smile:

#### Actual behaviour

`ERROR`. :disappointed_relieved:

#### Steps to reproduce the behaviour
```
sudo apt install -y git devscripts build-essential cmake ninja-build
git clone https://github.com/wimpysworld/quickemu.git
snap install qemu-virgil --edge
snap connect qemu-virgil:kvm
snap connect qemu-virgil:raw-usb
snap connect qemu-virgil:removable-media
```
```
#after quickget
cd quickemu/
./quickemu --vm elementary-6.0.conf
```
#### Quickemu output

`ERROR! Qemu 6.0.0 or newer is required, detected 4.2.1.`

#### Linux Distribution & Kernel

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Linux hdhnl 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daPhipz** [comment]
Please use the PPA as documented in the README. The `qemu-virgil` snap is no longer a dependency of `quickemu`.

**Comment by hdhnl** [comment]
> Please use the PPA as documented in the README. The `qemu-virgil` snap is no longer a dependency of `quickemu`.

I tried it first.
I get the same error message

**Comment by daPhipz** [comment]
Then, I'd suggest to remove your existing `qemu` install and try again. Virtual Machine Manager should work with the PPA version of `qemu` just fine :)

**Comment by hdhnl** [comment]
Thank you very much @daPhipz .
The issue is solved.
```
sudo apt remove qemu-system-x86
snap list
sudo snap remove qemu-virgil
```
Finally I followed the ppa installation procedure.

**Comment by hdhnl** [comment]
> Then, I'd suggest to remove your existing `qemu` install and try again. Virtual Machine Manager should work with the PPA version of `qemu` just fine :)

**Comment by daPhipz** [comment]
No problem - glad I could help! ☺️👍
