### ISSUE TITLE
Add man pages for quickemu and quickget

### ISSUE THREAD

**Issue by caltrop2075** [quickemu-project/quickemu#249]
#### Expected behaviour
a man page

Describe the your expected behaviour.

#### Actual behaviour
no man page

Describe the actual behaviour.

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```

**Comment by daPhipz** [comment]
This is to be expected, since nobody created a manpage for `Quickemu` yet.
I too think it would be a good idea to create one - feel free to start working on that, if you want! :)
