### ISSUE TITLE
quickget windows 11 "Chinese (Traditional)" get "ERROR"

### ISSUE THREAD

**Issue by antonyshen** [quickemu-project/quickemu#250]
#### Expected behaviour

Per the description in readme, it should work; however when run the command it gives ERROR! like below:

#### Actual behaviour

$ ~/projs/quickemu/quickget windows 11 "Chinese (Traditional)"
ERROR! Chinese (Traditional) is not a supported language:
Arabic
Brazilian Portuguese
Bulgarian
Chinese (Simplified)
Chinese (Traditional)
Croatian
Czech
Danish
Dutch
English
English International
Estonian
Finnish
FrenchERROR! Chinese (Traditional) is not a supported language:
Arabic
Brazilian Portuguese
Bulgarian
Chinese (Simplified)
Chinese (Traditional)
Croatian
Czech
Danish
Dutch
English
English International
Estonian
Finnish
French
French Canadian
German
Greek
Hebrew
Hungarian
Italian
Japanese
Korean
Latvian
Lithuanian
Norwegian
Polish
Portuguese
Romanian
Russian
Serbian Latin
Slovak
Slovenian
Spanish
Spanish (Mexico)
Swedish
Thai
Turkish
Ukrainian

French Canadian
German
Greek
Hebrew
Hungarian
Italian
Japanese
Korean
Latvian
Lithuanian
Norwegian
Polish
Portuguese
Romanian
Russian
Serbian Latin
Slovak
Slovenian
Spanish
Spanish (Mexico)
Swedish
Thai
Turkish
Ukrainian

#### Steps to reproduce the behaviour

Just run 
quickget windows 11 "Chinese (Traditional)"
from command line

#### Quickemu output

Run  `quickget windows 11 "Chinese (Traditional)"` and the output is:
ERROR! Chinese (Traditional) is not a supported language:
Arabic
Brazilian Portuguese
Bulgarian
Chinese (Simplified)
Chinese (Traditional)
Croatian
Czech
Danish
Dutch
English
English International
Estonian
Finnish
French
French Canadian
German
Greek
Hebrew
Hungarian
Italian
Japanese
Korean
Latvian
Lithuanian
Norwegian
Polish
Portuguese
Romanian
Russian
Serbian Latin
Slovak
Slovenian
Spanish
Spanish (Mexico)
Swedish
Thai
Turkish
Ukrainian

#### Linux Distribution & Kernel

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

$ uname -a
Linux us862 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by philclifford** [comment]
Bug: the 3rd-Party API call to get language-specific ISO URLs fails for all language names containing brackets. (Spaces work when quoted but not any with brackets)

**Comment by iHad169** [comment]
me too

**Comment by tootbrute** [comment]
Fixed now but doesn't matter because Microsoft blocks downloads from Taiwan. Did you find a way around that @antonyshen ?

```
~/VMs took 5s ❯ quickget windows 11 "Chinese (Traditional)"
Downloading Windows 11 (Chinese (Traditional))
 - Parsing download page: https://www.microsoft.com/en-us/software-download/windows11
 - Getting Product edition ID: 3113
 - Permit Session ID: 8b3c0bb4-64d4-480f-8586-8d8103c2800c
Failed to contact Microsoft servers! Is there an Internet connection or is the server down?
Downloading VirtIO drivers...
                                                                                                                    0.3%
```

Skips downloading the ISO and goes straight to VirtIO drivers.
