### ISSUE TITLE
add debian (libc6_2.31-13+deb11u2)

### ISSUE THREAD

**Issue by dontknowhy** [quickemu-project/quickemu#252]
WHY NOT DEBIAN???

**Comment by daPhipz** [comment]
WHY ARE YOU SHOUTING? This is not nice.

There already is a PR for debian support (#243), and nobody stops you from using your own ISOs with `quickemu`. See the README for instructions.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/pull/243
