### ISSUE TITLE
trouble install macOS Monterey

### ISSUE THREAD

**Issue by LIlaUraraka** [quickemu-project/quickemu#254]
#### Expected behaviour

macOS Monterey to install

#### Actual behaviour

Operation error PKDownloadError 8

#### Steps to reproduce the behaviour

Not sure, happens every time I attempt to install macOS

#### Quickemu output

none, using QuickGUI (If I can get one with the GUI, I don't know how to get, I am new to this program)

#### Linux Distribution & Kernel

installing macOS Monerey
[Screenshot here](https://imgur.com/4KFrmZ5)

**Comment by daPhipz** [comment]
Hi!
Did you follow the steps listed under the [macOS Guest](https://github.com/quickemu-project/quickemu#macos-guest) section of the README?
There are some things to watch out for when installing a macOS VM with Quickget. Unfortunately, these steps are not really mentioned when installing VMs via the Quickgui GUI (yet - there is an issue filed to improve this: https://github.com/quickgui/quickgui/issues/31).

**Comment by flexiondotorg** [comment]
This is not a bug with Quickemu, but rather a issue with the macOS installer. Not something we can fix. So, I am closing this issue and invite you to join our Discord server where you can discuss how to get the install finished 🙂

  * https://wimpysworld.io/discord
