### ISSUE TITLE
How to install through a .deb file, not through apt-get?

### ISSUE THREAD

**Issue by zhmlcg** [quickemu-project/quickemu#256]
Since I am not a super user, I can't use `sudo apt-get` command to install. So, is there any `.deb` file of quickemu for me to download and run directly in my user space?

**Comment by daPhipz** [comment]
You can try to clone the git repo, as mentioned in the README, and hope that all dependencies are already installed. That is the only way if you don't have superuser access...

**Comment by flexiondotorg** [comment]
Yes, Quickemu can be installed via apt, see the documentation here: 

  * https://github.com/quickemu-project/quickemu#install-quickemu
