### ISSUE TITLE
A PXE boot/install capability for guests

### ISSUE THREAD

**Issue by antonc42** [quickemu-project/quickemu#267]
#### Expected behaviour

Create a Windows (or other OS) VM config that boots via the network (bridge?) and allows for installation via PXE. My workplace uses this as the preferred method for installing a "blessed" Windows image. I'm not sure if this is really a good use case for Quickemu, or if there would be too many unknowns about the PXE image (virtio support).

#### Actual behaviour

Cannot do this.

#### Steps to reproduce the behaviour

Quickget/Quickemu only allows for installation via ISO.

#### Quickemu output

N/A

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

Linux <redacted> 5.10.0-1052-oem #54-Ubuntu SMP Tue Nov 23 09:06:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flexiondotorg** [comment]
I'm not interested in creating this capability myself, but we welcome contributions providing a working solution.

**Comment by MaxPeal** [comment]
+1 for the PXE support!

**Comment by zen0bit** [comment]
Check it...

**Comment by zen0bit** [comment]
new pull request https://github.com/quickemu-project/quickemu/pull/351

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/commit/596ffa86a67e8e5fb1c9531eee8b9aca68511624
