### ISSUE TITLE
Windows 11 asks me to login with instruction or enterprise account

### ISSUE THREAD

**Issue by Bernard996** [quickemu-project/quickemu#269]
#### Expected behaviour

Describe the your expected behaviour.
Windows asks me to login with standard Outlook account

#### Actual behaviour

Describe the actual behaviour.
Windows asks me to login with SAP account (user@contoso.com or user@contoso.onmicrosoft.com)

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.
Just installing Windows 11 and try to make it work

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.
Usage
  quickemu --vm ubuntu.conf

You can also pass optional parameters
  --delete-disk           : Delete the disk image and EFI variables
  --delete-vm             : Delete the entire VM and it's configuration
  --display               : Select display backend. 'sdl' (default), 'gtk', 'none', or 'spice'
  --fullscreen            : Starts VM in full screen mode (Ctl+Alt+f to exit)
  --ignore-msrs-always    : Configure KVM to always ignore unhandled machine-specific registers
  --screen <screen>       : Use specified screen to determine the window size.
  --shortcut              : Create a desktop shortcut
  --snapshot apply <tag>  : Apply/restore a snapshot.
  --snapshot create <tag> : Create a snapshot.
  --snapshot delete <tag> : Delete a snapshot.
  --snapshot info         : Show disk/snapshot info.
  --status-quo            : Do not commit any changes to disk/snapshot.
  --version               : Print version

ERROR! You must specify an operating system:
android archlinux debian elementary freebsd fedora garuda kali kdeneon kubuntu linuxmint-cinnamon linuxmint-mate linuxmint-xfce nixos-gnome nixos-plasma5 nixos-minimal lubuntu macos openbsd opensuse oraclelinux popos regolith rockylinux solus ubuntu ubuntu-budgie ubuntu-kylin ubuntu-mate ubuntu-studio windows xubuntu zorin

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```

LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.0
Codename:       Qonos
Linux vivobook 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux
![Screenshot_20211208_095939](https://user-images.githubusercontent.com/58182902/145179219-de0acf17-7143-49cd-88f0-8d67971854da.jpeg
![Screenshot_20211208_101559](https://user-images.githubusercontent.com/58182902/145181745-ae2d0360-d46f-498b-9260-f0c0c6b3fabd.jpeg)
)

**Comment by daPhipz** [comment]
This is fixed in the [latest release](https://github.com/quickemu-project/quickemu/releases/tag/2.3.4).

**Comment by flexiondotorg** [comment]
Fixed via #270

**Comment by jaylittle** [comment]
Are you sure this is fixed?  I just tried to create a new Windows 11 VM with QuickEMU and ran into a very similar issue.  I can't create a local account and I have no MS account that works with this.  

How do you actually make this work with just a local account?

**Comment by jaylittle** [comment]
Yeah so I tried using my own ISO image and modified a wide variety of settings in the UnAttend XML file to no avail.  Windows 11 VMs created with this tool appear to be useless.  I can only guess that it has something to do with EFI variables.... because nothing else seems to make a difference.
