### ISSUE TITLE
Insufficent RAM

### ISSUE THREAD

**Issue by dacadla** [quickemu-project/quickemu#274]
#### Expected behaviour

1. quickget windows 8 english
2. run quickemu
3. Windows machine starts

#### Actual behaviour

It says: `ERROR! You have insufficient RAM to run windows in a VM` when I try to run it, even though I have more than 2GB of ram.

#### Steps to reproduce the behaviour

1. quickget windows 8 english
2. run quickemu
3. get error

#### Quickemu output

Quickemu 3.11 using /usr/bin/qemu-system-x86_64 v6.0.0
Host:     Pop!_OS 21.04 running Linux 5.13 (dacadla-pop)
CPU:      AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
CPU VM:   1 Socket(s), 1 Core(s), 2 Thread(s), 2G RAM
ERROR! You have insufficient RAM to run windows in a VM

#### Linux Distribution & Kernel
Pop!_OS 21.04 running Linux 5.13

```bash
@ lsb_release --all
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute

@ uname -a
Linux dacadla-pop 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by daPhipz** [comment]
> CPU VM: 1 Socket(s), 1 Core(s), 2 Thread(s), 2G RAM

How much RAM do you have in your machine? This :arrow_up: is how much RAM the host gives to the VM - not the host's total RAM.
In order to function properly, a Windows VM needs at least 4 GB RAM.

**Comment by dacadla** [comment]
I have 6GB of RAM.

**Comment by daPhipz** [comment]
You can manually set the RAM for the VM by adding this line to the config file:

```
ram="4G"
```

Be advised that this has the potential to make the host system unresponsive or even crashing it due to low RAM.

**Comment by dacadla** [comment]
Thank you.

**Comment by cestcela** [comment]
Same problem with Windows10 and 11...
