### ISSUE TITLE
BSOD in Windows 10/11 installation start

### ISSUE THREAD

**Issue by matteorizzello** [quickemu-project/quickemu#275]
#### Expected behaviour

I start the VM and install Windows

#### Actual behaviour

The VM starts with Numlock flickering on and off every frame, I press the Numlock key until it stops flickering and go into the Windows installation ISO, which immediately returns a BSOD (Both in Windows 10 and 11)
![errorevm](https://user-images.githubusercontent.com/54456022/145698387-7593e82d-7f88-48b7-8f38-f6ed951bd2ad.png)

#### Steps to reproduce the behaviour

Download Windows 10/11 Italian through Quickgui and try to install it

#### Quickemu output

Quickemu 2.3.3 using /usr/bin/qemu-system-x86_64 v6.1.0
 - Host:     "Manjaro Linux" running Linux 5.15 (matteoManjaro)
 - CPU:      AMD Ryzen 5 1600 Six-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/x64/OVMF_CODE.secboot.fd), SecureBoot (on).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_Italian_x64.iso
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Boot ISO: windows-11/Win11_Italian_x64.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930
 - TPM:      windows-11/windows-11.swtpm-sock (5091)
audio: Driver `spice' does not support 2147483647 playback voices, max 1
qxl_send_events: spice-server bug: guest stopped, ignoring
 - Process:  Starting windows-11.conf as windows-11 (5093)

#### Linux Distribution & Kernel

LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.0
Codename:       Qonos

Linux matteoManjaro 5.15.2-2-MANJARO #1 SMP PREEMPT Sat Nov 13 19:25:38 UTC 2021 x86_64 GNU/Linux

**Comment by matteorizzello** [comment]
Nevermind, I clearly can't read. How embarassing.
For everyone else that can't read:

```
echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

      If you are unable to run macOS or Windows VMs then run the above 👆
      This will enable ignoring of unhandled MSRs until you reboot the host.
      You can make this change permenant by running: 'quickemu --ignore-msrs-always'
```
     
This is the solution

**Comment by edclement** [comment]
> Nevermind, I clearly can't read. How embarassing. For everyone else that can't read:
> 
> ```
> echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
> 
>       If you are unable to run macOS or Windows VMs then run the above 👆
>       This will enable ignoring of unhandled MSRs until you reboot the host.
>       You can make this change permenant by running: 'quickemu --ignore-msrs-always'
> ```
> 
> This is the solution

This message never showed up for me but fixed my issue trying to run any version of Windows. THANK YOU SO MUCH!
