### ISSUE TITLE
more disks

### ISSUE THREAD

**Issue by L0cutus** [quickemu-project/quickemu#276]
#### Expected behaviour
how to add more disks to VM cfg?
Thanks !

**Comment by flexiondotorg** [comment]
Sorry, this issue tracker is for bug reports in the software not user support. Please join our Discord for assistance using Quickemu slightly_smiling_face

https://wimpysworld.io/discord

**Comment by Nebucatnetzer** [comment]
Discord is a bad place for these kind of things, makes it very hard to discover things.
Possible solution: https://github.com/quickemu-project/quickemu/issues/726#issuecomment-3796700453
