### ISSUE TITLE
macos-monterey stuck on Less than a minute...

### ISSUE THREAD

**Issue by molaeiali** [quickemu-project/quickemu#278]
#### Expected behaviour
Finish the installation

#### Actual behaviour
Never finish or restart the installation

#### Steps to reproduce the behaviour
Start installing MacOS Monterey?
I started the installation, Erased `Apple Inc. VirtIO Block Media` and started the installation, waited for about 6 hours over night, it didn't restated, was just stuck on 18 minutes remaining, I closed the VM manually and started it again, there was a MacOS installer option added, So I assume the installer was finished but didn't restart. then there is a black screen with apple logo, with a bar filling, and then it stuck on "Less than a minute..." for hours, I repeated the process 3 times, same issues each time.

BTW, I don't know I should report this here or to qemu or Apple? So sorry if it's not relevant.

#### Quickemu output
I ran it through quickqui, so, I don't have any, If there is I can provide <3.

#### Linux Distribution & Kernel

Run the following and paste the output.

```
~$ lsb_release --all
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
~$ uname -a
Linux T490 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux
```

**Comment by philclifford** [comment]
Hi @molaeiali,
quickemu must be in your $PATH for quickgui to work so you could provide the output by opening a terminal and typing e.g. `quickemu --version`
If you haven't got the latest version (3.11) then you may be experiencing the annoying habit of macOS of going to sleep before it has finished installing. This should be fixed in 3.11 so if you have an older version please try getting 3.11 or later from here (you may also find a newer release of quickgui [here](https://github.com/quickemu-project/quickgui) )
Then you'll probably need to delete the VM disk (`quickemu --vm macos-monterey.conf --delete-disk`)  and restart the installation afresh.  If you do that using quickemu in a terminal (following the details in the README.md) you may have more success. 
If you were using 3.11 or later please let us know.

**Comment by maj113** [comment]
hiya, i have the same issue, the macOS installer froze at 18min remaining so after a hour i decided to just reboot it, its now stuck on less than a minute remaining, im using 3.11

```Quickemu 3.11 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu Jammy Jellyfish (development branch) running Linux 5.15 (may113-ThinkBook-15-G2-ITL)
 - CPU:      11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-monterey/disk.qcow2 (96G)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Display:  SDL, VGA, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-monterey" --port 5930
 - WebDAV:   On guest: build spice-webdavd (https://gitlab.gnome.org/GNOME/phodav/-/merge_requests/24)
 - WebDAV:   On guest: Finder -> Connect to Server -> http://localhost:9843/
 - 9P:       On guest: sudo mount_9p Public-may113
 - 9P:       On host:  chmod 777 /home/may113/Public
             Required for macOS integration 👆
 - Process:  Starting macos-monterey.conf as macos-monterey (8532)
 ```
 ill retry the install and report back if it worked

**Comment by kaaloo** [comment]
Unfortunately I'm systematically hitting the same issue on 3.12.  This occurs after the first reboot where I choose macOS installer and it displays around 29 min remaining, then goes to less than a minute and is stuck there.  Are there any log files or other artifacts that could help understand what's going on? Thanks!

```
❯ quickemu --vm macos-monterey.conf --display gtk
Quickemu 3.12 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.10 running Linux 5.13 (shangrila)
 - CPU:      Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 24G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-monterey/disk.qcow2 (256G)
 - Display:  GTK, VGA, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-monterey" --port 5930
 - WebDAV:   On guest: build spice-webdavd (https://gitlab.gnome.org/GNOME/phodav/-/merge_requests/24)
 - WebDAV:   On guest: Finder -> Connect to Server -> http://localhost:9843/
 - 9P:       On guest: sudo mount_9p Public-luis
 - 9P:       On host:  chmod 777 /home/luis/Public
             Required for macOS integration 👆
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Process:  Starting macos-monterey.conf as macos-monterey (116768)
```

**Comment by kaaloo** [comment]
Ok sorry for the noise, it just took a *very* long time....  After more than an hour I see the following:

![image](https://user-images.githubusercontent.com/67010/155498399-5b3f3280-76c7-4098-a7fb-ef403791f06e.png)
