### ISSUE TITLE
Tracking PRs for updated Distro releases and ISO changes

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#283]
Expected:
22.04 jammy flavours

Recently accommodated:
- [x] #281
- [x] #290
- [x] #277
- [x] #282

**Comment by jontyms** [comment]
quickget might be able to use torrents or something?
Or automatically pull a list from github with the latest urls

**Comment by philclifford** [comment]
Torrents add more dependencies so unlikely to find favour.
Having a reliable external catalogue of isos  and versions has a lot going for it, not least the separation of version churn from the main code release cycle. However, it is harder than it looks because every distro has their own standard, and some change their standard on a whim between releases. Hence so many slight variations in the current code, the delight when you find a distro that makes it easy, the frustration when you find an API that returns an ISO that isn't built yet, and the certainty that while some serious refactoring is needed, the work will be ongoing.

**Comment by flexiondotorg** [comment]
I have put in some considerable effort to `quickget` to make it much easier to add new OSs and maintain the existing OSs.

**Comment by philclifford** [comment]
> I have put in some considerable effort
Utterly awesome and exemplary marathon refactoring! Thanks @flexiondotorg 🙏
