### ISSUE TITLE
Feature Request: Alpine Linux support to quickget

### ISSUE THREAD

**Issue by MaxPeal** [quickemu-project/quickemu#294]
It is needed for a low disk space linux install.

**Comment by the-mentor** [comment]
This seems like it can be quite easy. 
I might give it a try.

-DM

**Comment by Jai-JAP** [comment]
Done....     #298

**Comment by the-mentor** [comment]
@Jai-JAP  looks like we did a similar implementation 
https://github.com/quickemu-project/quickemu/pull/301

**Comment by flexiondotorg** [comment]
Closed via #298
