### ISSUE TITLE
macOS Monterey: permanent display resolution change

### ISSUE THREAD

**Issue by sekret1** [quickemu-project/quickemu#303]
#### Expected behaviour

In the guest Monterey I'm able to adjust the display resolution to my needs (1920x1080). I expect it to be applied again after a reboot.

#### Actual behaviour

But it gets reverted to the default 1024x768.

#### Steps to reproduce the behaviour

Install Monterey, log in, open "System Preferences", click on "Displays", click on "Show all resolutions", select e.g. 1920x1080. The WindowServer will crash, you'll have to log in again. The resolution will be set to 1920x1080 as expected.
Restart the system. The display will be reset to 1024x768.

Has this something to do with the file OVMF_VARS-1024x768.fd ? So is this intended?

#### Quickemu output

not really helpful I guess…
<pre>
$ quickemu --vm macos-monterey.conf
usb_desc_get_descriptor: 1 unknown type 33 (len 10)
usb_desc_get_descriptor: 2 unknown type 33 (len 10)
usb_desc_get_descriptor: 1 unknown type 33 (len 10)
usb_desc_get_descriptor: 1 unknown type 33 (len 10)
usb_desc_get_descriptor: 2 unknown type 33 (len 10)
usb_desc_get_descriptor: 1 unknown type 33 (len 10)
</pre>
<pre>
$ cat macos-monterey.log
BdsDxe: loading Boot0000 "UEFI QEMU HARDDISK QM00013 " from PciRoot(0x0)/Pci(0xA,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0000 "UEFI QEMU HARDDISK QM00013 " from PciRoot(0x0)/Pci(0xA,0x0)/Sata(0x0,0xFFFF,0x0)
#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========
BdsDxe: loading Boot0000 "UEFI QEMU HARDDISK QM00013 " from PciRoot(0x0)/Pci(0xA,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0000 "UEFI QEMU HARDDISK QM00013 " from PciRoot(0x0)/Pci(0xA,0x0)/Sata(0x0,0xFFFF,0x0)
#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========
</pre>
#### Linux Distribution & Kernel
<pre>
$ lsb_release --all
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
</pre>
<pre>
$ uname -a
Linux Archlinux 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
</pre>

edit:
I'm using quickemu version 3.11

**Comment by flexiondotorg** [comment]
I can not reproduce this problem. This issue tracker is for actual bug reports, not for "support" discussion. We do have a place to discuss the use of Quickemu and that is our Discord 🙂 

  * https://wimpysworld.io/discord
