### ISSUE TITLE
fallback to wget with no zsync doesn't work

### ISSUE THREAD

**Issue by giorgiga** [quickemu-project/quickemu#306]
I'm running quickget on fedora 35, with no zsync (not available in the repos - too lazy to install manually).

Apparently quickget should fallback to wget, but that doesn't work:

```
$ quickget kdeneon user
which: no zsync in ([my path])
INFO: zsync not found, falling back to wget
ERROR! Unable to create directory 
```

**Comment by daPhipz** [comment]
Do you have `wget` installed?

**Comment by giorgiga** [comment]
`wget` is installed: in fact I have no problems running `quickget` for alma and fedora.

Now that I think of it... I kinda assumed those distros were not using `zsync` for whatever reason, but.. maybe `zsync` is used for all distros and the problem is specific to kdeneon?

**Comment by giorgiga** [comment]
Looking at the code, the issue might be at like 493, where the call to `web_get` has only one parameter compared to two in the other places it's called.

https://github.com/quickemu-project/quickemu/blob/12fbf6b02f43dfa42be33f8da72bbdab50ac7667/quickget#L493
