### ISSUE TITLE
add Braille terminal support

### ISSUE THREAD

**Issue by alex19EP** [quickemu-project/quickemu#307]
hello it will help me a lot if quickemu can add Braille display

references: 
* https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/scripts/run_archiso.sh#L82
* https://lists.nongnu.org/archive/html/qemu-devel/2008-04/msg00052.html
* search braille in qemu manual

**Comment by philclifford** [comment]
Hi Alexander, thanks for the suggestion. That looks to me to be a simple matter of nicking the relevant bit from the first reference and adding a quickemu option like 
`--accessibility braille` and/or `--acc brl`

I'll have a go at that if nobody has beaten me to it, but cannot test so if a PR appears...
Or am I missing something ?

**Comment by alex19EP** [comment]
> Hi Alexander, thanks for the suggestion. That looks to me to be a simple matter of nicking the relevant bit from the first reference 

yes.

> but cannot test

I will happily test this.

> Or am I missing something ?

I think no.

**Comment by philclifford** [comment]
Thanks Alexander.  Please try the `quickemu` in my linked PR #310 and let us know how you get on.
