### ISSUE TITLE
Force VM Shutdown

### ISSUE THREAD

**Issue by kd2flz** [quickemu-project/quickemu#311]
#### Expected behaviour

There should be an obvious option to "hard shutdown" a vm from the cli

#### Actual behaviour

Currently, the only ways I am aware of to shutdown a VM is either to do it from inside the machine, or to use quickgui (which has a handy stop button). 

#### Steps to reproduce the behaviour

Start a vm. Type '''quickemu --help'''. No obvious option for shutdown is exposed.

#### Quickemu output
```
Usage
 quickemu --vm ubuntu.conf

You can also pass optional parameters
  --delete-disk           : Delete the disk image and EFI variables
  --delete-vm             : Delete the entire VM and it's configuration
  --display               : Select display backend. 'sdl' (default), 'gtk', 'none', or 'spice'
  --fullscreen            : Starts VM in full screen mode (Ctl+Alt+f to exit)
  --ignore-msrs-always    : Configure KVM to always ignore unhandled machine-specific registers
  --screen <screen>       : Use specified screen to determine the window size.
  --shortcut              : Create a desktop shortcut
  --snapshot apply <tag>  : Apply/restore a snapshot.
  --snapshot create <tag> : Create a snapshot.
  --snapshot delete <tag> : Delete a snapshot.
  --snapshot info         : Show disk/snapshot info.
  --status-quo            : Do not commit any changes to disk/snapshot.
  --version               : Print version 
```

#### Linux Distribution & Kernel

```No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish
Linux L27838 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by daPhipz** [comment]
You can kill a VM by executing `kill VMPID`, where `VMPID` is the PID of the VM process. You can get it from the messages when starting the VM - it is mentioned in the last line ("Process").

**Comment by flexiondotorg** [comment]
Quickemu tells you the PID of the VM when you start it.

```
 - Process:  Starting alpine-3.15.conf as alpine-3.15 (594991)
```

As @daPhipz explain, you can simple kill the process. If the VM is running via SDL, you can simply close the window to shutdown the VM and Quickgui has an option to stop a running VM.
