### ISSUE TITLE
Monterey "the disk is locked"

### ISSUE THREAD

**Issue by buzzmandt** [quickemu-project/quickemu#315]
#### Expected behaviour

To click the install folder and it be ok to install to, but it's locked

#### Actual behaviour

When monterey is asking to select the disk where you want to install macOS, there's a folder 2.87 G total, 1.08 available. When I click this folder it says "This disk is locked"

#### Steps to reproduce the behaviour

quickget macos monterey
quickemu --vm macos-monterey.conf

#### Quickemu output

buzz-manjaro% quickemu --vm macos-monterey.conf
Quickemu 3.11 using /usr/bin/qemu-system-x86_64 v6.2.0
 - Host:     "Manjaro Linux" running Linux 5.15 (buzz-manjaro)
 - CPU:      AMD FX(tm)-8350 Eight-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-monterey/disk.qcow2 (96G)
             Looks unused, booting from macos-monterey/RecoveryImage.img
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Recovery: macos-monterey/RecoveryImage.img
 - Display:  SDL, VGA, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-monterey" --port 5930
 - WebDAV:   On guest: build spice-webdavd (https://gitlab.gnome.org/GNOME/phodav/-/merge_requests/24)
 - WebDAV:   On guest: Finder -> Connect to Server -> http://localhost:9843/
 - 9P:       On guest: sudo mount_9p Public-buzz
 - 9P:       On host:  chmod 777 /home/buzz/Public
             Required for macOS integration 👆
 - smbd:     On guest: smb://10.0.2.4/qemu
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.bmi2 [bit 8]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.0DH:EAX.xsaveopt [bit 0]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.bmi2 [bit 8]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.0DH:EAX.xsaveopt [bit 0]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.bmi2 [bit 8]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.0DH:EAX.xsaveopt [bit 0]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.bmi2 [bit 8]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.0DH:EAX.xsaveopt [bit 0]
 - Process:  Starting macos-monterey.conf as macos-monterey (214275)

#### Linux Distribution & Kernel
Manjaro-KDE
Kernel 5.15.12.1-MANJARO

**Comment by buzzmandt** [comment]
This also happens with catalina and big-sur.
tells me something is wrong on my end.
I'll admit that I don't have macrecovery installed. I don't know how and it's not in the repos or aur. 
is that the issue maybe?

**Comment by rany2** [comment]
This is how I managed to fix the "the disk is locked" issue:

1. Select "Disk Utility" 
![](https://user-images.githubusercontent.com/71077389/149206659-47a449db-87b8-4cc4-9a5d-cdd877183b29.png)
2. After Pressing "Continue", you will have a list of available hard disk devices
3. Select "Apple Inc. VirtIO Block Media"
![](https://user-images.githubusercontent.com/71077389/149206854-98e00b2c-2df9-4ede-bc89-d1f1cd8ca6e3.png)
4. Pick "Erase"
5. At the Erase prompt, make sure you select one of the "Mac OS Extended" options, here I picked case-sensitive 
![](https://user-images.githubusercontent.com/71077389/149206981-7084c860-ac2a-4079-bc0c-94240846cc2b.png)
6. When the Erase operation is complete, leave the disk utility by Win+Q so you could go back to the main menu and pick "Install Mac OS"

Now redo the install process and you will have an option to install onto your newly formatted hard drive:

![](https://user-images.githubusercontent.com/71077389/149208052-c273314e-af64-441a-9bba-3b699d37a112.png)

**Comment by buzzmandt** [comment]
Yep, that was it. Just didn't know what to do next. Thank you very much

**Comment by deathblade287** [comment]
thank you. this helped me still, more than 2 years later. couldn't find the solution anywhere else.

**Comment by lmr97** [comment]
Note to future visitors here, this also worked for my Sequoia install (it started up from a Sonoma VM)!
