### ISSUE TITLE
Opensuse LEAP download fails.

### ISSUE THREAD

**Issue by schmidthausen** [quickemu-project/quickemu#316]
#### Expected behaviour

The iso should download.

#### Actual behaviour

the download fails

#### Steps to reproduce the behaviour

```bash
quickget opensuse 15.3
```

#### Quickemu output

```bash
ERROR! Failed to download https://download.opensuse.org/distribution/leap/15.3/iso/openSUSE-Leap-15.3-DVD-x86_64.iso. Try running 'quickget' again.
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 35 (Thirty Five)
Release:        35
Codename:       ThirtyFive

Linux 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by flexiondotorg** [comment]
Fixed via #317
