### ISSUE TITLE
Make this run the native architecture binary

### ISSUE THREAD

**Issue by TikoTikTok** [quickemu-project/quickemu#329]
```
# TODO: Make this run the native architecture binary
```

https://github.com/TikoTikTok/quickemu/blob/0ae083c8237a62f2658906e4ffb1eac54a577aa5/quickemu#L1161

>> * https://github.com/quickemu-project/quickemu/pull/327

**Comment by flexiondotorg** [comment]
I do not understand what issue or pull request are seeking to address. Closing for now as branches have diverged considerably.
