### ISSUE TITLE
quickget cannot retrieve debian isos

### ISSUE THREAD

**Issue by victordiaz** [quickemu-project/quickemu#330]
#### Expected behaviour
`quickget` should retrieve Debian isos

#### Actual behaviour
Apparently quickget is pointing to a folder rather than the iso file

```
❯ quickget debian 11.1.0-amd64-gnome
SSL_INIT
debian-11.1.0-amd64-gnome-standard/: Is a directory
ERROR! Failed to download https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/. Try running 'quickget' again.
```

**Comment by Aifolin** [comment]
./quickget debian xfce

**Comment by victordiaz** [comment]
@Aifolin that works, thanks

Nevertheless, when doing 
```quickget debian```

the output is

```
ERROR! You must specify a release: 11.1.0-amd64-cinnamon 11.1.0-amd64-gnome 11.1.0-amd64-kde 11.1.0-amd64-lxde 11.1.0-amd64-lxqt 11.1.0-amd64-mate 11.1.0-amd64-standard 11.1.0-amd64-xfce
```

which is quite misleading

**Comment by philclifford** [comment]
Debian release of 11.2 disclosed a bug which has been fixed in some pending PRs. As @Aifolin noted if you just supply the wanted DE the current version works.
