### ISSUE TITLE
smb help, and network

### ISSUE THREAD

**Issue by ismaelct** [quickemu-project/quickemu#331]
hello i'm noobie with this kinda software im familiarized with virtualbox, i would like to reach to my windows 10 vm through my host and i tried to instal smbd, doing the bridge thing and nothing.

I would like yo know just wich ip is the one for my guest from my host and vice versa, and how to connect samba

**Comment by flexiondotorg** [comment]
Sorry, this issue tracker is for bug reports in the software not user support. Please join our Discord for assistance using Quickemu 🙂 

  * https://wimpysworld.io/discord
