### ISSUE TITLE
Failing to install Windows 10

### ISSUE THREAD

**Issue by rsuhada** [quickemu-project/quickemu#336]
#### Expected behaviour

I'm trying to install Windows 10.

#### Actual behaviour

Installation doesn't even start - returing "Failed to start boot...."
![image](https://user-images.githubusercontent.com/818539/151852348-1915392f-4c2b-4695-af97-8780b5f25c16.png)

#### Steps to reproduce the behaviour
    quickget windows 10
    quickemu --vm windows-10.conf

The .conf file is the default one, I haven't done any edits.

#### Quickemu output

Quickemu and Quickget are v.  3.11

#### Linux Distribution & Kernel

```bash
lsb_release --all

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal


uname -a
Linux xxxxx 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hcjl** [comment]
Try `echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs` before starting the vm.

**Comment by rsuhada** [comment]
Thanks, but I did have this setting and still the same issue.

To be more precise, the content of the file is "Y" (automatically changes from "1"), which I think should be equivalent: 

```
~/vm> echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
1

~/vm> cat /sys/module/kvm/parameters/ignore_msrs              
Y
```

**Comment by Nathan22211** [comment]
I"m getting something similar, but with win11

**Comment by flexiondotorg** [comment]
I can not reproduce this problem. This issue tracker is for actual bug reports, not for "support" discussion. We do have a place to discuss the use of Quickemu and that is our Discord 🙂 

  * https://wimpysworld.io/discord

**Comment by kaaloo** [comment]
Ok I got around this by hitting a key before the messages first reported here are displayed and it takes me to the windows setup screen.

**Comment by tom-james-watson** [comment]
> Ok I got around this by hitting a key before the messages first reported here are displayed and it takes me to the windows setup screen.

I can confirm that this workaround worked for me too
