### ISSUE TITLE
No audio can be when booting macOS Catalina recovery image using GTK interface

### ISSUE THREAD

**Issue by mhussaincov93** [quickemu-project/quickemu#337]
#### Expected behaviour
I should be able to hear audio output from the macos catalina
vm, but hear nuthing.
i'm using the gtk interface.
because the gtk interface audio worked with windows 10.
now, i'm not at all experienced with mac, but i thought that command plus f5 would launch screen reader?
command key being the windows key?
i'm pritty sure that it has booted, because on the host ram usage has gone up.
I would be greatful for your help.

#### Actual behaviour
no audio is herd at all from the recovery image

#### Steps to reproduce the behaviour
create a macos catalina vm using quickget and launch with
quickemu --vm marcos-catalina.conf --display gtk
when it's booted, try to launch the screen reader.
i've done the qemu module tweak 
the ecoh 1 tweak.

#### Quickemu output
none, it says it's booting normaly

#### Linux Distribution & Kernel
archlinux
linux-5.16.2.arch1

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
thanks,
Majid

**Comment by flexiondotorg** [comment]
Please try with the default SDL interface.

**Comment by nqvrg** [comment]
I have the same issue with both the SDL and the GTK interface. No audio on **any** macos version.

Distro: Debian 11 Buster
Kernel: 5.15.0-0.bpo.3-amd64
QEMU version: 6.2.0 (Debian 1:6.2+dfsg-2~bpo11+1)
