### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by GinoMalatesta** [quickemu-project/quickemu#338]
Hi, I just installed Mojave on Ubuntu 21.10-i5 10th gen, stock Lenovo machine, with Intel graphics . It went all nicely and it's booting.
But the screen size isn't adjusted well. I have a 1920x1080 screen attached. The screen is recognized as a 33.5" iMacPro screen, with 1920x1440. The upper part  of the desktop is missing, the menu only becomes visible, after I resize the window. Launching it with --screen 0 has no effect. 

Even more strange is, that the area tracked by the mouse seems to be fixed to 1024x768. I can only reach the dock, when I set the screen resolution to 1024x768, otherwise the tracking area ends at 768px from the top of the screen and 1024px from the left.
Would be grateful for any suggestions.

**Comment by flexiondotorg** [comment]
Sadly, Mojave screen resolution can not be changed when running via QEMU.
