### ISSUE TITLE
Move quickemu folders out of home

### ISSUE THREAD

**Issue by bshor** [quickemu-project/quickemu#341]
Quickemu works just fine on my Garuda Linux system. But it places all the VMs it creates in my home folder, which I don't want to use. Can I move the VMs elsewhere? When I tried to do so manually Quickgui couldn't find them anymore.

**Comment by philclifford** [comment]
Quickget / quickemu : cd to where you moved the config file too (parent of VM)
Quickgui: use the directory chooser to point it to the desired directory.
