### ISSUE TITLE
Allow connecting to the QEMU monitor

### ISSUE THREAD

**Issue by alexdelorenzo** [quickemu-project/quickemu#347]
#### Expected behaviour
Since guests run on QEMU, you should be able to access [QEMU's monitor](https://qemu-project.gitlab.io/qemu/system/monitor.html).

#### Actual behaviour

Guest VMs launched with `quickemu` are launched with [`-monitor none -serial mon:stdio`](https://github.com/quickemu-project/quickemu/blob/12fbf6b02f43dfa42be33f8da72bbdab50ac7667/quickemu#L868) in a [background process](https://github.com/quickemu-project/quickemu/blob/12fbf6b02f43dfa42be33f8da72bbdab50ac7667/quickemu#L961). Using `-serial mon:stdio` attaches the monitor to standard input and output.

Given that the VM is a background process, its `stdin` and `stdout` are not attached to the console, and the monitor is inaccessible.

#### Steps to reproduce the behaviour

```bash
$ quickemu --display spice --vm windows-11.conf
```

#### Quickemu output
```bash
$ quickemu --display spice --vm windows-11.conf
Quickemu 3.11 using /usr/bin/qemu-system-x86_64 v6.2.0
 - Host:     "Manjaro Linux" running Linux 5.16 (desktop)
 - CPU:      AMD Ryzen 5 5600G with Radeon Graphics
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/x64/OVMF_CODE.secboot.fd), SecureBoot (on).
 - Disk:     disk.qcow2 (64G)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - CD-ROM:   virtio-win.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir ~/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - TPM:      ./windows-11.swtpm-sock (331374)
audio: Driver `spice' does not support 2147483647 playback voices, max 1
qxl_send_events: spice-server bug: guest stopped, ignoring
 - Process:  Starting windows-11.conf as windows-11 (331398)
$
```

#### Linux Distribution & Kernel
```bash
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.3
Codename:       Qonos
Linux desktop 5.16.7-1-MANJARO #1 SMP PREEMPT Sun Feb 6 12:22:29 UTC 2022 x86_64 GNU/Linux
```

#### Comment
QEMU's monitor doesn't need to be attached to standard streams. It can use a socket or telnet, too.

Monitor access would enable features like this: https://github.com/quickemu-project/quickemu/issues/291

**Comment by flexiondotorg** [comment]
Fixed via #426
