### ISSUE TITLE
Enhancement  quickemu should work with xen!

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#359]
Xen is a type-1 hypervisor and for security ppl better choice. 

Your idea with quickly adding VMS is nice !!!
 You should follow this path and adding as addition xen hypervisor Dom0 automaticaly  install for archlinux and debian distros.

You project is hot!!!

Benefit of xen,  you can seperate everything in VM - even PCI adapters, network cards and so on.

Kvm typ2 hypervisor build on kernel functions ontop of linux directly, you cant seperate network drivers 
Because kvm needs driver access on kernelside - you cant seperate drivers for each kvm  and host machine forcing you drivers loaded.

You can run with xen nicvm or networkvm or firewallvm and your control distro (Dom0) haven't internet access. 

I hope you can understand my example. 

Maybe you can read more about xen  and
Watching Videos:
https://m.youtube.com/watch?v=qsSuYdUTkHQ

https://m.youtube.com/watch?v=4oc78WnBGps

Thanks and 
Best regards

**Comment by flexiondotorg** [comment]
Interesting idea, but sadly out of scope for this project :slightly_smiling_face:
