### ISSUE TITLE
quickget kdeneon result unexpected

### ISSUE THREAD

**Issue by leleliu008** [quickemu-project/quickemu#372]
#### Expected behaviour

should output support release of `kdeneon`

#### Actual behaviour

ERROR! You must specify a release: kdeneon is unknown
alma android archlinux debian elementary freebsd fedora garuda kali kdeneon kubuntu linuxmint-cinnamon linuxmint-mate linuxmint-xfce nixos-gnome nixos-plasma5 nixos-minimal lubuntu macos openbsd opensuse oraclelinux popos regolith rockylinux solus ubuntu ubuntu-budgie ubuntu-kylin ubuntu-mate ubuntu-studio windows xubuntu zorin

#### Steps to reproduce the behaviour

```
sudo apt-add-repository ppa:flexiondotorg/quickemu
sudo apt update
sudo apt install quickemu

quickget kdeneon
```

#### quickget output

ERROR! You must specify a release: kdeneon is unknown
alma android archlinux debian elementary freebsd fedora garuda kali kdeneon kubuntu linuxmint-cinnamon linuxmint-mate linuxmint-xfce nixos-gnome nixos-plasma5 nixos-minimal lubuntu macos openbsd opensuse oraclelinux popos regolith rockylinux solus ubuntu ubuntu-budgie ubuntu-kylin ubuntu-mate ubuntu-studio windows xubuntu zorin

#### lsb_release --all
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

#### uname -a
```
Linux ubuntu 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

![Screenshot from 2022-02-21 21-06-33](https://user-images.githubusercontent.com/3040852/154962775-94ee7dd8-2f7f-4934-a2a6-595bac74f1ec.png)

**Comment by daPhipz** [comment]
You need to specify a release as well - either `user`, `testing`, `unstable` or `developer`.

```
quickget kdeneon user
```
for example.

However, I do think that the wrong error message is shown when executing `quickget kdeneon` like you did - instead of listing the available OSes, it should point to `user`, `testing`, `unstable` or `developer`. So this is a valid bug after all ;P

Thanks for reporting it!

**Comment by leleliu008** [comment]
do you accept PR?

```diff
diff --git a/quickget b/quickget
index 38f9cf7..0d55e5d 100755
--- a/quickget
+++ b/quickget
@@ -2076,6 +2076,8 @@ else
         releases_windows
     elif [ "${OS}" == "zorin" ]; then
         releases_zorin
+    elif [ "${OS}" == "kdeneon" ]; then
+        releases_kdeneon
     else
         echo "${OS} is unknown"
         os_support
```
