### ISSUE TITLE
macos-monterey can not be installed if I add some configs in macos-montery.conf

### ISSUE THREAD

**Issue by leleliu008** [quickemu-project/quickemu#375]
#### Expected behaviour

can be installed successfully

#### Actual behaviour

stopped at this picture, cannot continue :

![quickemu-macos-montery-2](https://user-images.githubusercontent.com/3040852/155125555-17102ff3-4248-4de7-80c8-ec8455a75c8d.png)

#### Steps to reproduce the behaviour

```
sudo apt-add-repository ppa:flexiondotorg/quickemu
sudo apt update
sudo apt install quickemu

quickget macos montery

echo >> macos-montery.conf <<EOF
cpu_cores="8"
ram="8G"
EOF

quickemu --vm macos-monterey.conf
```

#### quickemu output

![quickemu-macos-montery-3](https://user-images.githubusercontent.com/3040852/155125145-76d35421-7fa9-4896-86a7-04ac1d2fec1a.png)

#### macos-monterey.conf
![quickemu-macos-montery-1](https://user-images.githubusercontent.com/3040852/155126141-7e96cc7b-990c-4063-82df-ed025e832b9b.png)

#### lsb_release --all
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

#### uname -a
```
Linux ubuntu 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nqvrg** [comment]
I have done a very similar change to yours, and I was able to install it and works perfectly (expect the known issue with the audio).

I added:

```
cpu_cores="4"
ram="16G"
disk_size="128G"
```

Before changing the configuration, I recommend you to empty the `macos-monterey` directory and run `quickget` again. Then make your changes and launch the VM.

Also, you might have to enable the "ignore unhandled MSRs" KVM parameter, running (if you need this, you should get a warning on the terminal when running the VM):

```
echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
```

**Comment by leleliu008** [comment]
@nqvrg Thanks for your comment.

**Comment by nqvrg** [comment]
I hope it helps! Let me know! 🙂

**Comment by leleliu008** [comment]
@nqvrg your config do not works for me. If I do not add any other configs, it works, but too slow when installing, after installing, I add my configs, it works.

**Comment by leleliu008** [comment]
Ubuntu-22.04
quickemu-3.15

```
guest_os="macos"
disk_img="macos-monterey/disk.qcow2"
img="macos-monterey/RecoveryImage.img"
macos_release="monterey"
cpu_cores="8"
ram="6G"
```

work for me now.
