### ISSUE TITLE
After changing disk_size, post-install, the disk is not resized.

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#384]
I did resize my disk like Example of quickemu inside VM.conf  file ,but,after restarting vm no resizing possible.

I did 
disk_size="44G" but after I did install my VM.
VM is bullseye netinstall.

Any solution? 

Thanks and

Best regards

**Comment by philclifford** [comment]
You need to change the disk_size before first running the VM so quickemu creates at that size.
You can use `qemu-img resize` to resize the image file but you'll likely need to extend partitions and filesystems into the space, which means booting the vm from a live iso. 
Alternatively use the `--delete-disk` parameter to remove the old one and re-run, which will create the new disk with the size in the config.

**Comment by osevan** [comment]
> You need to change the disk_size before first running the VM so quickemu creates at that size. You can use `qemu-img resize` to resize the image file but you'll likely need to extend partitions and filesystems into the space, which means booting the vm from a live iso. Alternatively use the `--delete-disk` parameter to remove the old one and re-run, which will create the new disk with the size in the config.

Thanks.

**Comment by suuuehgi** [comment]
For anyone else stumbling upon this, we can also fix it afterwards:

This grows the DISK
```
> qemu-img resize disk.qcow2 44G
```

To grow the partition, boot into live iso. Example for Arch:

Mount image:
`archlinux-latest.conf`
```
fixed_iso="/path/to/archlinux-latest.iso"
```

Fix GPT
```
> parted -l
```

Identify partition number (e.g.  `/dev/vda2` --> 2)
```
> fdisk -l
```

Grow PARTITION e.g.  `/dev/vda2`
```
pacman -Sy cloud-guest-utils
growpart /dev/vda 2
```

Grow FILE-SYSTEM
```
e2fsck -fv /dev/vda2
resize2fs /dev/vda2
```
