### ISSUE TITLE
Quickget downloads utilizing zsync fail

### ISSUE THREAD

**Issue by monetaryabyss** [quickemu-project/quickemu#395]
#### Expected behaviour

`quickget` should download the desired distribution.

#### Actual behaviour

`zsync` cannot download utilizing [https links](https://bugs.launchpad.net/ubuntu/+source/zsync/+bug/1927807) so the download fails.

#### Steps to reproduce the behaviour

Use `quickget` to download Ubuntu or any flavor.
Download fails.

#### Quickemu output

```
quickget lubuntu daily-live
ERROR! Failed to download https://cdimage.ubuntu.com/lubuntu/daily-live/current/jammy-desktop-amd64.iso.zsync
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

uname -a
Linux unx60113 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
It appears [this commit](https://github.com/quickemu-project/quickemu/commit/38b086244d591ab803f531ced409ccb87d63bfb2) introduced the regression.

**Comment by philclifford** [comment]
@monetaryabyss Thank you!
