### ISSUE TITLE
Garuda has 3 release+editions with broken targets

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#399]
Thanks to @takov751 we can see that these 404 errors need attention:
```text
garuda 220131 kde-barebones 404	text/html http://mirrors.fossho.st/garuda/iso/garuda/kde-barebones/220131/garuda-kde-barebones-linux-zen-220131.iso
garuda 220131 wayfire 404	text/html http://mirrors.fossho.st/garuda/iso/garuda/wayfire/220131/garuda-wayfire-linux-zen-220131.iso
garuda 220131 xfce 404	text/html http://mirrors.fossho.st/garuda/iso/garuda/xfce/220131/garuda-xfce-linux-zen-220131.iso

```
Their site now links to 
- https://mirrors.fossho.st/garuda/iso/garuda/xfce/220131/garuda-xfce-linux-lts-220131.iso
- ~~http://mirrors.fossho.st/garuda/iso/garuda/kde-barebones/220220/garuda-kde-barebones-linux-lts-220220.iso~~
- https://mirrors.fossho.st/garuda/iso/garuda/kde-barebones/220131/garuda-kde-barebones-linux-lts-220131.iso
- ~~http://mirrors.fossho.st/garuda/iso/garuda/wayfire/220116/garuda-wayfire-linux-zen-220116.iso~~

~~also there are 220213 and 220220 releases to consider offering for xfce and wayfire is stuck at 220116~~

Edit: between preparing this and later checking the links again while working on a patch for @takov751 they removed links to the 220220 files, and removed wayfire from their downloads.  This PR branch received an updated commit as soon as I found it, but just remembered to update this note.

~~slightly confusing that a week is a long time in arch (lts??)~~
a day is a long time in `arch` , btw

**Comment by philclifford** [comment]
Already tearing my hair out ( which is not sustainable ... see avatar ;-) ) remembering trying to write clever code  to deal with their "flexible" structure: each flavour seems to have its own release cadence, and you can't even "dynamically derive"  releases by parsing the "flavour"'s directory listing because some just have a pkg list (maybe while the iso is building) and a release on subsequent days suggest the first day probably shouldn't be in the list still.

**Comment by takov751** [comment]
Would be nice to have a current directory symlinked

**Comment by philclifford** [comment]
Having had a look round I remember I parsed their download page: the only links there are to 220131 except the kde-git, which I decided to skip since it looks too old to be a really maintained communtiy contrib at the moment. I have a little fix for the two that are fixable and wayfire seems to have been withdrawn.
