### ISSUE TITLE
gpu passthrough in quickemu needed

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#406]
How I can pass my GPU to VM Linux or Mac's in quickemu?

Which configs I need to edit? 

Thanks and

Best regards....

**Comment by flexiondotorg** [comment]
Duplicate of #113

**Comment by philclifford** [comment]
I think that was meant to say #133 
.. Also be assured some excellent work is underway to help simplify and facilitate this tricky task. You can follow along or help test if you're brave/confident - discussions and links are in the discord
