### ISSUE TITLE
Can't run quickemu vms on my ssd.(Tried with virt manager and vmware both work without problems)

### ISSUE THREAD

**Issue by if-loop69420** [quickemu-project/quickemu#410]
#### Expected behaviour

Starts an Alpine Linux VM(or any other operating system)

#### Actual behaviour
Throws:
'''
qemu-system-x86_64: -chardev socket,id=agent0,path=alpine-latest/alpine-latest-agent.sock,server=on,wait=off: Failed to bind socket to alpine-latest/alpine-latest-agent.sock: Operation not permitted
cat: alpine-latest/alpine-latest.pid: No such file or directory
 - Process:  Starting alpine-latest.conf as alpine-latest ()
'''

#### Steps to reproduce the behaviour

quickget alpine latest
quickemu --vm alpine-latest.conf

#### Quickemu output
Quickemu 3.13 using /usr/sbin/qemu-system-x86_64 v6.2.0
 - Host:     "Manjaro Linux" running Linux 5.10 (bonkbook)
 - CPU:      Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     alpine-latest/disk.qcow2 (16G)
             Looks unused, booting from alpine-latest/alpine-virt-3.15.0-x86_64.iso
 - Boot ISO: alpine-latest/alpine-virt-3.15.0-x86_64.iso
 - Display:  SDL, virtio-vga, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "alpine-latest" --port 5930 --spice-shared-dir /root/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-root ~/Public
 - smbd:     On guest: smb://10.0.2.4/qemu
qemu-system-x86_64: -chardev socket,id=agent0,path=alpine-latest/alpine-latest-agent.sock,server=on,wait=off: Failed to bind socket to alpine-latest/alpine-latest-agent.sock: Operation not permitted
cat: alpine-latest/alpine-latest.pid: No such file or directory
 - Process:  Starting alpine-latest.conf as alpine-latest ()

#### Linux Distribution & Kernel

Manjaro Linux 5.10

```bash
lsb_release --all

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.2.4
Codename:	Qonos

uname -a

Linux bonkbook 5.10.102-1-MANJARO #1 SMP PREEMPT Wed Feb 23 14:44:40 UTC 2022 x86_64 GNU/Linux
```

**Comment by if-loop69420** [comment]
Also tried it with sudo, but it still didnt work

**Comment by philclifford** [comment]
What filesystem is your SSD using?  You'd get that error on fat32 for example.

**Comment by if-loop69420** [comment]
Its exFat

**Comment by philclifford** [comment]
you could try and check directory mount-point permissions (needs execute - watch also for "noexec" mount/automount options  ) and if you have something else restricting access (acls, SE-linux, apparmour .... ).  However, I just assumed that it was a no-go when I hit the same error and moved my "portable" vms onto an ext4 usb ssd .  Given we're talking about COW sparse files of 16G or 32G or more with disk images and filesystems on them I wouldn't even try (again - it was an accident!) running a VM  "hosted" on FAT filesystem (and I'm still wary of ntfs under linux but that's probably an age/long memory problem).  

For further reading you might try [this](https://unix.stackexchange.com/questions/343814/kvm-cant-access-qcow2-images-storend-on-an-external-hdd) or [this](https://github.com/jedi4ever/veewee/issues/996) 

If I'm wrong and you find it can work fine on exfat then it would be good to know how.

**Comment by if-loop69420** [comment]
I dont have no noexec on there, but i Do have nodev. Its mounted with uid and gid Set to my User and usergroup. I dont know if thats the issue, but if i dont Set them i cant even nvim a file on the ssd bc then only root has the permissions.

**Comment by flexiondotorg** [comment]
This issue is due to mounting the ExFAT partition with the `nodev` option which prevents the Qemu socket from being created. This is not a bug in Quickemu, please modify your mount options accordingly 🙂

**Comment by bonnebulle** [comment]
Sorry, reopening
I try to start my VM from a ExFAT SSD
My ```/etc/fstab``` looks like :
```UUID=0361-02BD /media/Toshiba/ exfat users,exec,rw,suid,dev,atime,diratime,uid=1000,gid=1000,umask=000 0 0```
I keep have a socket error (permission denied) 
What can I do ?
Thanks

**Comment by zuize47** [comment]
I tried with this 
```shell
quickemu --vm ubuntu-server-23.10.conf --monitor none --serial none
```
and it run success @bonnebulle
