### ISSUE TITLE
OVMF paths on Solus

### ISSUE THREAD

**Issue by celtichawk** [quickemu-project/quickemu#412]
After Friday's update to Solus OS, qemu was upgraded and now refuses to work with quickemu citing missing EFI firmware, despite having the edk2-ovmf package installed from Solus's repos

Expected behavior: I run ./quickemu -vm <vm config> and qemu starts

Actual behavior: I run ./quickemu -vm <vm conf>.conf and qemu starts, then exits with a 'no efi firmware found' message, and tells me to install EFI firmware

Qemu version: 6.2.0, Release 47 (pulled from eopkg info qemu)

edk2-ovmf version: 202111 (from eopkg info edk2-ovmf)

I am not able on Solus to build my own ovmf firmware however

Is this merely a case of Solus installing things in different paths? For example, despite the package being installed, it does not install to /usr/share/ovmf

**Comment by philclifford** [comment]
Where is Solus putting the firmware now?  Currently `quickemu` is looking in the places below (so until we know where they've gone to in Solus you _could_ symlink them into one of these places as a possible interim fix)
```
grep OVMF_CODE quickemu |grep 'if \[ -e'| grep -v VM_DIR
    if [ -e "${VMDIR}/OVMF_CODE.fd" ] && [ -e "${VMDIR}/OVMF_VARS-1024x768.fd" ]; then
         if [ -e "/usr/share/OVMF/OVMF_CODE_4M.secboot.fd" ]; then
        elif [ -e "/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd" ]; then
        elif [ -e "/usr/share/OVMF/x64/OVMF_CODE.secboot.fd" ]; then
        elif [ -e "/usr/share/edk2-ovmf/OVMF_CODE.secboot.fd" ]; then
        if [ -e "/usr/share/OVMF/OVMF_CODE_4M.fd" ]; then
        elif [ -e "/usr/share/edk2/ovmf/OVMF_CODE.fd" ]; then
        elif [ -e "/usr/share/OVMF/OVMF_CODE.fd" ]; then
        elif [ -e "/usr/share/OVMF/x64/OVMF_CODE.fd" ]; then
        elif [ -e "/usr/share/edk2-ovmf/OVMF_CODE.fd" ]; then
```

**Comment by celtichawk** [comment]
There is something strange going on here. The files in the paths you provided are there, all except the main /usr/share/ovmf one, and I have no clue where Solus actually puts the files.


the files in /usr/share/edk2/x64 are there, I have the vars and .fd files, but not the main ovmf OVMF directory.

Assuming Solus puts it somewhere sane, would a simple ln ls fix it like you suggested?

**Comment by philclifford** [comment]
Hmm - you say  /usr/share/edk2/x64/  - that would explain them not being found as that combination is not quite a match for any in the list above. I would think creating one of the paths and `ln -s ` to link to the actual files should be a simple temporary fix .

If you could confirm where Solus has put them we could maybe add to the extensive hunt that quickemu already does.

To find where Solus put them there should be an option to the package manager ( maybe `eopkg info --files-path edk2-ovmf`).  and/or confirm your actual state using `find`.  For example (on ubuntu-mate) :
```
$ apt-file list ovmf
ovmf: /usr/share/OVMF/OVMF_CODE.fd        
ovmf: /usr/share/OVMF/OVMF_CODE.ms.fd
ovmf: /usr/share/OVMF/OVMF_CODE.secboot.fd
ovmf: /usr/share/OVMF/OVMF_CODE_4M.fd
ovmf: /usr/share/OVMF/OVMF_CODE_4M.ms.fd
ovmf: /usr/share/OVMF/OVMF_CODE_4M.secboot.fd
ovmf: /usr/share/OVMF/OVMF_CODE_4M.snakeoil.fd
ovmf: /usr/share/OVMF/OVMF_VARS.fd
ovmf: /usr/share/OVMF/OVMF_VARS.ms.fd
ovmf: /usr/share/OVMF/OVMF_VARS_4M.fd
ovmf: /usr/share/OVMF/OVMF_VARS_4M.ms.fd
ovmf: /usr/share/OVMF/OVMF_VARS_4M.snakeoil.fd
ovmf: /usr/share/doc/ovmf/README.Debian
ovmf: /usr/share/doc/ovmf/changelog.Debian.gz
ovmf: /usr/share/doc/ovmf/copyright
ovmf: /usr/share/ovmf/OVMF.fd
ovmf: /usr/share/ovmf/PkKek-1-snakeoil.key
ovmf: /usr/share/ovmf/PkKek-1-snakeoil.pem
ovmf: /usr/share/qemu/OVMF.fd
ovmf: /usr/share/qemu/firmware/40-edk2-x86_64-secure-enrolled.json
ovmf: /usr/share/qemu/firmware/50-edk2-x86_64-secure.json
ovmf: /usr/share/qemu/firmware/60-edk2-x86_64.json

$ find /usr/share/ -name "OVMF*" -a -type f 
/usr/share/ovmf/OVMF.fd
/usr/share/OVMF/OVMF_VARS_4M.ms.fd
/usr/share/OVMF/OVMF_CODE.fd
/usr/share/OVMF/OVMF_VARS.ms.fd
/usr/share/OVMF/OVMF_CODE_4M.secboot.fd
/usr/share/OVMF/OVMF_VARS_4M.snakeoil.fd
/usr/share/OVMF/OVMF_CODE.secboot.fd
/usr/share/OVMF/OVMF_VARS.fd
/usr/share/OVMF/OVMF_VARS_4M.fd
/usr/share/OVMF/OVMF_CODE_4M.fd

$ find /usr/share/ -name "OVMF*" -a -type l -ls|awk '{print $11 $12 $13}'
/usr/share/OVMF/OVMF_CODE.ms.fd->OVMF_CODE.secboot.fd
/usr/share/OVMF/OVMF_CODE_4M.snakeoil.fd->OVMF_CODE_4M.secboot.fd
/usr/share/OVMF/OVMF_CODE_4M.ms.fd->OVMF_CODE_4M.secboot.fd
/usr/share/qemu/OVMF.fd->../ovmf/OVMF.fd
```

**Comment by celtichawk** [comment]
Unfortunately, neither sinlinking to (that just results in the x64 folder and not the contents of said folder and no luck) or doing a sudo cp * /usr/share/ovmf works at all currntly

Solus doesn't show where a package is installed however, and even though it says the packages are installed, they don't get put into the typical places

**Comment by celtichawk** [comment]
Been poking at this and still no luck. It was working last wek and something changed in the updates Solus did, with no luck. Mostly since qemu updated.

Any ideas? I tried a simlink with no luck. I've tried doing simlinks to where it wants the files but no luck yet.

So the VM script looks for the files in the VM directory, then /usr/share/ovmf correct?

**Comment by clauded** [comment]
On my Solus installation, files are located in **/usr/share/edk2-ovmf/x64/**
```
~  git  quickemu  ls /usr/share/edk2-ovmf/x64/

MEMFD.fd  OVMF_CODE.fd  OVMF_CODE.secboot.fd  OVMF.fd  OVMF_VARS.fd
```

**Comment by philclifford** [comment]
Thanks @clauded  - an appropriate PR is now in the works with a possible fix.
