### ISSUE TITLE
(Enhancement) add a configuration file and command switches to change default VMs location.

### ISSUE THREAD

**Issue by amtoine** [quickemu-project/quickemu#415]
#### Expected behaviour

Having a configuration file for `quickemu`, e.g. `$HOME/.config/quickemu.conf` would be great to change the location of downloaded `.iso` files and `.conf` files. maybe a switch on the commands too?
So that it would be possible to run `quickget` from anywhere and have images put inside a common place.
And it would be possible to run `quickemu` from anywhere to launch and manage images from that common place.

#### Actual behaviour

There are no such configuration file, nor `quickemu` or `quickget` switches to indicate where VMs are located.

#### Steps to implement the enhancement

- add something like a `-c/--config` switch in both `quickemu` and `quickget`
- add the abitlity to read from a config file
- change the `.conf` files format to add the `$HOME` in front of the paths to transform them from relative paths to absolute ones.
- write a default config file
- change the help and doc

**I can open a pull request if you are interested in the feature!**

Really like the projet and it would be cool to contribute expanding it even more!
Cheers :wave:

**Comment by flexiondotorg** [comment]
There is no need for this feature :slightly_smiling_face: 

You can simply create a VM in any directory and launch that VM. VMs can be located anywhere you please, simple by being a directory making it your `pwd`

**Comment by amtoine** [comment]
> You can simply create a VM in any directory and launch that VM. VMs can be located anywhere you please, simple by being a directory making it your `pwd`
>
yes, asbolutely :yum: 

i was thinking more of a central place where all the config files and `.iso`s would go, such that the user does not have to worry about the path to the VMs or `cd`ing into the right directory :+1: 

i might have proposed to many new things in the original message, i did not want to change the project too much :confused:
