### ISSUE TITLE
Import the VM into virt-manager

### ISSUE THREAD

**Issue by nanonerd-io** [quickemu-project/quickemu#437]
Not really an "issue" but has anyone figured out an easy way to import the VM, along with the entire configuration, into virt-manager (which provides an easy GUI method of handling all the VMs)? I can import the qcow2 disk into a new virt-manager VM no problems. The problem that I'm running into is that it defaults to creating a SATA disk and controller upon import (even though the disk is defined as a virtio disk as created by quickemu. In other words, is there an easy way to import the VM shell file (.sh) into virt-manager OR another easy way of converting that .sh file into an XML file that can work with virt-manager. Such a feature would be awesome IMO

**Comment by flexiondotorg** [comment]
This is out of scope for the project, sorry.
