### ISSUE TITLE
macos Monterey only works/boots when cpu_cores="1"

### ISSUE THREAD

**Issue by nanonerd-io** [quickemu-project/quickemu#438]
#### Expected behaviour

To be able to set multiple cores/threads for CPU

#### Actual behaviour

Installation and subsequent bootups, the VM will only launch when cpu_cores is set to 1

#### Steps to reproduce the behaviour

Tried launching the VM to start installation which immediately halted/froze on the scrolling text screen. As soon as I set a parameter in the .conf file of cpu_cores="1" installation proceeded ahead. VM will only work with one CPU

**Comment by alexdelorenzo** [comment]
Also ran into this issue and left a comment on a duplicate issue here: https://github.com/quickemu-project/quickemu/issues/529#issuecomment-1214584347
