### ISSUE TITLE
Windows installer not booting on Ubuntu 21.10

### ISSUE THREAD

**Issue by marxjohnson** [quickemu-project/quickemu#439]
#### Expected behaviour

Starting a new windows 10 or 11 VM launches the Windows installer.

#### Actual behaviour

The installer does not boot, I am dropped to a UEFI shell.
![Screenshot from 2022-04-19 13-38-51](https://user-images.githubusercontent.com/235681/164006401-63c6132a-7c6a-43f3-b4ae-38f5c9847070.png)
![Screenshot from 2022-04-19 13-43-19](https://user-images.githubusercontent.com/235681/164006865-41bd1892-2a55-44d6-9988-9125dda8c40c.png)

#### Steps to reproduce the behaviour

`quickget windows 11`
`quickemu --vm windows-11.conf`

#### Quickemu output

```
Quickemu 3.14 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.10 running Linux 5.13 (markjohnson)
 - CPU:      11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_English_x64v1.iso
 - Boot ISO: windows-11/Win11_English_x64v1.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/markjohnson/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11.swtpm-sock (471689)
 - Process:  Starting windows-11.conf as windows-11 (471691)
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
$ uname -a
Linux markjohnson 5.13.0-39-generic #44-Ubuntu SMP Thu Mar 24 15:35:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stevem6** [comment]
iwilltry42 has a solution at [https://github.com/quickemu-project/quickemu/issues/86](https://github.com/quickemu-project/quickemu/issues/86). I found I had to type `#` to get `\` in `FS0:\EFI\BOOT\BOOTX64.EFI`

**Comment by marxjohnson** [comment]
Thanks, it looks like I was missing the "Press any key" prompt, and when I was hitting it, it's really slow to load on my machine so I thought I hadn't. I will close this issue.

**Comment by mirzaindra** [comment]
even after i type FS0:\EFI\BOOT\BOOTX64.EFI, it still doesnt work. is there other solution?
