### ISSUE TITLE
MacOS requires coreutils for sha256sum

### ISSUE THREAD

**Issue by ironicbadger** [quickemu-project/quickemu#446]
This entire issue is prefaced by acknowledging macos isn't a supported platform :)

#### Expected behaviour

Run `quickget ubuntu 20.04` and have the sha256sum verify.

```
quickemu % ./quickget ubuntu 20.04
ubuntu-20.04/ubuntu-20.04.4 100%[=========================================>]   3.15G  12.5MB/s    in 3m 22s
Checking ubuntu-20.04/ubuntu-20.04.4-desktop-amd64.iso with sha256sum... ./quickget: line 577: sha256sum: command not found
ERROR!
ubuntu-20.04/ubuntu-20.04.4-desktop-amd64.iso doesn't match f92f7dca5bb6690e1af0052687ead49376281c7b64fbe4179cc44025965b7d1c. Try running 'quickget' again.
```

#### Actual behaviour

`sha256sum` not found. Requires installing coreutils, for example with `brew install coreutils`.

#### Linux Distribution & Kernel

```
quickemu % lsb_release --all
uname -a
zsh: command not found: lsb_release
Darwin slartibartfast.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

**Comment by philclifford** [comment]
See: https://github.com/quickemu-project/quickemu#requirements right after `bash` . You might like to look at #248, where you'll find further efforts to enable macOS hosts and a selection of known issues to be addressed.
