### ISSUE TITLE
feat: add support for running quickemu on macOS hosts

### ISSUE THREAD

**Issue by ironicbadger** [quickemu-project/quickemu#447]
This entire issue is prefaced by acknowledging macos isn't a supported platform :)

#### Expected behaviour

Run `quickemu` and stand up Ubuntu.

#### Actual behaviour

```
./quickemu --vm ubuntu-20.04.conf
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
Quickemu 3.15 using /opt/homebrew/bin/qemu-system-x86_64 v6.2.0
 - Host:     Unknown OS running   ()
./quickemu: line 255: lscpu: command not found
./quickemu: line 256: lscpu: command not found
./quickemu: line 257: lscpu: command not found
 - CPU:
 - CPU VM:    Socket(s), 4 Core(s), 1 Thread(s)./quickemu: line 313: free: command not found
, 2G RAM
ERROR! EFI boot requested but no EFI firmware found.
       Please install OVMF firmware.
```

#### MacOS Distribution & Kernel

```bash
quickemu % lsb_release --all
uname -a
zsh: command not found: lsb_release
Darwin slartibartfast.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

**Comment by philclifford** [comment]
Also see #248 - and check out the work of @trollkarlen at the end.  If you look in their fork at https://github.com/trollkarlen/quickemu/commit/aab2330df1fdef0376ff21ebc4190c58a5fd04c4 they appear to have OVMF firmware ...

**Comment by flexiondotorg** [comment]
Getting there 😅

This is NixOS ❄️ running a virtual machine of macOS Ventura 🍏 via Quickemu, which is running a virtual machine of Alpine Linux 🐧 via Quickemu #linux #qemu

![NixOS-macOS-Alpine](https://github.com/quickemu-project/quickemu/assets/304639/c2718378-c5cf-4985-aab2-031f0b6cf0b6)
