### ISSUE TITLE
MacOS El Capitan

### ISSUE THREAD

**Issue by tunerooster** [quickemu-project/quickemu#451]
I am running an Intel Core 2 Duo (i.e., it does not have sse4.1 support).  All available version of MacOS apparently require sse4.1.

Would you consider adding "El Capitan" to the available MacOS versions?  I believe it is the last version which does not require sse4.1.

Thanks!

**Comment by tunerooster** [comment]
Anyone?

**Comment by flexiondotorg** [comment]
No, we are not going to be adding older releases of macOS. Sorry.
