### ISSUE TITLE
There should be Pre-installed VMs in qcow2 format

### ISSUE THREAD

**Issue by t3chie92** [quickemu-project/quickemu#469]
First I'd like to thank you for this awesome project.
Do you know what would be a great next step? To provide VMs that are already installed! (either by you or official images).
The big goal of the project is to have VMs ready and running in a fast manner, and providing .qcow2 files as an option will enhance the experience (especially GNU/Linux images) as they aren't vulnerable to hardware change errors, and especially that Internet speed is not an issue anymore for most. 

#### Expected behaviour

To have an option to download .qcow2 files of already installed Operating Systems in big sizes.

#### Actual behaviour

Only .iso files exist.

**Comment by flexiondotorg** [comment]
Sorry, this is out of scope for the project.
