### ISSUE TITLE
I can't log in to Apple ID account on Monterey

### ISSUE THREAD

**Issue by Emuzex** [quickemu-project/quickemu#474]
**Expected behaviour**

Log in to my Apple ID account.

**Actual behaviour**

All interfaces will be denied login

**Steps to reproduce the behaviour**

System Preferences -> Login -> Apple ID username and password entered correctly -> Error message

**Linux Distribution & Kernel**

Manjaro Linux
5.15.41-1-MANJARO kernel

```bash
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.6
Codename:       Qonos

Linux emuzex-arch 5.15.41-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022 x86_64 GNU/Linux
```

**Comment by sowinski** [comment]
Did you find a solution for this problem?

**Comment by Emuzex** [comment]
Unfortunatelly i didn't

**Comment by flexiondotorg** [comment]
This is not something Quickemu can fix or resolve. Sorry.

**Comment by donnykurnia** [comment]
If your apple id had 2FA turned on, you need to check your other apple device and confirm the login.

**Comment by flexiondotorg** [comment]
Duplicate of #1547
