### ISSUE TITLE
please add Debian netinst minimal Cd distribution support 

### ISSUE THREAD

**Issue by JanuszChmiel** [quickemu-project/quickemu#491]
#### Expected behaviour

Describe the your expected behaviour.

#### Actual behaviour

Describe the actual behaviour.

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
Dear elite programmers,
I Am visually impaired user with no sight at all. ANd I AM very nicely impressed by yours series of Bash scripts.
I like Quickemu very very much because it automatically setup legacy or UEFI firmware emulation according to The booted operating system.

Please would you be so kind and could you add support for Debian netinst miminimal image?
Because Debian support special boot option
s
which allow visually impaired users to install Debian with accessibility enabled including Speakup screen reader support and several GTK compatible desktop environments.
The direct up to date download link is here.
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.3.0-amd64-netinst.iso

Thank you very much for your time

**Comment by philclifford** [comment]
Hi @JanuszChmiel. Thanks for your kind words, and also for this request. The `netinst` image is already supported through the `Editions` parameter. To use the iso you mention simply use the following `quickget`command:

```
quickget debian 11.3.0 netinst
```
Hopefully that's all you need.  If not please let us know as accessibility is very important.  There is already a command line option  ( `quickemu --braille `) to enable `brltty` support. If there are other distributions or editions that would be of interest then please do add further issues (or even your own PR).

**Comment by JanuszChmiel** [comment]
Oh you are excellent Bash script developers. I really deeply appreciate your programmers work. I very appreciate automatic default UEFI firmware support so user do not have to specify this option. Scripts autodtect UEFI presence and virtual image can be used on UEFI compatible systems. In todays Linux years, it is still much faster and reliable to produce AN USB flash bootable media based on system installed to virtual image than remastering installed system and create live system, because SQUASHFS file system compression cause mother board temperature increase thanks to complex memory allocations and mathematic calculations. Is it possible to specify RAV image format of The created virtual disk image instead of Gconf2?
Raw image is ideal for tasks which envolves installing ANd distro, adding non supported packages on sspecific Linux distribution. As A visually impaired man I love various INternet radio players. SOme distros solve it by using Flatpak or similar non standard repository routines. But I like old approach based on building and compiling such apps myself.
