### ISSUE TITLE
how i can clone already working debian vm in quickemu?

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#496]
How i can do this?

Because i wont install new vm again. ..

Thanks and

Best regards

**Comment by flexiondotorg** [comment]
Please join our Discord for help using QUickemu.

  - https://wimpysworld.io/discord

**Comment by osevan** [comment]
Where i can find normal channel for my questions?

**Comment by osevan** [comment]
I can't write anything. 

Need i approve extra?
