### ISSUE TITLE
New quickemu release / support recent distro releases

### ISSUE THREAD

**Issue by paidhi** [quickemu-project/quickemu#498]
Quite a few Linux distributions had new releases recently.
Would it be possible to bump a new version for quickemu or at least merge some of the pull requests into the master/main branch to support the latest distro releases?

E.g.:
- PopOS 22.04
- Fedora 36
- Alma 9.0
- OpenSUSE Leap 15.4
- Mint 20.3
- Introduce CentOS Stream 8/9

**Comment by flexiondotorg** [comment]
These are all merged.
