### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by nicolasmol** [quickemu-project/quickemu#509]
Hi everyone
1) Is that possible to disbale the macOS startup manager sreen (the one into which we select the disk) ?
2) And/Or of this first question...Is that not possible to avoid booting by making and running like an "hibernate" image ?

**Comment by flexiondotorg** [comment]
For support and usage discussion, please join our Discord. This issue tracker is for bugs and feature requests only :slightly_smiling_face: 

 - https://wimpysworld.io/discord
