### ISSUE TITLE
Wrong download URL for Batocera 33

### ISSUE THREAD

**Issue by BackSpace54** [quickemu-project/quickemu#511]
Hi and first of all thanks for such this great VM tool :+1:

#### Expected behaviour
When choosing Batocera and version #33 the image file must be downloaded

#### Actual behaviour
The image is not downloaded

#### Steps to reproduce the behaviour
Install Quickemu 3.16 and QuickGui 1.2.4, try to download Batocera #33, got empty directory named 'Batocera-33' and no .img.gz file

#### Quickemu output

quickget batocera 33

07/30 22:11:14 [ERROR] CUID#7 - Download aborted. URI=https://updates.batocera.org/x86_64/stable/last/batocera-x86_64-33-20220203.img.gz
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://mirrors.o2switch.fr/batocera/x86_64/stable/last/batocera-x86_64-33-20220203.img.gz
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

#### Linux Distribution & Kernel

Run the following and paste the output.

No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

Linux <Machine name> 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

The problem seems to be the mismatch about latest Batocera version, it's not #33 but #34
If you refer to this page https://wiki.batocera.org/current_and_previous_releases the URL for latest version is https://mirrors.o2switch.fr/batocera/x86_64/stable/last/batocera-x86_64-34-20220523.img.gz
If i'm right Quickemu is trying to download  Batocera #33 with this URL formatting
local ISO="batocera-x86_64-${RELEASE}-20220203.img.gz"
local URL="https://updates.batocera.org/x86_64/stable/last"
so for Quickemu it's https://updates.batocera.org/x86_64/stable/last/batocera-x86_64-33-20220203.img.gz and this URL is no more valid.

To download older releases of Batocera you must use this URL https://mirrors.o2switch.fr/batocera/x86_64/stable/last/archives/${RELEASE}-<date of release>.img.gz so for #33 the correct URL is https://mirrors.o2switch.fr/batocera/x86_64/stable/last/archives/33/batocera-x86_64-33-20220203.img.gz (not https://mirrors.o2switch.fr/batocera/x86_64/stable/last/batocera-x86_64-33-20220203.img.gz)
With the archives directory you can add others older versions of Batocera if needed.

Could you check the problem and make it possible to download Batocera #34 and maybe the previous version for each major version (eg: version #34 + #33 and when the #35 version will be available add also #34 to the list, etc.)?

Tia.

**Comment by philclifford** [comment]
Thanks for the information, a fix is in the works.
