### ISSUE TITLE
When using quickget to download an image, I get an error if I don't enter the full distro name

### ISSUE THREAD

**Issue by jvesouza** [quickemu-project/quickemu#533]
When using quickget to download an image, if I type only the initials of the distro's name, I should get a message stating that the release was not informed.

Instead of receiving the message that the release was not informed, I receive an error message as shown in the example below.

./quickget u
ERROR! You must specify a release.
 - Releases: ./quickget: line 1966: releases_u: command not found

**Comment by flexiondotorg** [comment]
Please resubmit this issue using the issue template because the information we need to help is absent from this issue.
