### ISSUE TITLE
Windows 7 presents the best performance for VM, but isn't support for quickemu. Can you change that?

### ISSUE THREAD

**Issue by oldcastlehq** [quickemu-project/quickemu#554]
Hi,

Does anyone succeeded in having Windows 7 installed with quickemu? Can you have Windows 7 supported?

And from this study https://www.tandfonline.com/doi/full/10.1080/00051144.2020.1775961  Win 7 is the one that present the best performance.

**Comment by donnykurnia** [comment]
@oldcastlehq win7 can be easily created using virsh manager. No need to use special settings. Just add win7 iso, blank qcow2 disk, virtio-win-0.1.173.iso (last version still include win7 drivers), set the disk bus to virtIO, the boot away. No need to use special setting for it.
When installing win7, load the driver from virtio-win cd so the harddisk can be recognized and used by win7 installer.
