### ISSUE TITLE
macOS Catalina doesn't install correctly because QEMU HARDDISK Media isn't the correct size

### ISSUE THREAD

**Issue by thespyboss** [quickemu-project/quickemu#578]
#### Expected behaviour

Installation should proceed just like it is listed on the Wiki for installing macOS Catalina. 

#### Actual behaviour

The QEMU HARDDISK Media drive that is made, registers to small according to the macOS Catalina installer even after formatting it. 
![Screenshot_20221028_080731](https://user-images.githubusercontent.com/42257053/198583391-3c43ee9e-cc05-4e11-be39-82be9eb7793a.png)

#### Steps to reproduce the behaviour

Follow the steps on how to install macOS according to the wiki unless I have some edge case where the virtual drive that is being made is too small. 

#### Quickemu output

[cazd561@unknown-laptop ~]$ quickemu --vm macos-catalina.conf
Quickemu 4.3 using /usr/bin/qemu-system-x86_64 v7.1.0
 - Host:     "EndeavourOS Linux" running Linux 6.0 (unknown-laptop)
 - CPU:      Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-catalina/disk.qcow2 (96G)
             Looks unused, booting from macos-catalina/RecoveryImage.img
 - Recovery: macos-catalina/RecoveryImage.img
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - 9P:       On guest: sudo mount_9p Public-cazd561
 - 9P:       On host:  chmod 777 /home/cazd561/Public
             Required for macOS integration 👆 - Network:  User (vmxnet3)
 - Monitor:  On host:  nc -U "macos-catalina/macos-catalina-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-catalina/macos-catalina-monitor.socket
 - Serial:   On host:  nc -U "macos-catalina/macos-catalina-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-catalina/macos-catalina-serial.socket
audio: Unknown audio driver `pa'
audio: warning: Using timer based audio emulation
qxl_send_events: spice-server bug: guest stopped, ignoring
 - Process:  Starting macos-catalina.conf as macos-catalina (39934)

#### Linux Distribution & Kernel

Run the following and paste the output.

[cazd561@unknown-laptop ~]$ lsb_release --all
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling
[cazd561@unknown-laptop ~]$ uname -a
Linux unknown-laptop 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux

**Comment by thespyboss** [comment]
Just rebooted to try the 4.4 update and now macOS doesn't even boot, it just shows this. 

![Screenshot_20221028_081901](https://user-images.githubusercontent.com/42257053/198585357-1bd6a3e7-c7f6-4c24-bda2-25bad736f9a8.png)

**Comment by mahmoudelbadrywork** [comment]
@thespyboss for the UEFI screen, you'll need to delete the `OpenCore.qcow2` file from the mac folder and download it again using `quickget`

For the HARDDISK, what worked for me is adding the following line to the conf file
```
disk_size="128G"
```

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/commit/9a7ee718047aece5b7600307e33dcc88251a9921

**Comment by acendan** [comment]
Unfortunately, I'm still running into this issue. Followed all of the instructions on the README, but the volume is created at ~400Mb and modifying the conf file with `disk_size="128G"` per @mahmoudelbadrywork's suggestion hasn't worked for me. Any suggestions? Happy to provide more info if needed.

![image](https://user-images.githubusercontent.com/65690085/210319461-3b7fb08e-0002-4005-883b-f2bd7498cb55.png)

**Comment by OskarPersson** [comment]
I'm having the exact same problem. I'm running the latest master. @flexiondotorg

**Comment by thespyboss** [comment]
@flexiondotorg This isn't fixed it seems like.

**Comment by poetislands** [comment]
same problem

**Comment by woutgg** [comment]
I am also seeing this issue (Quickemu 4.5 on Arch). No matter which of the previously mentioned fixes I try, the disk always appears as the same small size even though qemu-img reports a correct size. I have tried with both Catalina and Monterey.

Seeing that I am not the only one, perhaps this issue should be reopened.

**Comment by jtbrough** [comment]
I ran into a similar issue with a fresh macOS Monterey VM today. It seems to present different disk name/sizes by default than what are captured in the readme.

quickemu version 4.6.

**Comment by erlerre** [comment]
@flexiondotorg this issue still persists. I have tried today. But struggle with the same wrongly recognized disk size as the guys before. Can you please have a look to it again. Thanks in advance

**Comment by erlerre** [comment]
I have changed line 551 in quickemu script
from: MAC_DISK_DEV="virtio-blk-pci"
back to: MAC_DISK_DEV="ide-hd,bus=ahci.2"
Now the installer aknowledge the right size of the disk and Mac Os is working.
I hope this info helps someone else.

**Comment by woutgg** [comment]
> I have changed line 551 in quickemu script from: MAC_DISK_DEV="virtio-blk-pci" back to: MAC_DISK_DEV="ide-hd,bus=ahci.2" Now the installer aknowledge the right size of the disk and Mac Os is working. I hope this info helps someone else.

This fixed it for me as well, very nice. Thank you!

**Comment by notsuretho** [comment]
Using "Apple Inc. VirtIO Bloc..." as the disk instead of "QEMU HARDDISK..." works just as well. That disk has ~103.08GB storage just like the doc mentioned.

**Comment by azuredusk10** [comment]
I also ran into this problem. I deleted the "macos-catalina" folder, started the installation process again, but chose the drive with about 103GB as @notsuretho did. The name didn't match the one in the installation guide, but MacOS installed just fine then.

**Comment by Cytomax55** [comment]
I had the same problem and im using 

"Using "Apple Inc. VirtIO Bloc..." as the disk instead of "QEMU HARDDISK..." works just as well. That disk has ~103.08GB storage just like the doc mentioned."

as my work around

**Comment by jackc12** [comment]
Go into disk utility before selecting reinstall Mac OS and delete the largest virtual drive. Watch this [video](https://youtu.be/wLezYl77Ll8?t=391). It's linked in the [Docker-OSX Readme](https://github.com/sickcodes/Docker-OSX#quick-start-docker-osx).
