### ISSUE TITLE
Feature request: LVM integration

### ISSUE THREAD

**Issue by omartijn** [quickemu-project/quickemu#582]
quickemu has been pretty useful to me so far, but I'm doing some fairly I/O-intensive stuff within the VMs I create with it. My idea for this is to get an external NVME drive, put on a small partition (which then has quickemu checked out on it), with the rest of the disk used for an LVM volume group.

Then, when you create a new VM, instead of creating a qcow2 image, it could create a logical volume and then use that instead.

I could probably hack that into the current scripts, but I think it'd be a nice feature to do properly. So I have a couple of questions.

1. Is this a feature that would have a chance of being merged if I wrote it
2. What would be a sensible way to implement it. Have a config file in the root directory that can contain the volume group to use (if choosing to use LVM)

**Comment by omartijn** [comment]
BTW: I tried to join the Wimpys World Discord, but immediately during sign-up they "detected something out of the ordinary" and then tried to harvest my phone number. Feels really fishy to me, not sure you'd want to associate with a number-harvesting operation.

**Comment by flexiondotorg** [comment]
Sorry, this is not a feature I intended to add support for. See #597
