### ISSUE TITLE
can't change macos guest screen resolution

### ISSUE THREAD

**Issue by blobfish** [quickemu-project/quickemu#592]
#### Expected behaviour

Being able to change screen resolution of macos big-sir

#### Actual behaviour

display preferences inside big-sir guest has only one choice of 1920x1080 which is way too small for laptop screen.

#### Steps to reproduce the behaviour

quickemu --display gtk --vm macos-big-sir.conf

#! --vm
guest_os="macos"
disk_img="macos-big-sur/disk.qcow2"
img="macos-big-sur/RecoveryImage.img"
macos_release="big-sur"
cpu_cores="2"
ram="8G"

#### Quickemu output

Not relevant.

#### Linux Distribution & Kernel

lsb_release --all && uname -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        n/a
Codename:       bookworm
Linux laptop 6.0.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.8-1 (2022-11-11) x86_64 GNU/Linux

**Comment by blobfish** [comment]
Just checked my catalina guest and it exhibits the same behavior.

**Comment by donnykurnia** [comment]
@blobfish it is macOS behaviour. To change the screen resolution, edit the OpenCore config.plist and rebuild OpenCore.qcow2 file. See the guide here:
https://github.com/kholia/OSX-KVM/blob/master/notes.md#change-resolution-in-opencore
https://github.com/kholia/OSX-KVM/blob/master/OpenCore/README.md

The usable resolutions is limited. Any resolutions available in OVMF config can be used. I tried to put resolution 1536x864 but the macOS fallback to 1280x800. So, just use any standard 16:9 resolution and you are good to go.

**Comment by blobfish** [comment]
Thanks for the help. I found a [solution](https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-screen-resolution.md#how-to-increase-screen-resolution-for-macos-simple-kvm) that doesn't involve me downloading yet another github repo. Now I can backup OpenCore.qcow2 and change the resolution from inside the virtual machine. If the screen is messed up I can just restore the original OpenCore.qcow2 file.

**Comment by donnykurnia** [comment]
Other approach is by mounting the `OpenCore.qcow2`, then edit the `config.plist` file inside it. Unmount, and then boot the macOS vm.
To mount the qcow2 file, one of the guide is here: https://gist.github.com/shamil/62935d9b456a6f9877b5
