### ISSUE TITLE
Feature request: Add Option to install the VM on a Physical driver or Unused Partition.

### ISSUE THREAD

**Issue by talesgomes27** [quickemu-project/quickemu#597]
#### Expected behaviour

I want to know if it's possible to install the VM on a separate SSD or on a different unused partition on my system? I have Two SSDs and want to dedicate the second only for my Windows VM. Is it possible to pass some extra argument to Quickget to install the VM on a dedicated SSD?

**Comment by philclifford** [comment]
`quickget` will create the `<vm>.conf` and the`<vm>` directory where it is run.  It is intended for quick and simple use using image files on a filesystem. If I understand what you wish correctly you might be able to achieve it using options in the `<vm>.conf` file with a little preparatory work.  You'd need to pass-thru the second SSD or make it available to the VM using the `quickemu` options available (and maybe the "--extra-options=" parameter to `quickemu`).  Unless you use a raw or qcow2 image file you'll lose some benefits of  `qemu` (e.g. snapshots ) and any that the underlying host filesystem could provide (e.g. the wonders of `zfs` for snapshots, clones, compression ...) and the simplicity of just formatting your second ssd and putting your windows vm on it.  I'd strongly recommend the simple approach.

**Comment by flexiondotorg** [comment]
Sorry, what you are requesting is not a use case I am interested in adding support for.
