### ISSUE TITLE
Create a Larger Disk than default

### ISSUE THREAD

**Issue by henrydenhengst** [quickemu-project/quickemu#603]
#### Expected behaviour

Describe the your expected behaviour: Create a Larger Disk

#### Actual behaviour

How to write a-guest.conf file like that?

#### Steps to reproduce the behaviour

Is this possible?

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Run the following and paste the output.

quickget nixos 22.11 gnome

vim nixos-22.11-gnome.conf

How can I tweak my config and create a larger disk, more memory etc.

**Comment by henrydenhengst** [comment]
I now solved it like this, but I don't think you want to have it don like that by all users of you tool?

[qemu-img info disk.qcow2
qemu-img resize disk.qcow2 +25G
qemu-img info disk.qcow2
sudo qemu-nbd -c /dev/nbd0 disk.qcow2
gparted /dev/nbd0
sudo qemu-nbd -d /dev/nbd0](url)

**Comment by philclifford** [comment]
from `man quickemu_conf`:

```

     Add additional lines to your virtual machine configuration:

       • cpu_cores="4" - Specify the number of CPU cores allocated to the VM

       • ram="4G" - Specify the amount of RAM to allocate to the VM

       • disk_size="16G" - Specify the size of the virtual disk allocated to the VM
```
the disk_size will only apply at creation (or after `--delete-disk` ).  That's often easier than trying to resize an existing  image, although for common linux situations resizing with qemu_img then using `parted` and `resize2fs` (in the VM or using a live iso / rescue VM with access to the image ...) is often fairly straightforward.

Do you need to `sudo qemu-nbd -d /dev/nbd0` before trying to start the VM ?
What does `gparted` show? What output/errors do you see when trying to start the VM ?

**Comment by henrydenhengst** [comment]
Works like a charm! Thanks

By the way, `man quickemu_conf` does not work for me?!

Create a VM e.g. Linux Mint, than...

```
quickemu --vm linuxmint-21-cinnamon.conf --delete-disk
vim linuxmint-21-cinnamon.conf
```

Add whatever you like e.g. .....

```
cpu_cores="4"
ram="8G"
disk_size="100G" 
```

Start VM and configure again.

Although not for noobs and not very flexible, it works.

**Comment by flexiondotorg** [comment]
This is documented in the README. If you have additional questions about using Quickemu, please join our Discord 🙂

 - https://wimpysworld.io/discord
