### ISSUE TITLE
Beginner question: how to change settings and make it run them

### ISSUE THREAD

**Issue by rexendevar** [quickemu-project/quickemu#604]
#### Expected behaviour

I would like to change the .sh launch script in the vm folder and just launch it and have quickemu use the settings I set instead of regenerating what it thinks is best. I would very much like to figure it out with this program specifically as I am not very advanced at using Linux.

#### Actual behaviour

The .sh file is overwritten with quickemu's default settings regardless of whether I use quickemu or quickGUI. This means I cannot configure my launch options at all without using a much more complex program that I don't understand.

#### Steps to reproduce the behaviour

Download a machine file - I used windows 10
Run it once to set up 
Close machine
Find `windows-10/windows-10.sh` in the quickemu folder
Make an edit to the .sh file - I tried increasing the number of cores dedicated to the VM
Save
Launch machine again via quickGUI 
Reload the text file

#### Quickemu output

```Quickemu 4.5 using /usr/bin/qemu-system-x86_64 v7.0.0
 - Host:     Pop!_OS 22.04 LTS running Linux 6.0 (pop-os)
 - CPU:      Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
 - Process:  Starting windows-10.conf as windows-10 (79114)
 ```

#### Linux Distribution & Kernel

Pop OS 22.04 LTS x86_64
Kernel version 6.0.6-76060006-generic

**Comment by philclifford** [comment]
Quickemu always creates that bash script based on the built-in options and anything provided in the `.conf` file. Your best approach is to edit the conf file to get the results you wish.

from `man quickemu_conf` :

```
OPTIONS
       These are the options and defaults for the <vm>.conf file

              # Lowercase variables are used in the VM config file only
              boot="efi"
              cpu_cores=""
              disk_img=""
              disk_size=""
              fixed_iso=""
              floppy=""
              guest_os="linux"
              img=""
              iso=""
              macaddr=""
              macos_release=""
              network=""
              port_forwards=()
              preallocation="off"
              ram=""
              secureboot="off"
              tpm="off"
              usb_devices=()
```
so you could add lines that specify, for example,

```
ram="16G"
cpu_cores="22"
```
provided you have enough spare memory and cpu cores. 

If you require something of `qemu` that is not supported by `quickemu`'s other  options or config options you might be able to achieve it by using `--extra_args` : 
```
quickemu |grep extra
  --extra_args <arguments>          : Pass additional arguments to qemu
```

**Comment by flexiondotorg** [comment]
GitHub issue tracker is not for support requests. Please see the documentation for details on how to configure and use Quickemu. If you have questions please join our Discord 🙂

 - https://wimpysworld.io/discord
