### ISSUE TITLE
Host distro Language independent

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#613]
#### Expected behaviour

Language independent

cpu cores counting works as expected in any laguage mutation of OS

#### Actual behaviour

I think any system with different base language then english suffer same...

grep 'Model Name' 'Socket' 'Vendor' ineffective

#### Steps to reproduce the behaviour

lscpu

my output:
```
Architektura:            x86_64
  Operační režim(y) CPU: 32-bit, 64-bit
  Velikost adresy:       43 bits physical, 48 bits virtual
  Pořadí bajtů:          Little Endian
Počet CPU:               12
  Seznam zapnutých CPU:  0-11
ID výrobce:              AuthenticAMD
  Název modelu:          AMD Ryzen 5 2600 Six-Core Processor
    Rodina CPU:          23
    Model:               8
    Vláken na jádro:     2
    Jader na patici:     6
    Patic:               1
    Stepping:            2

```

**Comment by zen0bit** [comment]
nproc --all
```
32
```

**Comment by zen0bit** [comment]
qemu-system-x86_64: warning: Number of SMP cpus requested (16) exceeds the recommended cpus supported by KVM (12)
qemu-system-x86_64: warning: Number of hotpluggable cpus requested (16) exceeds the recommended cpus supported by KVM (12)

**Comment by flexiondotorg** [comment]
Sadly not possible. See #614
