### ISSUE TITLE
localization support

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#614]
#### Expected behaviour

Easily translate to any language

#### Actual behaviour

only in english

###

I want translate quickemu and quickget to my native language and expecting more languages can come..

So what about make quickemu and quickget more translation friendly?

**Comment by flexiondotorg** [comment]
Sadly, this is not possible. The output of the commands is treated as a pseudo API for parsing the command outputs, which is why `export LC_ALL=C` is at the top of each script.
