### ISSUE TITLE
Quickget fails to download Windows 10 and 11 from CDN

### ISSUE THREAD

**Issue by akarasulu** [quickemu-project/quickemu#618]
#### Expected behaviour

Expecting the download to occur with quickget.

#### Actual behaviour

Instead I get:

```
Download URL not leading to Microsoft CDN
```

#### Steps to reproduce the behaviour

On a Manjaro installation install quickemu and run `quickget windows 10`. Incidentally quickgui fails too but gives no such error message.

#### Quickemu output

```
# quickget windows 10                                                                                       
Getting Windows 10 URL...
Download URL not leading to Microsoft CDN
```

#### Linux Distribution & Kernel

```
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        22.0
Codename:       Sikaris
Linux newton 6.1.1-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 21 23:21:50 UTC 2022 x86_64 GNU/Linux
```

**Comment by Luk45135** [comment]
Same as #612
