### ISSUE TITLE
Can't download devuan ISOs...

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#620]
[ERROR] CUID#7 - Download aborted. URI=https://files.devuan.org/devuan_chimaera/desktop-live/devuan_chimaera_4.0.2_amd64_desktop-live.iso Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://files.devuan.org/devuan_chimaera/desktop-live/devuan_chimaera_4.0.2_amd64_desktop-live.iso
  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: protocol error

aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR! Failed to download https://files.devuan.org/devuan_chimaera/desktop-live/devuan_chimaera_4.0.2_amd64_desktop-live.iso with aria2c. Try running 'quickget' again.

From browser it works (maybe only on my machine aria complain ???)
Other distros looks good, not tested everything...

**Comment by flexiondotorg** [comment]
I can't reproduce this. Download via https work for me from multiple locations.
