### ISSUE TITLE
Macos Command Key Not Working

### ISSUE THREAD

**Issue by skinatro** [quickemu-project/quickemu#623]
#### Expected behaviour

Pressing windows key act as command key in Mac VM

#### Actual behaviour

The VM does not grab the windows key input and it is  handled by the window manager instead (gnome)

#### Steps to reproduce the behaviour

Install macos VM on Fedora 37 , gnome 43 wayland and try to use the command key

**Comment by notsuretho** [comment]
Hey @skinatro how did you solve it then? Did you find an instruction list (commands to invoke, arguments to pass...)? If so, can you share it with me please?
