### ISSUE TITLE
feat: parse the available centos-stream mirror list

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#633]
centos-stream hard-codes the mirror, which could be improved by parsing the available mirrorlist without re-direct

_Originally posted by @philclifford in https://github.com/quickemu-project/quickemu/issues/629#issuecomment-1416001988_

**Comment by zen0bit** [comment]
Already solved?

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/commit/d01855e0ed6a83874c8304dbd7f88a4791d7485b
