### ISSUE TITLE
Documentation Glitch

### ISSUE THREAD

**Issue by suuuehgi** [quickemu-project/quickemu#645]
>`quickget` can not download Windows10 and Windows 11 automatically, but does automatically create an optimised virtual machine configuration that you can just add an Windows .iso image to. 
>[...]
>`quickget` can automatically download Windows 8.1, Windows 10 and Windows 11 along with the VirtIO drivers for Windows and creates a virtual machine configuration.

https://github.com/quickemu-project/quickemu#windows-10--11-guests

**Comment by philclifford** [comment]
Thanks for spotting and reporting my error! The fault was entirely mine and should soon be fixed.

**Comment by philclifford** [comment]
Should now be fixed - thanks again.
