### ISSUE TITLE
Add Atlasos - Optimized Windows 10

### ISSUE THREAD

**Issue by RoiArthurB** [quickemu-project/quickemu#648]
Atlasos is an open-sourced optimized version of Windows 10 (firstly aimed for gaming, but globally result in a lighter version of W10 in size and process). https://atlasos.net - https://github.com/Atlas-OS/Atlas

I greatly think that it's simple to add in the project (as the installation follow the same process as W10 but from another iso source) and is a great project to run a lighter version from VM :)

**Comment by flexiondotorg** [comment]
AtlasOS doesn't provide ISO images.
