### ISSUE TITLE
quickget: incorrect path for calling macrecovery

### ISSUE THREAD

**Issue by ObscureScience** [quickemu-project/quickemu#656]
#### Expected behaviour

running: quickget macos catalina/big-sur/monterey etc..
would download the system image so that the presented quickemu call would work.

#### Actual behaviour

The command silently fails with the print: 

Downloading monterey...
/usr/bin/quickget: line 1329: /usr/bin/macrecovery: Is a directory

before presenting the command to start the vm.

#### Steps to reproduce the behaviour

`quickget macos catalina`

#### Quickemu output

```
$ quickget --version
4.6

$ quickget macos catalina
[#3f1cf2 9.0MiB/20MiB(45%) CN:1 DL:10MiB ETA:1s]                               


Downloading catalina...
/usr/bin/quickget: line 1329: /usr/bin/macrecovery: Is a directory
Making macos-catalina.conf
Giving user execute permissions on macos-catalina.conf,

To start your macOS virtual machine run:
    quickemu --vm macos-catalina.conf
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```
$ lsb_release --all
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ uname -a
Linux callearch 6.2.1-1-cachyos-bore-lto #1 SMP PREEMPT_DYNAMIC Sat, 25 Feb 2023 15:22:50 +0000 x86_64 GNU/Linux
```

The issue could be fixed by modifying /usr/bin/quickget, 
line 1328 `${MACRECOVERY}` to `${MACRECOVERY}/macrecovery`

Likely, replacing the directory macrecovery with the file macrecovery, would have worked as well.

**Comment by flexiondotorg** [comment]
This looks like a packaging error in the Arch Linux package for Quickemu.
