### ISSUE TITLE
Missing disk installing 16.04.7

### ISSUE THREAD

**Issue by popey** [quickemu-project/quickemu#680]
#### Expected behaviour

Boot 16.04.7 and install it.

#### Actual behaviour

Installer cannot find a storage device to install onto.

![image](https://user-images.githubusercontent.com/1841272/227260492-dc375480-180e-45a7-9f4f-94a7e94fe228.png)

#### Steps to reproduce the behaviour

```
quickget ubuntu 16.04
quickemu --vm ubuntu-16.04.conf
```

Proceed to boot 16.04, select "Install Ubuntu".

#### Quickemu output

```
$ quickget  ubuntu 16.04
ubuntu-16.04/ubuntu-16.04.7-desktop-amd64.iso   100%[=====================================================================================================>]   1.58G  9.14MB/s    in 2m 50s  
Checking ubuntu-16.04/ubuntu-16.04.7-desktop-amd64.iso with sha256sum... Good!
Making ubuntu-16.04.conf
Giving user execute permissions on ubuntu-16.04.conf,

To start your Ubuntu virtual machine run:
    quickemu --vm ubuntu-16.04.conf


```

```
$     quickemu --vm ubuntu-16.04.conf
Quickemu 4.6 using /usr/bin/qemu-system-x86_64 v7.2.0
 - Host:     Ubuntu Lunar Lobster (development branch) running Linux 5.19 (ziggy)
 - CPU:      AMD Ryzen 7 PRO 6860Z with Radeon Graphics
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     ubuntu-16.04/disk.qcow2 (16G)
             Just created, booting from ubuntu-16.04/ubuntu-16.04.7-desktop-amd64.iso
 - Boot ISO: ubuntu-16.04/ubuntu-16.04.7-desktop-amd64.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-alan ~/Public
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "ubuntu-16.04/ubuntu-16.04-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-16.04/ubuntu-16.04-monitor.socket
 - Serial:   On host:  nc -U "ubuntu-16.04/ubuntu-16.04-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-16.04/ubuntu-16.04-serial.socket
 - Process:  Starting ubuntu-16.04.conf as ubuntu-16.04 (1788549)

```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Lunar Lobster (development branch)
Release:	23.04
Codename:	lunar
$ uname -a
Linux ziggy 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by philclifford** [comment]
Looks like it may be an Ubuntu / Lunar "feature" : working fine installing 16.04 on Ubuntu Mate kinetic pending the latest update

```shell
qemu-system:
  Installed: 1:7.0+dfsg-7ubuntu2.1
  Candidate: 1:7.0+dfsg-7ubuntu2.2
  Version table:
     1:7.0+dfsg-7ubuntu2.2 500 (phased 60%)
```

Did it create the disk.qcow2 OK ? If so, does  `qemu-img info ubuntu-16.04/disk.qcow2` look normal ?  Is `quickemu` / `qemu` otherwise functional on your lunar ?

**Comment by popey** [comment]
```
$ qemu-img info ubuntu-16.04/disk.qcow2 
image: ubuntu-16.04/disk.qcow2
file format: qcow2
virtual size: 16 GiB (17179869184 bytes)
disk size: 196 KiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: true
    refcount bits: 16
    corrupt: false
    extended l2: false
```

"Otherwise functional"? I mean, I get the desktop booted as per the screenshot.

**Comment by philclifford** [comment]
Looks like it is a disagreement about disk devices between the qemu presentation of virtual disk and the kernel of 16.04.  Lots of other (more recent) guests work fine, including 18.04.  I haven't gone as far as 16.04-era debians/redhats/SuSEs and debugging what's actually going on is beyond my bandwidth and possibly capability.  That's maybe worth someone with 10 years of Ubuntu Pro LTS ESM support on 16.04 to take up with Canonical .... 

These worked fine (as far as getting to dump data to the install disk) in my lunar VM:

 - [x] debian 11.6.0
 - [x] Ubuntu Mate 20.04.6 (using safe graphics)
 - [x] OpenSUSE Tumbleweed

Ubuntu 18.04 decided to have a different failure mode and will need some persuasion to boot (or testing  not on a nested VM).

![image](https://user-images.githubusercontent.com/8797027/228717559-9f9fa1ab-e04d-493d-848e-245105e0a8d7.png)

**Comment by philclifford** [comment]
raised :point_up: there and [bug 2013415](https://bugs.launchpad.net/ubuntu-desktop-installer/+bug/2013415)

**Comment by philclifford** [comment]
Neither of which appear to have been looked at ... :shrug:

**Comment by flexiondotorg** [comment]
I can't reproduce this with the upcoming quickemu 4.9.3

![image](https://github.com/quickemu-project/quickemu/assets/304639/2d0b24cb-19d7-4ff9-9cf6-259db18dd1d1)
