### ISSUE TITLE
rerun installer

### ISSUE THREAD

**Issue by JulianGro** [quickemu-project/quickemu#685]
How do you rerun an installation?

In my case, I tried installing Debian, the installation failed, and now I would like to rerun it. But I have absolutely no idea how to get it to boot the iso again instead of it just trying to boot the empty virtual drive.

**Comment by philclifford** [comment]
if you use the `--delete-disk`  parameter to `quickemu` it will remove the virtual drive, which will be recreated and the iso booted next time your run the VM.  It is an opportunity to adjust the disk size too if you want more headroom. `quickemu` without any parameters will show you the parameters.
