### ISSUE TITLE
Windows 10 not starting 

### ISSUE THREAD

**Issue by styvvy** [quickemu-project/quickemu#686]
#### Expected behaviour
I installed the quickemu and quickgui over the AUR on my machine and created a Windows 10 (over the gui and once over the cli) in theory it should just open the VM after entering the command:

```
quickemu --vm windows-10.conf
``` 

#### Actual behaviour

When i try to start it over the GUI I get a Spice Connection Prompt, when trying to open it over the CLI I get the following message:

```
➜ quickemu --vm windows-10.conf
Quickemu 4.6 using /usr/bin/qemu-system-x86_64 v7.2.1
 - Host:     "Arch Linux" running Linux 6.2 (suecyde)
 - CPU:      AMD Ryzen 9 5950X 16-Core Processor
 - CPU VM:   1 Socket(s), 8 Core(s), 2 Thread(s), 16G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
             Looks unused, booting from windows-10/windows-10.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
qemu-system-x86_64: Display 'sdl' is not available.
cat: windows-10/windows-10.pid: No such file or directory
 - Process:  Starting windows-10.conf as windows-10 ()
 - Sending:  sendkey ret
2023/04/10 10:18:41 socat[7993] E connect(, AF=1 "windows-10/windows-10-monitor.socket", 38): Connection refused

/Virtualization/VMs took 3.8s …
➜ lsa
total 16K
drwxr-xr-x 3 stywen stywen 4.0K Apr 10 10:16 .
drwxr-xr-x 6 stywen wheel  4.0K Apr 10 10:15 ..
drwxr-xr-x 3 stywen stywen 4.0K Apr 10 10:18 windows-10
-rwxr--r-- 1 stywen stywen  147 Apr 10 10:16 windows-10.conf

/Virtualization/VMs …
➜ tree .
.
├── windows-10
│   ├── disk.qcow2
│   ├── OVMF_VARS.fd
│   ├── unattended
│   │   ├── autounattend.xml
│   │   ├── spice-vdagent-x64-0.10.0.msi
│   │   ├── spice-webdavd-x64-latest.msi
│   │   └── UsbDk_1.0.22_x64.msi
│   ├── unattended.iso
│   ├── virtio-win.iso
│   ├── windows-10-agent.sock
│   ├── windows-10.log
│   ├── windows-10-monitor.socket
│   ├── windows-10.ports
│   └── windows-10.sh
└── windows-10.conf

3 directories, 14 files
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
➜ lsb_release --all
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a


Linux suecyde 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000 x86_64 GNU/Linux
```

I also tested ubuntu vm and it worked just fine.
Thanks for the help in advance!

**Comment by philclifford** [comment]
The answer for you may already be in the output you posted: 

```
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
```

**Comment by CheesyChocolate** [comment]
```
######################################################################
# Download a Windows 11 .iso image from:
#  - https://www.microsoft.com/software-download/windows11
# Put the .iso image in the windows-11 directory and rename
# it to windows-11.iso.
######################################################################
```
it seems they don't ship windows iso anymore.

```
cat: windows-10/windows-10.pid: No such file or directory
```

**Comment by giorgiga** [comment]
I'd say the actual issue is `qemu-system-x86_64: Display 'sdl' is not available.`.

I'm getting a similar error (`qemu-system-x86_64: -display sdl,gl=on: Parameter 'type' does not accept value 'sdl'`) trying with qemu 7.10, regardless of what ISO I try to start.

Apparently, sdl has not been supported in qemu for a while (see https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1829945).

I have no idea why quickemu generates `-display sdl,gl=on` as a parameter in the .sh startup script... maybe some legacy logic is being triggered for some reason?

Anyway, starting with `quickemu --vm <vm> --display spice` or `--display gtk` works for me,

**Comment by giorgiga** [comment]
(created issue  #715 about sdl still being used for display)

**Comment by flexiondotorg** [comment]
SDL has been a supported QEMU backend in Ubuntu since QEMU 6.0.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I got the same problem dont understand why this is closed?

**Comment by Amenia1999** [comment]
Still the same issue on EndavourOS

**Comment by 641i130** [comment]
Same issue with most recent packages on Arch Linux.

**Comment by zen0bit** [comment]
> Same issue with most recent packages on Arch Linux.

Looks like issue with AUR template (Not supporting SDL) not quickemu itself...

Ps: Taked quick look at qemu-full  PKGBUILD see SDL as make dependency, To make things work install optional dependecy Not included in AUR static build...

Install that optional `qemu-ui-sdl` and you should be good to go...

**Comment by AkechiShiro** [comment]
The AUR pkgs should be updated upstream someday...

**Comment by securityopa** [comment]
Have the same issue with MacOS (all versions)

**Comment by securityopa** [comment]
This is my output, any help would be appreciated:

`quickemu --vm macos-monterey.conf
Quickemu 4.9.4 using /usr/bin/qemu-system-x86_64 v7.0.0
 - Host:     Pop!_OS 22.04 LTS running Linux 6.8 (pop-os)
 - CPU:      12th Gen Intel(R) Core(TM) i7-12700K
 - CPU VM:   1 Socket(s), 1 Core(s), 2 Thread(s), 16G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-monterey/disk.qcow2 (96G)
             Looks unused, booting from macos-monterey/RecoveryImage.img
 - Recovery: macos-monterey/RecoveryImage.img
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22221
 - 9P:       On guest: sudo mount_9p Public-user
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "macos-monterey/macos-monterey-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-monterey/macos-monterey-monitor.socket
 - Serial:   On host:  nc -U "macos-monterey/macos-monterey-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-monterey/macos-monterey-serial.socket
cat: macos-monterey/macos-monterey.pid: No such file or directory
 - Process:  Starting macos-monterey.conf as macos-monterey ()`

**Comment by jackiesogi** [comment]
> This is my output, any help would be appreciated:
> 
> `quickemu --vm macos-monterey.conf Quickemu 4.9.4 using /usr/bin/qemu-system-x86_64 v7.0.0
> 
>     * Host:     Pop!_OS 22.04 LTS running Linux 6.8 (pop-os)
> 
>     * CPU:      12th Gen Intel(R) Core(TM) i7-12700K
> 
>     * CPU VM:   1 Socket(s), 1 Core(s), 2 Thread(s), 16G RAM
> 
>     * BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
> 
>     * Disk:     macos-monterey/disk.qcow2 (96G)
>       Looks unused, booting from macos-monterey/RecoveryImage.img
> 
>     * Recovery: macos-monterey/RecoveryImage.img
> 
>     * Display:  SDL, qxl-vga, GL (on), VirGL (off)
> 
>     * Sound:    intel-hda
> 
>     * ssh:      On host:  ssh user@localhost -p 22221
> 
>     * 9P:       On guest: sudo mount_9p Public-user
> 
>     * Network:  User (virtio-net)
> 
>     * Monitor:  On host:  nc -U "macos-monterey/macos-monterey-monitor.socket"
>       or     :  socat -,echo=0,icanon=0 unix-connect:macos-monterey/macos-monterey-monitor.socket
> 
>     * Serial:   On host:  nc -U "macos-monterey/macos-monterey-serial.socket"
>       or     :  socat -,echo=0,icanon=0 unix-connect:macos-monterey/macos-monterey-serial.socket
>       cat: macos-monterey/macos-monterey.pid: No such file or directory
> 
>     * Process:  Starting macos-monterey.conf as macos-monterey ()`

My problem is exact the same with yours.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/pull/1264
