### ISSUE TITLE
Vanilla OS

### ISSUE THREAD

**Issue by cloudlena** [quickemu-project/quickemu#694]
#### Expected behaviour

It would be great to have [Vanilla OS](https://vanillaos.org/) available.

#### Actual behaviour

Currently, it's not available.

#### Quickemu output

```shell
$ quickget vanillaos
ERROR! vanillaos is not a supported OS.
```

#### Linux Distribution & Kernel

```
Linux tuxedo 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux
```

**Comment by philclifford** [comment]
duplicate of #644
