### ISSUE TITLE
quickemu starts qemu with `-display sdl,gl=on`

### ISSUE THREAD

**Issue by giorgiga** [quickemu-project/quickemu#715]
I'm getting `qemu-system-x86_64: -display sdl,gl=on: Parameter 'type' does not accept value 'sdl'`  with qemu 7.10, regardless of what ISO I try to start.

Apparently, sdl has not been supported in qemu for a while (see https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1829945).

I have no idea why quickemu generates `-display sdl,gl=on` as a parameter in the .sh startup script... maybe some legacy logic is being triggered for some reason?

Anyway, starting with `quickemu --vm <vm> --display spice` or `--display gtk` works for me,

**Comment by HarryPsalms** [comment]
> I'm getting `qemu-system-x86_64: -display sdl,gl=on: Parameter 'type' does not accept value 'sdl'` with qemu 7.10, regardless of what ISO I try to start.
> 
> Apparently, sdl has not been supported in qemu for a while (see https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1829945).
> 
> I have no idea why quickemu generates `-display sdl,gl=on` as a parameter in the .sh startup script... maybe some legacy logic is being triggered for some reason?
> 
> Anyway, starting with `quickemu --vm <vm> --display spice` or `--display gtk` works for me,

I'm running 8.0.50 and am getting the same exact "Parameter 'type' does not accept value 'sdl'" error as you, except neither the --display spice nor --display gtk options are working for me.

**Comment by flexiondotorg** [comment]
SDL has been a default backend in Ubuntu since QEMU 6.0

- https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1256185/comments/32

**Comment by zen0bit** [comment]
Looks like issue with AUR template (Not supporting SDL) not quickemu itself...

Ps: Taked quick look at qemu-full  PKGBUILD see SDL as make dependency, To make things work install optional dependecy Not included in AUR static build...

Install that optional `qemu-ui-sdl` and you should be good to go...
Check that build script before building...
https://gitlab.archlinux.org/archlinux/packaging/packages/qemu/-/blob/main/PKGBUILD?ref_type=heads
