### ISSUE TITLE
Add support for TUXEDO OS

### ISSUE THREAD

**Issue by jochristian** [quickemu-project/quickemu#721]
Hi,

Support for TUXEDO OS would be great.
https://www.tuxedocomputers.com/en/TUXEDO-OS_1.tuxedo
https://os.tuxedocomputers.com/

**Comment by zen0bit** [comment]
https://github.com/quickemu-project/quickemu/pull/749

**Comment by jochristian** [comment]
Hi,

I do understand your point of view on this.
But since quickemu does support pop_os I tought Tuxedo OS was also acceptable.
As you know pop_os is an distro created by system76 for their hardware-specific laptops and desktops.

**Comment by jochristian** [comment]
> I am not going to accept distros that are primarily designed for/by OEMs as they will often carry hardware-specific enablement that is unnecessary in VMs.

**Comment by jochristian** [comment]
> I am not going to accept distros that are primarily designed for/by OEMs as they will often carry hardware-specific enablement that is unnecessary in VMs.

Hi,

I do understand your point of view on this.
But since quickemu does support pop_os I tought Tuxedo OS was also acceptable.
As you know pop_os is an distro created by system76 for their hardware-specific laptops and desktops.

**Comment by zen0bit** [comment]
stay included in my fork..
