### ISSUE TITLE
iPhone emulator

### ISSUE THREAD

**Issue by LDprg** [quickemu-project/quickemu#737]
There is also an android emulator with quickemu, so why not adding an iphone(ios) emulator. I would need it for working with homekit without having an iphone.

**Comment by takov751** [comment]
Greetings,

That is to my knowledge is not achievable. While there are IDE like softwares that does some short of emulation, there is only one way to emulate ios with qemu is https://github.com/sickcodes/Docker-eyeOS . However that only brings GDB functionality. So to summarise it's not viable. If you like to use homekit to some extend i would recommend hosting a home assistant instance[homeassistant.io](https://www.home-assistant.io/)
