### ISSUE TITLE
Gentoo VMs do not have enough disk space.

### ISSUE THREAD

**Issue by jon-bit** [quickemu-project/quickemu#738]
When you make the disk image for it, it is not enough to install Gentoo. I don't know how much space is needed for Gentoo(I tried in installing it last night for the first time) but I keep getting the no more disk space error. Is it meant only to be booted live or is their a real/temp fix for this?

**Comment by zen0bit** [comment]
I can easily solve that.

But leaving for now for someone new..
Since I already solved my first issue here 😃
