### ISSUE TITLE
bootloader crimes

### ISSUE THREAD

**Issue by f0rdprefect** [quickemu-project/quickemu#739]
No a bug bit a feature request of some kind.

There was a talk on the CCC-Camp about how to use a minimal linux to bootstrap windows 11 with custom configuration. Please see github page for more info

https://github.com/Phaeilo/bootloader-crimes

I spend some time to figure out how to call qemu to try this method and all the time I wished quickemu could do the heavy lifting for me ;)

Anyhow if someone wants to try 

``qemu-img convert -O qcow2 disk.vmdk disk.qcow2``

``qemu-system-x86_64 -machine q35 -cpu host -m 8G -net nic,model=e1000 -net user -hda disk.qcow2 -enable-kvm``

Might be helpful.

**Comment by flexiondotorg** [comment]
Please re-submit this issue as a specific feature request :+1: The current issue doesn't describe a tractable bug or feature request.
