### ISSUE TITLE
Windows 10-11 installing issue

### ISSUE THREAD

**Issue by Jonikster** [quickemu-project/quickemu#741]
Hi all,
Using Ubuntu 23.04 I tried to install Windows 10-11:
quickget windows 10
quickget windows 11
Then I try to run:
quickemu --vm windows-10-22H2.conf
Quickemu 4.8 using /usr/bin/qemu-system-x86_64 v7.2.0
 - Host:     Ubuntu 23.04 running Linux 6.2 (john-Zenbook-UX3402ZA-UX3402ZA)
 - CPU:       12th Gen Intel(R) Core(TM) i5-1240P
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
             Looks unused, booting from windows-10/Win10_22H2_EnglishInternational_x64v1.iso
 - Boot ISO: windows-10/Win10_22H2_EnglishInternational_x64v1.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-22H2-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-22H2-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-22H2-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-22H2-serial.socket
audio: Could not init `pa' audio driver
cat: windows-10/windows-10-22H2.pid: No such file or directory
 - Process:  Starting windows-10-22H2.conf as windows-10-22H2 ()
 - Sending:  sendkey ret
2023/09/06 14:05:19 socat[22877] E connect(, AF=1 "windows-10/windows-10-22H2-monitor.socket", 43): Connection refused

quickemu --vm windows-11-22H2.conf
Quickemu 4.8 using /usr/bin/qemu-system-x86_64 v7.2.0
 - Host:     Ubuntu 23.04 running Linux 6.2 (john-Zenbook-UX3402ZA-UX3402ZA)
 - CPU:       12th Gen Intel(R) Core(TM) i5-1240P
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_22H2_English_x64v1.iso
 - Boot ISO: windows-11/Win11_22H2_English_x64v1.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11-22H2.swtpm-sock (22183)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-22H2-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-22H2-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-22H2-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-22H2-serial.socket
audio: Could not init `pa' audio driver
cat: windows-11/windows-11-22H2.pid: No such file or directory
 - Process:  Starting windows-11-22H2.conf as windows-11-22H2 ()
 - Sending:  sendkey ret
2023/09/06 14:02:50 socat[22193] E connect(, AF=1 "windows-11/windows-11-22H2-monitor.socket", 43): Connection refused

Is it possible to fix?
Thanks in advance!

**Comment by TuxVinyards** [comment]
`quickemu --vm windows-11-22H2.conf` Are you issuing that command from your VM folder?  

The output says it can't find the pid file.  Qemu should generate that file when it starts.

Try qqX ??

**Comment by AkechiShiro** [comment]
I've ran into the same issue, what can we do to help for more debugging or fix this issue ?

**Comment by flexiondotorg** [comment]
Please try editing the quickemu config file for Windows 10/11 and changing `secureboot="on"` to `secureboot="off"`

**Comment by flexiondotorg** [comment]
Fixed via #836
