### ISSUE TITLE
docs: create a project website

### ISSUE THREAD

**Issue by vignesh7056** [quickemu-project/quickemu#744]
what about creating a website for quickemu project

**Comment by vignesh7056** [comment]
@flexiondotorg  ok i can help on this. can you please create a folder on the repo for this requirement. lets try to create a mvp.

**Comment by zen0bit** [comment]
### Any progress @flexiondotorg?

# What we wanna use?

### Own domain?
 - best
### Github domain?
 - good
   - For whoole quickemu project?
     - Then create repository `.github` in quickemu-project organization

   - Only for quickemu?
     - Then create `gh-pages` branch in this repo
     - Or we can push it from here...

### What we first push first?
- Just same README.md as here (as most projects do.

# So look like only show stopper here is that choice...

**Comment by flexiondotorg** [comment]
I think a Hugo static site on GitHub pages would be sufficient. Other than providing a landing page, other ideas are:

- A page for the daily `quickget` configuration can be published as `.json` and `.csv`
- A page for the current failing `quickget` tests

**Comment by nfowlie** [comment]
Saw that this was an issue with Help Wanted.  How can I apply to help?

**Comment by flexiondotorg** [comment]
@nfowlie I'm not sure yet because I haven't decided if creating a website is the way to go yet. 

But if we do, I'd like to use Hugo and the [Coder](https://themes.gohugo.io/themes/hugo-coder/) theme because the site should be minimal and really just serve as a jumping-off point for the projects.

**Comment by flexiondotorg** [comment]
> Saw that this was an issue with Help Wanted. How can I apply to help?

If I create a repo for the website, are you interested in sending pull requests to get things up and running? GitHub pages (no CNAME for a real domain) is what I'm thinking.

**Comment by nfowlie** [comment]
@flexiondotorg absolutely!
I'd love to contribute to a project I love.

**Comment by nfowlie** [comment]
@flexiondotorg I now have some free time to dedicate to this feature.  Would you be able to create a repo for this and move the task into the In Progress column.

Thank you.

**Comment by flexiondotorg** [comment]
@nfowlie I've created a repo for the website here:

- https://github.com/quickemu-project/quickemu-project.github.io

It is a minimal Hugo site using the [Hugo Coder theme](https://github.com/luizdepra/hugo-coder/) with just enough configuration to function as a landing page.

Basic CI is wired up along with the usual community standards. The site is here:

- https://quickemu-project.github.io/

I've created a "Webwranglers" team and I've invited you to join :tickets: 

I'll close this issue and we can collaborate on over here:

- https://github.com/quickemu-project/quickemu-project.github.io/issues/11
