### ISSUE TITLE
feat: support running Quickemu on arm64 host

### ISSUE THREAD

**Issue by brad** [quickemu-project/quickemu#784]
#### Expected behaviour

Any chance we can virtualize MacOS in Asahi Linux? I know for a fact this CPU can run MacOS 😉 

#### Actual behaviour

Error about unsupported CPU

#### Steps to reproduce the behaviour

```
quickget macos catalina
quickemu --vm macos-catalina.conf
```

#### Quickemu output

```
Quickemu 4.8 using /usr/bin/qemu-system-x86_64 v7.2.6
 - Host:     "Fedora Asahi Remix release 38 (Thirty Eight)" running Linux 6.5 (MacBook-Pro.lan)
 - CPU:       -
 -
 - CPU VM:   1
1 Socket(s), 4 Core(s), 1 Thread(s), 4G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
ERROR! macOS catalina requires a CPU with SSE 4.1 support.
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
LSB Version:	:core-4.1-aarch64:core-4.1-noarch:cxx-4.1-aarch64:cxx-4.1-noarch:desktop-4.1-aarch64:desktop-4.1-noarch:languages-4.1-aarch64:languages-4.1-noarch:printing-4.1-aarch64:printing-4.1-noarch
Distributor ID:	FedoraAsahiRemix
Description:	Fedora Asahi Remix release 38 (Thirty Eight)
Release:	38
Codename:	ThirtyEight
Linux MacBook-Pro.lan 6.5.4-403.asahi.fc38.aarch64+16k #1 SMP PREEMPT_DYNAMIC Fri Sep 22 20:51:27 UTC 2023 aarch64 GNU/Linux
```

**Comment by TuxVinyards** [comment]
<https://github.com/TuxVinyards/qqX>

Am currently working on being able to  have different machine types in the config file.   Should be out in the next qqX release.

**Comment by flexiondotorg** [comment]
Running Asahi Linux on anything other than Apple Silicon hardware is pointless. This is out of scope for the project.

**Comment by brad** [comment]
You misunderstand. I am running Asahi Linux on a Mac, and I want to use quickemu to run MacOS

**Comment by codingCoffee** [comment]
Curious about this! I'm running `Asahi Linux (Fedora Redmix Edition)` on my `Macbook Pro (2023) 14"` model. Since this is running on Apple Silicon hardware, would it be possible to run `MacOS Sonoma` via QEMU on it!? Requesting to reopen this issue. :)

**Comment by flexiondotorg** [comment]
Thanks for clarifying. I've re-opened the issue and changed the title :+1: 

I don't have suitable hardware to work on this feature, so pull requests welcome :smiley:
