### ISSUE TITLE
Scaling with --display spice is off on Wayland + KDE + Display Scaling

### ISSUE THREAD

**Issue by 9SMTM6** [quickemu-project/quickemu#785]
This has been reproducible for me on arch KDE. Its probably an upstream issue, but I only have a dirty fix, and there are some things that maybe should be investigated here.

#### Expected behaviour

If I start a quickemu vm with `--display spice` (eg windows) while in a Wayland KDE session with (fractional) scaling applied to the current display, the resulting SPICE client should handle resolution correctly. Meaning with `Options > Scale display` (scaling) disabled it should display the VM in the actually set resolution, and if `Options > Resize guest to match window size` (auto-resize) is enabled, it should scale the VM to the correct resolution.

#### Actual behaviour

scaling disabled displays the VM in too small a window for the set resolution. auto-resize chooses too high a resolution (it seems to be too high according to the set scale, so 135% scaling means its set to 1.35 times the native resolution when maximized).

This also leads to ugly scaling artifacts, because the scale is too small, making text hard to read. It also seems to considerably increase system load (my laptop really ramps up its fans, seems to be mostly gone with the fix).

#### Steps to reproduce the behaviour

This is not going to be easy to reproduce, but assuming that wayland becomes the default sooner or later, and assuming that this isnt arch linux specific, its only going to become more common. Since it doesnt make quickemu entirely unusable and running a VM isnt exactly expected to be low on system resources, I would not be surprised if a significant number of people already suffer a worse experience than possible, without realizing that.

1. Presumably any Linux distro with KDE, or at least Arch based distro without large changes to the packages used by quickemu should do as base (EndavourOS and Manjaro were tested)
2. enable Wayland: Ensure dependencies are installed (`plasma-wayland-session` on arch) and choose the wayland session on the login screen (lower left corner)
3. install and start a quickemu vm with the SPICE client (eg `quickget windows 11 && quickemu quickemu --vm windows-11-22H2.conf --display spice`)
4. (for auto-resize) install the SPICE guest drivers
5. ensure the options are set according to the above error cases.
6. observe a VM window with the wrong scaling and its drawbacks.

#### Quickemu output

```
> Quickemu 4.8 using /usr/bin/qemu-system-x86_64 v8.1.1
 - Host:     "EndeavourOS Linux" running Linux 6.5 (cloakOfManyColors)
 - CPU:       12th Gen Intel(R) Core(TM) i5-1240P
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.secboot.fd), SecureBoot (on).
 - Disk:     windows-11/disk.qcow2 (64G)
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11-22H2" --port 5930 --spice-shared-dir /home/smaier/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11-22H2.swtpm-sock (19336)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-22H2-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-22H2-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-22H2-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-22H2-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
 - Process:  Starting windows-11-22H2.conf as windows-11-22H2 (19339)
 - Viewer:   spicy --title "windows-11-22H2" --port "5930" --spice-shared-dir "/home/smaier/Public" "" >/dev/null 2>&1 &
```

#### Linux Distribution & Kernel

I think the most important bit is that I'm running KDE + Wayland with display scaling, perhaps also with the specific versions from Arch Linux, that would have to be tested.

Heres what you asked for

```bash
> lsb_release --all
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling
# EndavourOS uses Arch Linux repos directly
# also has been observed in Manjaro Arch

> uname -a
Linux cloakOfManyColors 6.5.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 x86_64 GNU/Linux
```

#### Proposed fix

The fix I found was to force the spicy client to run through xWayland (X11 compatibility layer) instead of using the apparently native Wayland client (observed with `qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole`).

QT or GTK specific ways to do that did not work, but unsetting `WAYLAND_DISPLAY` worked. So if before I did `quickemu --vm windows-11-22H2.conf --display spice`, now I do `WAYLAND_DISPLAY= quickemu --vm windows-11-22H2.conf --display spice`.

That this works can be observed in the debug console mentioned above, or simply by the fact that the VM window now scales correctly.

You could add unsetting of that environment variable to the issued command from quickemu, if the same issue is also present on Gnome, otherwise I'm not sure, perhaps autodetection, or otherwise at least a mention in the Readme.

However, and this is part of why I did not raise this as an issue upstream in spicy (in addition to the fact I could not find an issue tracker anyways): Spicy isn't supposed to be used in production anyways, its just a `test client` in their words (I'd call it reference implementation). The website for spicy suggests using `remote-viewer` (from virt-manager). This would obviously be a big effort for you, but seeing as the reason for you to choose spicy hasn't been discussed to my knowledge, I just wanted to put that out there.

**Comment by 9SMTM6** [comment]
I found this, just as I finished this issue: https://github.com/quickemu-project/quickemu/issues/127. I'll test if that same issue occurs with that.

If its fixed with that, I guess my recommendation would simply be to switch to using that 'by default' (meaning adjusting the readme and other documentation to suggest that instead of --display spice)

**Comment by 9SMTM6** [comment]
Nah. That behaves fairly similar, except that it seems to have issues with xWayland: If I launch it with `WAYLAND_DISPLAY= ` prefixed it agains has correct scaling, but there is some weird transparency of most of the Application window, including the VM, making this less usable.

Also while the GUI has easier access to regular things, I could not get auto-resize of the guest working (the option I though would set that didnt change anything I could observe).

**Comment by flexiondotorg** [comment]
Quickemu just launches the spice viewers, they are not part of this project so it would be best if you raise this issue with the relevant project :+1:
