### ISSUE TITLE
quickemu quickget X terminal project now in release  > readme.md   

### ISSUE THREAD

**Issue by TuxVinyards** [quickemu-project/quickemu#803]
![](https://user-images.githubusercontent.com/3956806/263740125-18e5c495-8072-49a5-8b9c-e1302549efcf.jpg)

<https://github.com/TuxVinyards/qqX>

Offers users a lot of new features & may be happily installed alongside quickgui or quickemu shortcuts without problems.

Now in official release, after  lengthy release candidate staging and testing.

All scripts have been carefully Shellcheck linted & have full error handling routines.

**Comment by flexiondotorg** [comment]
Hi @TuxVinyards :wave: 

I've seen you mention qqX, looks like an interesting project. I need to find time to test it 😅

What is this issue about exactly?

**Comment by TuxVinyards** [comment]
@flexiondotorg qqX may be happily installed alongside quickgui or quickemu shortcuts. What I would like is a mention of this project in the quickemu readme, in the usage section, as an alternative to quickgui.

Having spent the last 8 or 9 months working on this project, I do hope you can find ten minutes to download and run this program.   It's a very easy install & in actual fact it has a lot of time saving features built in, so you may even gain time :rofl: 

A GUI can look more polished but by using the same simple scripting language as quickemu, we can achieve far easier modding, editing & interaction ... and thus a much more powerful interface.

There are none of steep learning curves often involved with a GUI, which allows better community involvement.

I am currently working the ability to select different qemu machines and to have the settings in the .conf file so switching for example to aarch64  raspi3b on the fly should be possible.

Other little features, other than snapshot & disk management,  like telling you how long it is since your Ubuntu Mate Live VM was updated may appeal to certain users too ....

**Comment by TuxVinyards** [comment]
:rofl:   Just saw your commit @philclifford  after I had done mine ...    (thanks)

Oh well.   Lets see what Wimpy thoughts are.   

I think a few more things have been added to qqX since your bullet point list maybe ....

**Comment by philclifford** [comment]
Just wanted to include a mention of some highlight features, enough to spark interest but not intended to be complete. Happy to see your feature list continues to grow.

**Comment by TuxVinyards** [comment]
Yay  :heart:
