### ISSUE TITLE
Add tiny10 / tiny11 images for windows

### ISSUE THREAD

**Issue by LDprg** [quickemu-project/quickemu#827]
Since Windows is quite bloated per default it would be nice if quickemu give the user the option to also download tiny10 images with quickget. Tiny10 is a debloated performance improved windows, which is generally really good for VMs.

**Comment by LDprg** [comment]
I did some testing with tiny10:
1. Download win10 with quickget
2. Replace win10 image with tiny10 image from archive.org (offical download)
3. manually load drivers from the virtio disk for SCSI (needed so vm detects the install drive)
4. Complete normal win10 setup (automated steps seem not to work)

The setup took a bit longer (because of manual steps), however the VM was alot faster and the ISO was only 3,6 GB compared to the normal 5,6 GB.

**Comment by LDprg** [comment]
The windows also isn't activated automatically, seems like all automation steps do not work.

**Comment by flexiondotorg** [comment]
This is our of scope for the project. You can craft your own configuration to support tiny10/11 images.
