### ISSUE TITLE
Allow usb mouse by default

### ISSUE THREAD

**Issue by Grubben** [quickemu-project/quickemu#830]
#### Expected behaviour
When I run the VM I should be able to use my mouse

#### Actual behaviour
There reaches a point where the host mouse leaves the window and I can't access the rest of the guest screen

#### Steps to reproduce the behaviour
quickget macos catalina
quickemu --vm macos-catalina.conf

#### Solution
I actually found the solution (by trying a million things cause I'm a noob. On that note, this should be a PR not an issue since I have the solution but I wouldn't know where to start to actually implement this)
Add
-device usb-mouse \
to macos-catalina.sh in the folder next to macos-catalina.conf

#### Version
I am running version 4.8 on NixOS

**Comment by TuxVinyards** [comment]
Try adding `mouse="usb"` to the .conf file.  Let us know if that works.

**Comment by flexiondotorg** [comment]
quickemu has documented features to selected the mouse protocol to override the default behaviour.
