### ISSUE TITLE
problem with the installing windows 11

### ISSUE THREAD

**Issue by BENDER35** [quickemu-project/quickemu#831]
#### Expected behaviour

Describe the your expected behaviour.

attempt to install windows 11 from quickemu-quickget

#### Actual behaviour

Describe the actual behaviour.

When installing Windows 11, when the download finishes, when downloading the drivers it gives an error

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.

executed quickget in windows 11, it gives an error (capture attached)

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

![Captura de pantalla -2023-11-03 17-06-40](https://github.com/quickemu-project/quickemu/assets/62604047/ffc14064-d3b0-4758-8ac9-3ec4ef11fdc7)

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
bender@C50:~$ lsb_release --all
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
bender@C50:~$ 

bender@C50:~$ uname -a
Linux C50 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
bender@C50:~$

**Comment by TuxVinyards** [comment]
The error screen suggests running things again.  Did you try that?

Did you try coping the given link and seeing if worked manually?

Was it simply a temporary Fedora server problem, other words?

**Comment by BENDER35** [comment]
> The error screen suggests running things again. Did you try that?
> 
> Did you try copying the given link and seeing if worked manually?
> 
> Was it simply a temporary Fedora server problem, other words?
> 
> `wget "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso"`
> 
> works for me.

hello

I have downloaded the ISO with wget and when I run it through quickget I still get the same error and it cannot create the configuration file necessary to load the windows 11 qemu.

I attach the log of the error I got when combining wget with quickget.

greetings
[log_virtio.txt](https://github.com/quickemu-project/quickemu/files/13261434/log_virtio.txt)

**Comment by TuxVinyards** [comment]
Apologies if not clear.   The error says:  "Try running 'quickget' again."     This is what I  meant  by try running 'things' again.   

What I meant by "wget  etc ... " works for me, was that I tested the link that quickget uses and that it was working.

Now that you have the downloads, if you run the command `quickget windows 11` again, the installation should work.   

I also recommend that you set the disk_size to 128G in the .conf file, not 64 as the default gives you.

**Comment by flexiondotorg** [comment]
I can't reproduce this, it looks like a temporary cert issue on fedorapeople.org
