### ISSUE TITLE
remote-viewer can't connect remotely due to hard coded value in the script

### ISSUE THREAD

**Issue by colino17** [quickemu-project/quickemu#833]
#### Expected behaviour

Using remote-viewer on a LAN device to access the Spice session should work whether using it locally on the host (ex: spice://localhost:5930) or remotely on a different LAN machine (ex: spice://192.168.0.10:5930).

#### Actual behaviour

Using remote-viewer locally on the host (ex: spice://localhost:5930) works, however using it remotely (ex: spice://192.168.0.10:5930) will not connect.

#### Steps to reproduce the behaviour

1. Run VM (ex: quickemu --vm vmname.conf --display none) [note multiple display/viewer flag combos were tried]
2. Open remote-viewer and try to connect to the VM using the IP address (ex: spice://192.168.0.10:5930).
3. Open remote-viewer on the host and try to connect to the VM using locahost (ex: spice://localhost:5930).

#### Steps to bypass the behaviour
I was able to achieve the expected behaviour by editing line 867 of the quickemu script and changing: 
```bash
SPICE="${SPICE},port=${SPICE_PORT},addr=127.0.0.1
```
to
```bash
SPICE="${SPICE},port=${SPICE_PORT}
```

#### Linux Distribution & Kernel

Tried on multiple distros including NixOS 23.05 and Ubuntu 22.04.

**Comment by philclifford** [comment]
The behaviour is intentionally restricted by default. It should be possible to add an option to expose the display on a selected address or addresses (possibly with intelligent detection and use of e.g. tailscale) or unrestricted.
