### ISSUE TITLE
When using the new  `-s` or `-t` options  in some cases the download commences

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickemu#845]
There is an issue when using the new  `-s` or `-t` options if `aria2c` is available,  or with `*daily*` releases if `zsync` is available. In such cases the download commences via `aria2c` or `zsync`.

If `aria2c` and/or `zsync` are not installed  (or the binaries temporarily moved or renamed) and `quickget` falls back to using  `wget` then the expected behaviour for  `-s` or `-t ` is observed.

_Originally posted by @philclifford in https://github.com/quickemu-project/quickemu/issues/801#issuecomment-1810764818_

**Comment by zen0bit** [comment]
As stated in my PR not everything worked perfectly

new features:
quickget commands
- [x] --show-iso-url (not fully tested)
    `quickget --show-iso-url alpine latest`
    or
    `quickget -s bodhi 7.0.0 standard`
- [x] --test-iso-url (not fully tested)
    `quickget --test-iso-url alpine latest`
    or
    `quickget -t bodhi 7.0.0 standard`
- [x] --open-distro-homepage
    `quickget --open-distro-homepage alpine`
    or
    `quickget -o vxlinux`
- [x] zsync/aria2 support in #846 Thanks
- [ ] more testing
