### ISSUE TITLE
Can't install quickemu on parrot OS

### ISSUE THREAD

**Issue by cabiamdos** [quickemu-project/quickemu#863]
#### Expected behaviour

Describe the your expected behaviour.
Installation on parrot os
#### Actual behaviour

Describe the actual behaviour.
Can't install on parrot OS
#### Steps to reproduce the behaviour
```
sudo apt-add-repository ppa:flexiondotorg/quickemu 
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 361, in <module>
    addaptrepo = AddAptRepository()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/bin/apt-add-repository", line 39, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Debian/lory
```
Outline the step to reproduce the issue you've encountered.
this guide (https://christitus.com/quickemu/)
#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.
Nothing
#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
```
lsb_release --all

uname -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Parrot Security 6.0 (lorikeet)
Release:	6.0
Codename:	lory
Linux parrot 6.5.0-3parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-3parrot1 (2023-10-20) x86_64 GNU/Linux
```

**Comment by lj3954** [comment]
Debian and its derivatives do not support Ubuntu PPAs. You should instead install quickemu through git, and add the directory you cloned the repository in to your PATH.

**Comment by flexiondotorg** [comment]
You should use the .deb published in the GitHub Release page to install on Parrot OS.
