### ISSUE TITLE
include default distros username:password

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#877]
#### Expected behaviour

I think could be awesome include in quickget (config) default username and password for ISOs
Also show it in VM starting message
Also would be helpfull for easier ssh into VMs...

#### Actual behaviour
Google fu / Homepage (link straight from quickget) ![Did it](https://github.githubassets.com/assets/1f680-d0ef47fdb515.png))

Should I?

**Comment by TuxVinyards** [comment]
I have started work on integrating your work on homepage links to qqX this morning.

Basically, doing a grep of quickget for OS name and filtering for  "HOMEPAGE=" from within your function os_homepages seems to be the way forward ...

I guess I could do similar with passwords but I think that the maintenance requirements for quickget are already very high. Probably even too high.  

The more that is hard coded the more there is the check and maintain. 

On the other hand, if we use some kind of accompanying caveat like a 'last known' or 'probable'  user/password to use with Live ISO's then this could save a lot of  searching around on the homepage. So, might be a good idea 👍

**Comment by flexiondotorg** [comment]
Sorry, this is one idea I am not in favour of including.

**Comment by zen0bit** [comment]
> Sorry, this is one idea I am not in favour of including.

You already included :rofl:
