### ISSUE TITLE
bug: VM fails to start because smartcard support is absent

### ISSUE THREAD

**Issue by DidierSpaier** [quickemu-project/quickemu#888]
#### Expected behaviour

quickemu --vm <distro> <version> should start the VM

#### Actual behaviour

The VM fails to start.

 Please note that I have installed qemu 8.2.0. [Configuration summary](https://slackware.uk/slint/x86_64/slint-15.0/source/qemu/LOG_8.2.0). 

#### Steps to reproduce the behaviour

Outline the step to reproduce the issue you've encountered.

```
quickget windows 11
quickemu --vm windows-11.conf
```
I have tried other distributions, same issue in all cases.
#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

```
quickemu --vm windows-11.conf
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.0
 - Host:     Slint 15.0 running Linux 6.6 (ici.ici.net)
 - CPU:       Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permanent by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (Windows), OVMF (/usr/share/qemu/edk2-x86_64-code.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_23H2_English_x64v2.iso
 - Boot ISO: windows-11/Win11_23H2_English_x64v2.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - TPM:      windows-11/windows-11.swtpm-sock (6844)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
qemu-system-x86_64: -chardev spicevmc,id=ccid,name=smartcard: unsupported type name: smartcard
allowed spice char type names: vdagent, usbredir
cat: windows-11/windows-11.pid: No such file or directory
 - Process:  Starting windows-11.conf as windows-11 ()
 - Sending:  sendkey ret
2023/12/29 18:52:56 socat[6854] E connect(5, AF=2 127.0.0.1:4440, 16): Connection refused
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
lsb_release is not installed however os-release is present:

```
didier[bigfiles]$ cat /etc/os-release
NAME=Slint
VERSION="15.0"
ID=slint
VERSION_ID=15.0
PRETTY_NAME="Slint 15.0"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slint:slint_linux:15.0"
HOME_URL="https://slint.fr/"
SUPPORT_URL="https://www.freelists.org/list/slint"
BUG_REPORT_URL="https://www.freelists.org/list/slint"
```
```
didier[bigfiles]$ uname -a
Linux ici.ici.net 6.6.7 #1 SMP PREEMPT_DYNAMIC Thu Dec 14 21:30:24 CET 2023 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux
```
FYI this script instead works: https://slint.fr/doc/windows11.sh

**Comment by zen0bit** [comment]
Not directly releated but what about adding slint to supported distros? 🤔

Not many distros for blind people I think...

**Comment by DidierSpaier** [comment]
> Not directly releated but what about adding slint to supported distros? 🤔
> 
> Not many distros for blind people I think...

Yes, this has been suggested by a friend so I consider doing that and also package quickemu for Slint, this is why I am trying it. But for this to happen I have to test it successfully first :)

**Comment by lj3954** [comment]
Smartcard support is disabled in your distro's QEMU build. You'll have to build QEMU yourself or request the distro maintainers to enable the feature in the next build. This is not a quickemu issue.

**Comment by DidierSpaier** [comment]
> Smartcard support is disabled in your distro's QEMU build. You'll have to build QEMU yourself or request the distro maintainers to enable the feature in the next build. This is not a quickemu issue.

I can rebuild QEMU (I am the distro maintainer), but I suggest that the required features of QEMU to run quickemu be documented. Maybe they are, but I was unable to find such an information. Do I need better glasses?
I would not like to also miss another needed feature, hence my question.

**Comment by zen0bit** [comment]
> > Not directly releated but what about adding slint to supported distros? 🤔
> > Not many distros for blind people I think...
> 
> Yes, this has been suggested by a friend so I consider doing that and also package quickemu for Slint, this is why I am trying it. But for this to happen I have to test it successfully first :)

#889

Some specific distro requirements?
I spot something about 50GB on DisteroWtch...

**Comment by DidierSpaier** [comment]
Digging a little more i have found the answer in a closed issue: https://github.com/quickemu-project/quickemu/issues/717

However I agree with this comment https://github.com/quickemu-project/quickemu/pull/364#issuecomment-1046211509

**Comment by DidierSpaier** [comment]
> Add Slint PR #889
> 
> Some specific distro requirements? I spot something about 50GB on DistroWatch...

Yes, listed [here](https://slint.fr/en/HandBook.html#_requirements).  By the way I still do not really know why Jesse Smith failed to install it...

**Comment by zen0bit** [comment]
Added 50G to config file

testing...

Live ISO would be nice for quicker testing...

**Comment by DidierSpaier** [comment]
> Live ISO would be nice for quicker testing...

Yes. Contributors are welcome  :)

**Comment by TuxVinyards** [comment]
This isn't affecting all distros. My feeling is that issue is down to differing Qemu builds and/or differing dependency builds in different distros. 

 Manjaro offered  updates to Qemu 8.2 yesterday.  It all works fine.  Smartcard is present as normal.  

![8 2 smartcard](https://github.com/quickemu-project/quickemu/assets/3956806/c6426510-44e8-4605-8199-fcb078ae70a5)

Irrespectively,   I have added a hot fix for this problem to qqX this morning while we wait for a new quickemu update ...

<https://github.com/TuxVinyards/qqX/releases/tag/1.4.05>

**Comment by flexiondotorg** [comment]
Closed via #986

**Comment by atykhonov** [comment]
I could fix this issue on Gentoo Linux by rebuilding `app-emulation/spice` with `smartcard` USE flag. I built `app-emulation/qemu` with `smartcard` as well but this didn't help.

**Comment by lj3954** [comment]
This issue was fixed several releases ago, it's no longer relevant.

**Comment by atykhonov** [comment]
> This issue was fixed several releases ago, it's no longer relevant.

I ran into it an hour ago.

**Comment by lj3954** [comment]
> > This issue was fixed several releases ago, it's no longer relevant.
> 
> I ran into it an hour ago.
> 
> ```
> $ ./quickemu --version                      
> 4.9.5
> ```

Please paste the output of `qemu-system-x86_64 -device help | grep smartcard`

**Comment by atykhonov** [comment]
> Please paste the output of qemu-system-x86_64 -device help | grep smartcard, if you still have access to the build in which you experienced these issues.

I built `qemu` with `smartcard` USE flag. So it was there, but still, the issue remained actual. It was fixed when I rebuilt `app-emulation/spice` with `smartcard` USE flag as I wrote in my comment.

Ok, np, if you still need it, here it is:

```
$ qemu-system-x86_64 -device help | grep smartcard
name "ccid-card-emulated", bus ccid-bus, desc "emulated smartcard"
name "ccid-card-passthru", bus ccid-bus, desc "passthrough smartcard"
name "usb-ccid", bus usb-bus, desc "CCID Rev 1.1 smartcard reader"
```

**Comment by lj3954** [comment]
Re-opening issue due to regression in https://github.com/quickemu-project/quickemu/commit/e29173a16d5fb1546a725a28bc8973007b228bbe

**Comment by flexiondotorg** [comment]
Removed some unrelated comments for clarity.

**Comment by mervn** [comment]
I've encountered this error on version 4.9.7 and solved it by compiling SPICE with smartcard support (as @atykhonov said).

If this is the recommended solution, it should be documented. Otherwise, this issue should be reopened.
