### ISSUE TITLE
Add support for MacOS Sonoma

### ISSUE THREAD

**Issue by robcohen** [quickemu-project/quickemu#903]
I did a search for MacOS Sonoma, and I could not determine if there are any current plans to add support. What's involved with doing so? https://github.com/kholia/OSX-KVM supports Sonoma presently, so I don't believe it would be difficult to add.

**Comment by lj3954** [comment]
PR #886 includes macOS Sonoma support.

**Comment by robcohen** [comment]
Thank you, no idea how that didn't come up in a search. My mistake!

**Comment by Henry-Hiles** [comment]
Should this be reopened since that PR was never merged?

**Comment by zen0bit** [comment]
> Should this be reopened since that PR was never merged?

Merged in #986

**Comment by Henry-Hiles** [comment]
> > Should this be reopened since that PR was never merged?
> 
> Merged in #986

oh thanks. I just upgraded manually, (in macos settings), and it worked, but my keyboard no longer functions in the vm, is this expected?

**Comment by zen0bit** [comment]
Not tried macos myself

**Comment by Henry-Hiles** [comment]
usb_controller="xhci" fixed it

**Comment by zen0bit** [comment]
> usb_controller="xhci" fixed it

Maybe PR then?

**Comment by Henry-Hiles** [comment]
> > usb_controller="xhci" fixed it
> 
> Maybe PR then?

i just put it in the .conf file, where do i pr that to?
