### ISSUE TITLE
Windows 11 Fails to Start

### ISSUE THREAD

**Issue by nkizz** [quickemu-project/quickemu#904]
#### Expected behaviour

Windows 11 runs

#### Actual behaviour

Windows 11 does not run :(

Instead, the process just exits

#### Steps to reproduce the behaviour

I ran the commands below. This is a headless machine, but X11 forwarding is set up, and virt-manager/spice-viewer has been confirmed to work.

#### Quickemu output

```
[nix-shell:~]$ quickget windows 11
Downloading Windows 11...
 - Product edition ID: 2935
 - SKU ID: 17442
 - Got latest ISO download link (valid for 24 hours): https://software.download.prss.microsoft.com/dbazure/Win11_23H2_English_x64v2.iso?t=cb2f46e2-7482-446e-8bc5-4eb48c771221&e=1705089691&h=accf84e24ad4d4e689047eaa250ada11bbe6fe8a05a39e33ce0ced6679489cc0
windows-11/Win11_23H2_English_x64v2.is 100%[===========================================================================>]   6.34G   109MB/s    in 60s
Downloading VirtIO drivers...
windows-11/virtio-win.iso              100%[===========================================================================>] 598.45M  82.0MB/s    in 7.5s
Making unattended.iso
windows-11/unattended/spice-webdavd-x6 100%[===========================================================================>]  11.89M  22.5MB/s    in 0.5s
windows-11/unattended/spice-vdagent-x6 100%[===========================================================================>]   1.90M  6.95MB/s    in 0.3s
windows-11/unattended/UsbDk_1.0.22_x64 100%[===========================================================================>]   6.05M  18.8MB/s    in 0.3s
Making windows-11.conf
Giving user execute permissions on windows-11.conf,

To start your Windows virtual machine run:
    quickemu --vm windows-11.conf

[nix-shell:~]$ cat windows-11.conf
#!/nix/store/zdgf6zj8g7jvwh1j2i2ydxb62j52sn0f-quickemu-4.9.1/bin/quickemu --vm
guest_os="windows"
disk_img="windows-11/disk.qcow2"
iso="windows-11/Win11_23H2_English_x64v2.iso"
fixed_iso="windows-11/virtio-win.iso"
tpm="on"
secureboot="off"
[nix-shell:~]$ quickemu --vm windows-11.conf
Quickemu 4.9.1 using /nix/store/58xm9iqi49c2idxhpygw3r4gasal61wy-qemu-8.1.3/bin/qemu-system-x86_64 v8.1.3
 - Host:     "NixOS 23.11 (Tapir)" running Linux 6.1 (nixpro)
 - CPU:       AMD Ryzen 5 3600X 6-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 4G RAM
 - BOOT:     EFI (Windows), OVMF (/nix/store/8p2r6i89l75j864pwy3m2a4c01sk6fmq-OVMF-202311-fd/FV/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/Win11_23H2_English_x64v2.iso
 - Boot ISO: windows-11/Win11_23H2_English_x64v2.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - TPM:      windows-11/windows-11.swtpm-sock (8767)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
audio: Could not init `pa' audio driver
cat: windows-11/windows-11.pid: No such file or directory
 - Process:  Starting windows-11.conf as windows-11 ()
 - Sending:  sendkey ret
2024/01/11 15:03:25 socat[8777] E connect(, AF=1 "windows-11/windows-11-monitor.socket", 38): Connection refused
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```
No LSB modules are available.
Distributor ID:	NixOS
Description:	NixOS 23.11 (Tapir)
Release:	23.11
Codename:	tapir
Linux nixpro 6.1.68 #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 13 17:39:30 UTC 2023 x86_64 GNU/Linux
```

**Comment by lj3954** [comment]
The issue you're getting has something to do with PulseAudio. Is PulseAudio or PipeWire installed and active? See if there's anything out of the ordinary in the output of `pactl info`

**Comment by alxjsn** [comment]
I am also having an issue starting a Windows 11 VM on a fresh Arch Linux install.

```
quickemu --vm windows-11.conf --display spice
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.0
 - Host:     Arch Linux running Linux 6.7 (rum)
 - CPU:       12th Gen Intel(R) Core(TM) i7-1250U
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permanent by running: 'quickemu --ignore-msrs-always'
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Just created, booting from windows-11/windows-11.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/alxjsn/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11.swtpm-sock (2691)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
qemu-system-x86_64: -drive media=cdrom,index=0,file=windows-11/windows-11.iso: Could not open 'windows-11/windows-11.iso': No such file or directory
cat: windows-11/windows-11.pid: No such file or directory
 - Process:  Starting windows-11.conf as windows-11 ()
 - Sending:  sendkey ret
2024/01/15 20:53:33 socat[2730] E connect(, AF=1 "windows-11/windows-11-monitor.socket", 38): Connection refused
 - Viewer:   spicy --title "windows-11" --port "5930" --spice-shared-dir "/home/alxjsn/Public" "" >/dev/null 2>&1 &
 - ```

**Comment by lj3954** [comment]
> I am also having an issue starting a Windows 11 VM on a fresh Arch Linux install.
> 
> ```
> quickemu --vm windows-11.conf --display spice
> Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.0
>  - Host:     Arch Linux running Linux 6.7 (rum)
>  - CPU:       12th Gen Intel(R) Core(TM) i7-1250U
>  - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
>  - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.
> 
>              echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
> 
>              If you are unable to run macOS or Windows VMs then run the above 👆
>              This will enable ignoring of unhandled MSRs until you reboot the host.
>              You can make this change permanent by running: 'quickemu --ignore-msrs-always'
>  - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
>  - Disk:     windows-11/disk.qcow2 (64G)
>              Just created, booting from windows-11/windows-11.iso
>  - CD-ROM:   windows-11/virtio-win.iso
>  - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
>  - Sound:    intel-hda
>  - ssh:      On host:  ssh user@localhost -p 22220
>  - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/alxjsn/Public
>  - WebDAV:   On guest: dav://localhost:9843/
>  - TPM:      windows-11/windows-11.swtpm-sock (2691)
>  - Network:  User (virtio-net)
>  - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
>              or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
>  - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
>              or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
> qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
> qemu-system-x86_64: -drive media=cdrom,index=0,file=windows-11/windows-11.iso: Could not open 'windows-11/windows-11.iso': No such file or directory
> cat: windows-11/windows-11.pid: No such file or directory
>  - Process:  Starting windows-11.conf as windows-11 ()
>  - Sending:  sendkey ret
> 2024/01/15 20:53:33 socat[2730] E connect(, AF=1 "windows-11/windows-11-monitor.socket", 38): Connection refused
>  - Viewer:   spicy --title "windows-11" --port "5930" --spice-shared-dir "/home/alxjsn/Public" "" >/dev/null 2>&1 &
>  - ```
> ```

Your config file has the windows ISO path as windows-11.iso. That should mean that quickget for some reason failed to download the ISO and requested you manually download it instead. If that's what occurred, remember to rename the ISO to windows-11.iso as it suggested.

**Comment by alxjsn** [comment]
Ah, I saw an ISO in there, but that was the virtio one. Thanks for the pointer!

**Comment by tgienger** [comment]
Also having problems. I came over here because of issues getting one running so I'm hoping this will help narrow it down:
```
Quickemu 4.9.1 using /nix/store/06pbfqb9q17z5bqsisz317nl2jm682f0-qemu-8.2.0/bin/qemu-system-x86_64 v8.2.0
 - Host:     "NixOS 24.05 (Uakari)" running Linux 6.1 (nixos)
 - CPU:       13th Gen Intel(R) Core(TM) i9-13950HX
 - CPU VM:   1 Socket(s), 8 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/nix/store/aaaf9jdckmnhigmqrzll09m2pinqd0jm-OVMF-202311-fd/FV/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-11/disk.qcow2 (64G)
             Looks unused, booting from windows-11/windows-11.iso
 - Boot ISO: windows-11/windows-11.iso
 - CD-ROM:   windows-11/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - TPM:      windows-11/windows-11.swtpm-sock (2766)
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-11/windows-11-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-monitor.socket
 - Serial:   On host:  nc -U "windows-11/windows-11-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-11/windows-11-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  0
  Current serial number in output stream:  106
swtpm: Data client disconnected
cat: windows-11/windows-11.pid: No such file or directory
 - Process:  Starting windows-11.conf as windows-11 ()
 - Sending:  sendkey ret
2024/01/15 22:44:00 socat[2803] E connect(, AF=1 "windows-11/windows-11-monitor.socket", 38): Connection refused
```
nix unstable:
`Linux nixos 6.1.72 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jan 10 16:10:37 UTC 2024 x86_64 GNU/Linux`

**Comment by tgienger** [comment]
And just FYI I knew about the windows-11.iso and have renamed it. I'm clueless about the BadAlloc, can't tell what it's for.

**Comment by cowboyliao** [comment]
change the .conf, iso should be Win11_23H2_English_x64v2.iso.

**Comment by lj3954** [comment]
> And just FYI I knew about the windows-11.iso and have renamed it. I'm clueless about the BadAlloc, can't tell what it's for.

It's for sure a display driver issue. I'm assuming you're running an NVIDIA GPU on Wayland. Make sure you have the latest possible graphics driver installed. I'm not sure there's much else you can troubleshoot when you're using proprietary drivers.

**Comment by lj3954** [comment]
> change the .conf, iso should be Win11_23H2_English_x64v2.iso.

This is a solution to nothing. Quickget will automatically put the correct ISO in the config, it'll only put windows-11.iso if it fails to automatically download the ISO for Windows. It will instruct you to move the ISO into the VM directory as windows-11.iso.

**Comment by ToRvaLDz** [comment]
I had the same problem, did you try to activate swap partition or file?
