### ISSUE TITLE
docs: document how to get SPICE clipboard sharing to working on NixOS

### ISSUE THREAD

**Issue by genevieve-me** [quickemu-project/quickemu#919]
#### Expected behaviour

When "options / automatic clipboard sharing" is checked, it should be possible to copy on the host and paste into the guest.

#### Actual behaviour

Unable to get any sort of clipboard sharing in either direction.

#### Steps to reproduce the behaviour

- `quickget fedora 39 KDE`
- `quickemu --vm fedora-39-KDE.conf`
- Install Fedora with default settings in guest.
- Reboot, apply system update in guest. Install `spice-vdagent` (`dnf install spice-vdagent`) in guest. Shutdown.
- `quickemu --vm fedora-39-KDE.conf --display spice` in host.
- Tried in both Wayland and X11 environments in the guest. Only tried in a Wayland host environment, so it's possible that's where the issue lies.

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.
```
genevieve ~ > quickemu

Usage
  .quickemu-wrapped --vm ubuntu.conf

You can also pass optional parameters
...
```

#### Linux Distribution & Kernel

Linux godard 6.1.75 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jan 25 23:27:52 UTC 2024 x86_64 GNU/Linux

Running sway 1.9 (source build), nothing installed that would affect the clipboard

**Comment by flexiondotorg** [comment]
I've added a section to the wiki which describe how to enable clipboard sharing and includes details for NixOS.

- https://github.com/quickemu-project/quickemu/wiki/05-Advanced-quickemu-configuration#clipboard-sharing

**Comment by name-snrl** [comment]
@flexiondotorg I think it would be great for me to also write about how this doesn't work for wayland and what workarounds can be used for it.

https://gitlab.freedesktop.org/spice/linux/vd_agent/-/issues/26
https://github.com/name-snrl/nixos-configuration/blob/e29a7d45ed8dce5c82189e858c2d97c3fa895458/modules/nixos/profiles/system/vm-config.nix#L37-L47
