### ISSUE TITLE
easyos will not boot 

### ISSUE THREAD

**Issue by dabrown645** [quickemu-project/quickemu#921]
#### Expected behaviour

Expect to be able to boot up into downloaded OS

#### Actual behaviour

System did not boot up and went looking for pixie boot

#### Steps to reproduce the behaviour

quickget easyos 5.6.4
quickemu --vm easyos-5.6.4.conf

#### Quickemu output

 quickget easyos 5.6.4
easyos-5.6.4/easy-5.6.4-amd64.img              100%[===================================================================================================>] 857.00M  23.9MB/s    in 36s
Making easyos-5.6.4.conf
Giving user execute permissions on easyos-5.6.4.conf,

    quickemu --vm easyos-5.6.4.conf
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.0
 - Host:     "Garuda Linux" running Linux 6.7 (rog1)
 - CPU:       13th Gen Intel(R) Core(TM) i9-13980HX
 - CPU VM:   1 Socket(s), 8 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     easyos-5.6.4/disk.qcow2 (16G)
             Looks unused, booting from easyos-5.6.4/easy-5.6.4-amd64.img
 - Boot ISO: easyos-5.6.4/easy-5.6.4-amd64.img
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-dabrown ~/Public
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "easyos-5.6.4/easyos-5.6.4-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:easyos-5.6.4/easyos-5.6.4-monitor.socket
 - Serial:   On host:  nc -U "easyos-5.6.4/easyos-5.6.4-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:easyos-5.6.4/easyos-5.6.4-serial.socket

 - Process:  Starting easyos-5.6.4.conf as easyos-5.6.4 (107859)

![Screenshot_20240208_110119](https://github.com/quickemu-project/quickemu/assets/11675109/1f08aa13-ef71-49e2-9102-7ee8769e9fb7)

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a

❯ lsb_release --all
LSB Version:    n/a
Distributor ID: Garuda
Description:    Garuda Linux
Release:        Soaring
Codename:       Spizaetus
❯ uname -a
Linux rog1 6.7.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000 x86_64 GNU/Linux

**Comment by zen0bit** [comment]
I'll take a look later today..

**Comment by lj3954** [comment]
Clearly, EasyOS is using a .img file. The make_vm_config function is where the image type is set. EasyOS should be added to the switch cases.

**Comment by dabrown645** [comment]
Looks like it will need changes to both quickget and quickemu.  I tried setting gest to batocera which also uses img to see if it would and it did. Not sure what other setting need to be made in quickemu to support easyos

**Comment by zen0bit** [comment]
just needs convert img to qcow2 to work.
`qemu-img convert -f raw -0 qcow2 "${ISO}" disk.qcow2`
 easy os as is like installed system. Or for installation just unpack in any dir.

Not yet sure where to implement that...

**Comment by lj3954** [comment]
> just needs convert img to qcow2 to work. `qemu-img convert -f raw -O qcow2 "${ISO}" disk.qcow2` easy os as is like installed system on ext4 partition. Or for installation just unpack in any dir.
> 
> Not yet sure where to implement that...

FreeDOS, ReactOS, etc, have unarchiving in the create_vm function. You should put it there.
