### ISSUE TITLE
Error when using the optional parameter keyboard_layout

### ISSUE THREAD

**Issue by balazskiss1985** [quickemu-project/quickemu#922]
#### Expected behaviour

To be able to set keyboard_layout when when trying to change the default keyboard layout from en_us.

#### Actual behaviour

ERROR! "--keyboard_layout" is not a supported parameter.

#### Steps to reproduce the behaviour

quickemu --vm alpine-latest.conf --keyboard_layout "en-za"

#### Quickemu output

quickemu --vm alpine-latest.conf --keyboard_layout "en-za"
ERROR! "--keyboard_layout" is not a supported parameter.

#### Linux Distribution & Kernel

```bash
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
Linux desktop 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flexiondotorg** [comment]
Closed via #986
