### ISSUE TITLE
Can't start any vm

### ISSUE THREAD

**Issue by aleandro6804** [quickemu-project/quickemu#928]
#### Expected behaviour

Launch the vm's window

#### Actual behaviour

An error on the terminal occurs

#### Steps to reproduce the behaviour

Install any vm and launch it with 'quickemu --vm name.conf'

#### Quickemu output

$ quickemu --vm zorin-16-core64.conf

Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.1
 -Host:     "Arch Linux" running Linux 6.7 (archlinux)

 -CPU:       12th Gen Intel(R) Core(TM) i7-12700F

 -CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM

 -BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).

 -Disk:     zorin-16-core64/disk.qcow2 (16G)
             Looks unused, booting from zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso

 -Boot ISO: zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso

 -Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)

 -Sound:    intel-hda

 -ssh:      On host:  ssh user@localhost -p 22220

 -WebDAV:   On guest: dav://localhost:9843/

 -9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-aleandro ~/Public

 -Network:  User (virtio-net)

 -Monitor:  On host:  nc -U "zorin-16-core64/zorin-16-core64-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-monitor.socket

 -Serial:   On host:  nc -U "zorin-16-core64/zorin-16-core64-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-serial.socket

qemu-system-x86_64: Display 'sdl' is not available.

cat: zorin-16-core64/zorin-16-core64.pid: No such file or directory

 -Process:  Starting zorin-16-core64.conf as zorin-16-core64 ()

#### Linux Distribution & Kernel

Run the following and paste the output.
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

Linux archlinux 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux

**Comment by TuxVinyards** [comment]
> "Display 'sdl' is not available."

Check your install.  Try adding --display spice

**Comment by aleandro6804** [comment]
This is the output:
`$ quickemu -vm zorin-16-core64.conf --display spice


Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.1
 - Host:     "Arch Linux" running Linux 6.7 (archlinux)
 - CPU:       12th Gen Intel(R) Core(TM) i7-12700F
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     zorin-16-core64/disk.qcow2 (16G)
             Looks unused, booting from zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso
 - Boot ISO: zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso
 - Display:  SPICE, virtio-gpu, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "zorin-16-core64" --port 5930 --spice-shared-dir /home/aleandro/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-aleandro ~/Public
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "zorin-16-core64/zorin-16-core64-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-monitor.socket
 - Serial:   On host:  nc -U "zorin-16-core64/zorin-16-core64-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-serial.socket
qemu-system-x86_64: -spice disable-ticketing=on,port=5930,addr=127.0.0.1: There is no option group 'spice'
/usr/bin/quickemu: line 210:  3025 Segmentation fault      (core dumped) ${QEMU} "${args[@]}" > "${VMDIR}/${VMNAME}.log"
cat: zorin-16-core64/zorin-16-core64.pid: No such file or directory
 - Process:  Starting zorin-16-core64.conf as zorin-16-core64 ()
 - Viewer:   spicy --title "zorin-16-core64" --port "5930" --spice-shared-dir "/home/aleandro/Public" "" >/dev/null 2>&1 &
 `

It also open this window for the SPICE connection but, when i click on connect, it just shows up the same window in a loop
![error](https://github.com/quickemu-project/quickemu/assets/79479582/d38577cf-95d9-42e1-b41b-f9483cf6ef0c)





I tried also starting the vm without the display but it still not works
`$ quickemu -vm zorin-16-core64.conf --display none


Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.1
 - Host:     "Arch Linux" running Linux 6.7 (archlinux)
 - CPU:       12th Gen Intel(R) Core(TM) i7-12700F
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     zorin-16-core64/disk.qcow2 (16G)
             Looks unused, booting from zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso
 - Boot ISO: zorin-16-core64/Zorin-OS-16.3-Core-64-bit.iso
 - Display:  NONE, virtio-gpu, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "zorin-16-core64" --port 5930 --spice-shared-dir /home/aleandro/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-aleandro ~/Public
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "zorin-16-core64/zorin-16-core64-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-monitor.socket
 - Serial:   On host:  nc -U "zorin-16-core64/zorin-16-core64-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:zorin-16-core64/zorin-16-core64-serial.socket
qemu-system-x86_64: -spice disable-ticketing=on,port=5930,addr=127.0.0.1: There is no option group 'spice'
/usr/bin/quickemu: line 210:  3335 Segmentation fault      (core dumped) ${QEMU} "${args[@]}" > "${VMDIR}/${VMNAME}.log"
cat: zorin-16-core64/zorin-16-core64.pid: No such file or directory
 - Process:  Starting zorin-16-core64.conf as zorin-16-core64 ()
`

**Comment by TuxVinyards** [comment]
> "There is no option group 'spice'"  

Don't know what that is all about.  Either the command you are typing is wrong or there is software that you haven't installed.

What happens if you try with qqX?

Also, you say it happens with all your VM's.  What happens with something like Ubuntu?

**Comment by TuxVinyards** [comment]
There's something wrong with your basic underlying quickemu dependencies.  Something is not installed properly there.

I have looked at your video.   There's a highlighted "[ql] see qemu error log"  message. Opening that  might give you a clue.

The reason that Spice won't connect is simply that  VM hasn't booted.  There's probably nothing wrong with Quickemu or Spice.  There's something not right at a lower level.

Delete and re-install all the underlying recommended software.  You can leave qqX and quickemu, I would think.

Strangely,  when I started up my main computer, just now, it was offering me updates for the OVMF system.   That's the virtual UEFI/BIOS that is used by Qemu to get things going.   Looked to be all like security patches though.

I have another computer that runs Manjaro (Arch) and that has never had any quickemu problems. Everything should be running for you.  There's something not right with you host system.

I am presuming that as you are running Arch that you are a reasonably experienced and able Linux user.   But you do seem to be not seeing the error messages that being presented to you.   Have you checked that you have got all the virtual functions of your HOST CPU enabled on your host UEFI/BIOS?

![Screenshot at 2024-02-15 17-27-37](https://github.com/quickemu-project/quickemu/assets/3956806/c67e0da9-aae4-48e1-bdb6-5350bfcd48a7)

System dependencies  and distro package variances can be quite frustrating.   I know. :rofl:

**Comment by TuxVinyards** [comment]
Pleased that it's all solved.  There's no obligation to use qqX to run quickemu.  

It won't hurt your setup in the slightest if you haven't yet decided. And there are lots of tools that qqX has, that you don't get with standard quickemu.

But if you want to uninstall or change the setup, just run the installer script ...

👍

**Comment by aleandro6804** [comment]
Ok, i'll give it a try. Thanks for everything!

**Comment by ameyjoshi3068** [comment]
I faced same issue.
Solved.

**Comment by bhutch29** [comment]
Same issue, same solution here on Arch. qemu-full instead of qemu-base resolved it.

**Comment by GrabbenD** [comment]
Here's how Arch Linux devs fixed this for `incus` with `qemu-base`
https://gitlab.archlinux.org/archlinux/packaging/packages/incus/-/issues/5#note_159149

```
$ pacman --sync --needed qemu-base qemu-chardev-spice qemu-hw-usb-redirect qemu-hw-display-virtio-vga qemu-hw-display-virtio-gpu
```

* This includes `qemu-ui-spice-core` & `qemu-ui-spice-app`
* I believe it's possible to skip `virtio` packages with `qemu-hw-display-qxl`
* It might be worth to consider `qemu-audio-spice`

Cheers

**Comment by averyfreeman** [comment]
I landed on this page directly after experiencing the same (or quite similar) issue, where I was unable to start a new instance of `quickemu` after accidentally closing a VM window with `ALT+F4`. 

People in this thread advocate removing and re-installing entire package suites, but I want to recommend restarting `qemu-kvm.service` before going through all that trouble, since it allowed me start a new instance, as normal, immediately afterward.

synopsis:

```
sudo systemctl restart qemu-kvm.service
```
Give it a shot, the worst that can happen is if it doesn't work, you end up re-installing like you'd already planned.

**Comment by TuxVinyards** [comment]
>  where I was unable to start a new instance of quickemu after accidentally closing a VM window with ALT+F4.

@averyfreeman  that is quite easy to do if you have booted with Spice.  Only the display window actually closes. The Spice server and the VM are still running ....

I f you look at the quickemu output on the terminal,  the info is there for opening a fresh window and getting back in.   

Running `systemctl`  will cause a force close of your VM.
