### ISSUE TITLE
Kali Linux out of disk space

### ISSUE THREAD

**Issue by Parrot7483** [quickemu-project/quickemu#944]
#### Expected behaviour

Following the installation process with default settings and ensuring all software upgrades are completed, the system should not encounter disk space limitations.

#### Actual behaviour

Out of disk space after default install.

#### Steps to reproduce the behaviour

Install kali linux current with all default settings and upgrade software afterwards

#### Proposed Change

Increase the default disk size to 20G - 30G

**Comment by flexiondotorg** [comment]
Closed via #986
