### ISSUE TITLE
feat: add an option to pass an entire raw disk

### ISSUE THREAD

**Issue by dsancheznet** [quickemu-project/quickemu#955]
I'd like to pass an entire hard disk to a Sonoma virtual machine. In virtual-machine-manager I use the following code:
```XML
<disk type='block' device='disk'>
  <driver name='qemu' type='raw' cache='none'/>
  <source dev='/dev/disk/by-partuuid/d8b63353-34n6-6587-ac07-810mdf36d544'/>
  <target dev='vdb' bus='virtio'/>
  <boot order='2'/>
  <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
</disk>
```

How could I accomplish that with quickemu?

Best regards
D.Sánchez

**Comment by zen0bit** [comment]
Isn't this same as #726?

**Comment by dsancheznet** [comment]
No, I did not explain correctly, I'm afraid.

I don't want to use a qcow2 disk but a raw device ( a passthrough ) such as /dev/sda or /dev/sdb... 
As if the device were connected bare metal.

Best regards
