### ISSUE TITLE
versioning wrong in quickemu

### ISSUE THREAD

**Issue by axlroden** [quickemu-project/quickemu#958]
https://github.com/quickemu-project/quickemu/blob/0c8e1a5205c5706f63b2921e50d4c8fa9f60c774/quickemu#L1557
On 4.9.2 release.. 

causing:
quickemu --version 
to be 4.9.1 .. 
Which wasted me an hour trying to figure out if i had the latest version or not :)

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickemu/commit/0d5b97e186e286210a9ce18ea552de4709781c9e
