### ISSUE TITLE
Problems installing Quickemu on MXLinux

### ISSUE THREAD

**Issue by Rotyak85** [quickemu-project/quickemu#959]
#### Expected behaviour

Use Quickemu after installation.

#### Actual behaviour

I am unable to start quickemu

#### Steps to reproduce the behaviour

I did :

    sudo apt install qemu bash coreutils ovmf grep jq lsb-base procps python3 genisoimage usbutils util-linux sed spice-client-gtk libtss2-tcti-swtpm0 wget xdg-user-dirs zsync unzip

Response: 
    
    The package 'qemu' does not have an installation candidate

i searched in apt and found **qemu-system-x86,** installed it.

now:

    git clone --filter=blob:none https://github.com/wimpysworld/quickemu

then:

    ./quickemu

#### Quickemu output

    ERROR! QEMU not found. Please make install qemu-system-x86_64 and qemu-img

Note:
    
- i found only **qemu-system-x86** and not **qemu-system-x86_64**, but i think the 64 is underlined
- i didn't find **qemu-img**

Other info:
- The other test i did was to install qemu entirely, so i did **apt install qemu-system**, with no luck (same error).

#### Linux Distribution & Kernel
MXlinux 23.2 (Debian 12 based)

```bash
lsb_release --all
uname -a
```
Response:

```No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
Linux my-pc 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

**Comment by flexiondotorg** [comment]
Please install Quickemu using the .deb package provided in the Release page.

- https://github.com/quickemu-project/quickemu/releases
