### ISSUE TITLE
MacOS installation stuck on Monterey and Ventura

### ISSUE THREAD

**Issue by hairy-tortoise** [quickemu-project/quickemu#960]
#### Expected behaviour

That the time remaining will go down and MacOS be installed. 

#### Actual behaviour

Instead it is stuck at 2 hours and 31 minutes.

#### Steps to reproduce the behaviour

Follow the Guide to install MacOS

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

```bash
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
Linux tortoise-Surface-Pro 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flexiondotorg** [comment]
At that step, macOS Recovery is downloading the large installation image for macOS. This can take a very long time depending on your network bandwidth
