### ISSUE TITLE
PPA is outdated

### ISSUE THREAD

**Issue by popey** [quickemu-project/quickemu#965]
#### Expected behaviour

To install the latest release of QuickEmu as per the installation instructions from the PPA linked in the README.md

#### Actual behaviour

I get quickemu 4.9.1

#### Steps to reproduce the behaviour

1. Install Ubuntu 23.10
2. Add the https://launchpad.net/~flexiondotorg/+archive/ubuntu/quickemu?field.series_filter=mantic repo as per the README
3. `apt install quickemu`
4. `quickemu --version`

Get 4.9.1, expect 4.9.2

#### Quickemu output

```bash
$ quickemu --version
4.9.1

```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
$ uname -a
Linux nuc 6.5.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:17:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zen0bit** [comment]
In 4.9.2 isn't properly raised version..

It still saying 4.9.1..

So you are on latest..
Someone already mention it...

**Comment by popey** [comment]
Uh, 4.9.2 is the "Latest" release on github. https://github.com/quickemu-project/quickemu/releases/tag/4.9.2

**Comment by zen0bit** [comment]
Yes but inside quickemu script is still 4.9.1 even is it 4.9.2
