### ISSUE TITLE
socat[66135] E connect(, AF=1 "windows-10/windows-10-monitor.socket", 38): Connection Refused

### ISSUE THREAD

**Issue by KuboSE** [quickemu-project/quickemu#968]
#### Expected behaviour

Expected behavior includes start of virtual machine.

#### Actual behaviour

The virtual machine refuses to start.

#### Steps to reproduce the behaviour

Pull the latest version of Windows 10 using quickget through `quickget windows 10`, and then attempt to launch Windows 10 through launching quickemu as `quickemu --vm windows-10.conf`. 

#### Quickemu output
```bash
(base) [delle@kubose ~]$ quickemu --vm windows-10.conf --display gtk
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.2
 - Host:     "EndeavourOS Linux" running Linux 6.6 (kubose)
 - CPU:       AMD Ryzen 5 3600XT 6-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
             Looks unused, booting from windows-10/windows-10.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  GTK, qxl-vga, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
qemu-system-x86_64: -drive media=cdrom,index=0,file=windows-10/windows-10.iso: Could not open 'windows-10/windows-10.iso': No such file or directory
cat: windows-10/windows-10.pid: No such file or directory
 - Process:  Starting windows-10.conf as windows-10 ()
 - Sending:  sendkey ret
2024/03/21 04:26:14 socat[66135] E connect(, AF=1 "windows-10/windows-10-monitor.socket", 38): Connection refused
```

#### Linux Distribution & Kernel
```bash
(base) [delle@kubose ~]$ lsb_release --all
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling
(base) [delle@kubose ~]$ uname -a
Linux kubose 6.6.22-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 06:20:33 +0000 x86_64 GNU/Linux
```

#### (additional information) 
* I have attempted to run the software using different displays. Running `--display none` and `--display gtk` generate the same error; `--display spice` generates the same, but appends the following after launching the respective desktop environment's SPICE client: ` - Viewer:   spicy --title "windows-10" --port "5930" --spice-shared-dir "/home/delle/Public" "" >/dev/null 2>&1 &`
* I've verified that both `qemu-base` and `qemu-display` were both installed prior to Quickemu. In fact, attempting to remove `qemu-base` throws an error for `qemu-display` as a dependency. 
* There was an error about attempting to download Windows 10 as a result of my VPN, so Quickget installed a different variant and threw a message about the config needing to be changed. I didn't catch it in time, but I wonder if this has something to do with it.

**Comment by pafurijaz** [comment]
Same issue here with boot Win 10 and 11..

**Comment by lj3954** [comment]
If quickget fails to fetch a valid URL for Windows, it will set the path to "windows-RELEASE.iso" and continue downloading the drivers and creating the unattended setup. You must download the ISO yourself in that case. The issue has nothing to do with socat.

**Comment by KuboSE** [comment]
Hey there. 

I downloaded the ISO just fine later, and it installed with no issues. 
I've also verified that I have qemu-base, qemu-desktop and qemu-full installed. 

The error presented by socat still remains. 
After having removed all three above packages and reinstalling them, this error still remains. 
I've also tried reinstalling Quickemu, which also results in the same error.

**Comment by lj3954** [comment]
An error with socat will only occur if the VM already has failed to start for another reason, since socat is just used to send keys to the guest. If you have already moved the ISO into the VM's directory, please provide the new output from quickemu.

**Comment by KuboSE** [comment]
```bash
(base) [delle@kubose ~]$ quickemu --vm windows-10.conf 
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.2
 - Host:     "EndeavourOS Linux" running Linux 6.6 (kubose)
 - CPU:       AMD Ryzen 5 3600XT 6-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
             Looks unused, booting from windows-10/windows-10.iso
 - CD-ROM:   windows-10/virtio-win.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
qemu-system-x86_64: -no-hpet: warning: -no-hpet is deprecated, use '-machine hpet=off' instead
qemu-system-x86_64: -drive media=cdrom,index=0,file=windows-10/windows-10.iso: Could not open 'windows-10/windows-10.iso': No such file or directory
cat: windows-10/windows-10.pid: No such file or directory
 - Process:  Starting windows-10.conf as windows-10 ()
 - Sending:  sendkey ret
2024/03/22 00:54:02 socat[105967] E connect(, AF=1 "windows-10/windows-10-monitor.socket", 38): Connection refused
(base) [delle@kubose ~]$ ls windows-10
disk.qcow2    unattended      virtio-win.iso                windows-10-agent.sock  windows-10-monitor.socket  windows-10.sh
OVMF_VARS.fd  unattended.iso  Win10_22H2_English_x64v1.iso  windows-10.log         windows-10.ports
```

This time, attempting to use the monitor options as before result in errors, presumably because `windows-10/windows-10-monitor.socket` exists. But I'm not sure why the attempt to open the socket fails, and I think something either with the VM or with my system related to this socket is causing this.

**Comment by lj3954** [comment]
The ISO must be renamed to windows-10.iso. If quickget is unable to fetch a URL, it's unable to determine what the filename of the latest ISO of that windows version, so it instead points the config to windows-RELEASE.iso. Alternatively, you can edit the config and replace "windows-10/windows-10.iso" with "windows-10/Win10_22H2_English_x64v1.iso".

**Comment by KuboSE** [comment]
Hey, this works for me; I was able to get it loaded up. I appreciate it! Thank you!

**Comment by pafurijaz** [comment]
Thanks, @lj3954,  now I've understand more, but in my case with quickget Win10_22H2_English_x64v1.iso wasn't downloaded, in the windows-10, I have these files inside.
![image](https://github.com/quickemu-project/quickemu/assets/11751383/965159b1-1c31-454c-b446-fce0d9d07764)

**Comment by lj3954** [comment]
Yes, that's because the person above downloaded the ISO directly from Microsoft's website. The current method used to fetch the URL for Windows downloads doesn't work very reliably, so quickget will ask you to download it from Microsoft yourself instead.

**Comment by pafurijaz** [comment]
Thanks, after many trouble now I have the right iso and it worked with SPICE, but I have to understand some things before finalize the OS.

**Comment by iQiexie** [comment]
> Alternatively, you can edit the config and replace "windows-10/windows-10.iso" with "windows-10/Win10_22H2_English_x64v1.iso".

What file do I need to edit?
