### ISSUE TITLE
quickget error Unknown option 'show-progress' 

### ISSUE THREAD

**Issue by 24fpsDaVinci** [quickemu-project/quickemu#973]
#### Expected behaviour

download files

#### Actual behaviour

error failed to download

#### Steps to reproduce the behaviour
$ ./quickget macos monterey

#### Quickemu output

Unknown option 'show-progress'
ERROR! Failed to download https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2 with wget. Try running 'quickget' again.

#### Linux Distribution & Kernel
LSB Version:	
Distributor ID:	Fedora
Description:	Fedora release 41 (Rawhide)
Release:	41
Codename:	Rawhide
Linux fedora 6.9.0-0.rc0.20240322git8e938e398669.14.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 22 16:04:21 UTC 2024 x86_64 GNU/Linux

**Comment by 24fpsDaVinci** [comment]
I found this #878 from December but the error is still happening after after MR #879

**Comment by 24fpsDaVinci** [comment]
ok I guess its just waiting for #878 #879

**Comment by flexiondotorg** [comment]
Closed via #986
