### ISSUE TITLE
Config options to set resolution

### ISSUE THREAD

**Issue by jmpolom** [quickemu-project/quickemu#974]
Right now quickemu is _far_ too helpful and automatically attempts to set desired window resolutions based on desktop resolution. This is undesirable behavior. What configuration options exist to manually set the resolution that gets configured in the start script for the VM? I did not see any obvious way to do this in the quickemu script (but there should be).

**Comment by TuxVinyards** [comment]
You can do all that with qqX ....  But if you don't want to use it ...

**Comment by jmpolom** [comment]
> You can do all that with qqX

I do not understand what you mean here. Can you elaborate?

What I want to do is [bypass this unhelpful bit](https://github.com/quickemu-project/quickemu/blob/0c8e1a5205c5706f63b2921e50d4c8fa9f60c774/quickemu#L686) and simply provide X and Y resolution in the VM conf file. quickemu generates a start script where those calculated resolutions get statically defined.

It is extremely obnoxious to have to manually edit that file  to change it and it also kind of breaks the normal user workflow with quickemu to do so. Any customization in that start script can easily get overwritten by quickemu.

**Comment by TuxVinyards** [comment]
You can place a percentage in the .conf file that qqX will act on every time you start up the VM. You can also set a default percentage which will work globally.

Quickemu doesn't have individual X and Y settings.  Something perhaps for the future.

That's the best we have at present.  Feel free to add a pull request or make your own fork ...

**Comment by TuxVinyards** [comment]
There is one more thing. 

You can tweak the X and Y in if you use qqX to set up a Custom Boot. 

See the qqX wiki & the settings file notes ...

**Comment by jmpolom** [comment]
I was extremely confused what "qqX" is in your messages but now I understand. I do not use qqX nor do I desire to. I prefer the simplicity of quickemu and basic configuration files. I will consider adding this feature and sending a PR.

**Comment by flexiondotorg** [comment]
Closed via #986
