### ISSUE TITLE
Can't start windows 11. Connect to SPICE

### ISSUE THREAD

**Issue by ilcobrapizzica** [quickemu-project/quickemu#978]
#### Expected behaviour

I installed quickemu and quickgui on linux mint and had windows 10 and windows 11 as virtual machines.
They worked perfectly.
Yesterday I made a copy of Windows 11 and started a second machine with Windows 11.
Everything worked, but then I started seeing the connect to SPICE error.
I deleted all virtual machines with windows 11 and reinstalled it several times, but the error remains.
I used timeshift to bring the system back to past configurations, but the error persists.
I tried to find an online solution to this problem, but nothing I read works.
I haven't the slightest idea what to do.
Windows 10 boots fine, as do the other virtual machines.
The problem only exists with Windows 11.

#### Quickemu output
Usage
  quickemu --vm ubuntu.conf

You can also pass optional parameters
  --access                          : Enable remote spice access support. 'local' (default), 'remote', 'clientipaddress'
  --braille                         : Enable braille support. Requires SDL.
  --delete-disk                     : Delete the disk image and EFI variables
  --delete-vm                       : Delete the entire VM and it's configuration
  --display                         : Select display backend. 'sdl' (default), 'gtk', 'none', 'spice' or 'spice-app'
  --fullscreen                      : Starts VM in full screen mode (Ctl+Alt+f to exit)
  --ignore-msrs-always              : Configure KVM to always ignore unhandled machine-specific registers
  --screen <screen>                 : Use specified screen to determine the window size.
  --screenpct <percent>             : Percent of fullscreen for VM if --fullscreen is not specified.
  --shortcut                        : Create a desktop shortcut
  --snapshot apply <tag>            : Apply/restore a snapshot.
  --snapshot create <tag>           : Create a snapshot.
  --snapshot delete <tag>           : Delete a snapshot.
  --snapshot info                   : Show disk/snapshot info.
  --status-quo                      : Do not commit any changes to disk/snapshot.
  --viewer <viewer>                 : Choose an alternative viewer. @Options: 'spicy' (default), 'remote-viewer', 'none'
  --ssh-port <port>                 : Set ssh-port manually
  --spice-port <port>               : Set spice-port manually
  --public-dir <path>               : Expose share directory. @Options: '' (default: xdg-user-dir PUBLICSHARE), '<directory>', 'none'
  --monitor <type>                  : Set monitor connection type. @Options: 'socket' (default), 'telnet', 'none'
  --monitor-telnet-host <ip/host>   : Set telnet host for monitor. (default: 'localhost')
  --monitor-telnet-port <port>      : Set telnet port for monitor. (default: '4440')
  --monitor-cmd <cmd>               : Send command to monitor if available. (Example: system_powerdown)
  --serial <type>                   : Set serial connection type. @Options: 'socket' (default), 'telnet', 'none'
  --serial-telnet-host <ip/host>    : Set telnet host for serial. (default: 'localhost')
  --serial-telnet-port <port>       : Set telnet port for serial. (default: '6660')
  --keyboard <type>                 : Set keyboard. @Options: 'usb' (default), 'ps2', 'virtio'
  --keyboard_layout <layout>        : Set keyboard layout.
  --mouse <type>                    : Set mouse. @Options: 'tablet' (default), 'ps2', 'usb', 'virtio'
  --usb-controller <type>           : Set usb-controller. @Options: 'ehci' (default), 'xhci', 'none'
  --sound-card <type>               : Set sound card. @Options: 'intel-hda' (default), 'ac97', 'es1370', 'sb16', 'none'
  --extra_args <arguments>          : Pass additional arguments to qemu
  --version                         : Print version

#### Linux Distribution & Kernel
Linux Mint 21.3 Cinnamon
5.15.0-101-generic
![ksnip_20240403-083427](https://github.com/quickemu-project/quickemu/assets/60149346/0a8261c9-cf2d-4ec7-a905-658edaadb4c6)

**Comment by ilcobrapizzica** [comment]
I tried to install windows 8 and I have the same problem when I start it.
It seems that any new installation of Windows will now fail.
Is there a way to reset everything and keep the virtual machines?

**Comment by zen0bit** [comment]
Your quickemu output don't show anything, just part of quickemu help message..

hard to tell whats your problem (i think you already have ISOs)

**Comment by ilcobrapizzica** [comment]
I don't know where is the problem.
This is Windows 11 folder.
![ksnip_20240403-160050](https://github.com/quickemu-project/quickemu/assets/60149346/90c6d793-09b0-4952-80c1-e6ca835749fa)

**Comment by ilcobrapizzica** [comment]
> Change the config file in the parent directory to reference the ISO. Chances are you haven't modified it to point to your downloaded ISO, since you manually downloaded it.

Thank you very much.
You solve my problem.
