### ISSUE TITLE
missing newer endeavouros versions

### ISSUE THREAD

**Issue by lucamosca1** [quickemu-project/quickemu#982]
If I try to install endeavour os I see

luca@XXX:~$ quickget endeavouros 
ERROR! You must specify a release.
 - Releases: apollo_22_1 artemis-22_6 artemis_neo_22_7 artemis_neo_22_8 artemis_nova_22_9 atlantis-21_4 atlantis_neo-21_5 cassini_22_12
luca@XXX:~$ 

and the newer version EndeavourOS_Galileo-Neo-2024.01.25.iso is missing, can you please add it?

**Comment by TuxVinyards** [comment]
We are working on getting quickget updated. There's a lot of discussion still going on but Galileo has already been added.

Until the new release of quickget, please feel free to use the new ISO installer function with the new qqX 1.7, out this morning and designed to address this whole general issue.
