### ISSUE TITLE
feat: add font logos of Operating Systems

### ISSUE THREAD

**Issue by zen0bit** [quickemu-project/quickemu#983]
What about pretty icons used in quickemu/quickget?

Not sure how to easily show svg in any terminal..

But found how to create fonts.

What about font with Operating Systems logos?

Working on it...
0.0.3 - font broken
![preview](https://github.com/quickemu-project/quickemu/assets/6384793/edcf23bb-f8b6-42cf-8059-a36ac8b931a6)

[quickemu-logos](https://github.com/oSoWoSo/quickemu-logos) repo

~PR will follow later~ #1082
(**Still** not all logos there yet)
# And here is screenshot of actual font: (0.0.2)
 with not yet removed apps logos from source repo https://github.com/lukas-w/font-logos
![icons](https://github.com/quickemu-project/quickemu/assets/6384793/ba1bc20e-b11f-4d1d-92c1-cb95a40cb48c)

So far my conversion of quickemu logo
![fontmanager](https://github.com/quickemu-project/quickemu/assets/6384793/19dc3169-b186-4359-a3a5-c89f43034df4)
 isn't sucesfull (font shows circle or square instead)
![quickemu](https://github.com/quickemu-project/quickemu/assets/6384793/fa61a80e-2083-439b-8e3b-fa646972392d)

PS: Interested for qqX? @TuxVinyards

PPS: Due to screen readers this must be optional!

**Comment by lj3954** [comment]
https://github.com/quickemu-project/quickemu-icons already exists and is used for list_csv.

**Comment by zen0bit** [comment]
:thinking: I am already contributed there

But that are colored svg icons (also gathered in my repo..)
I am speaking about `font` logos

**Comment by lj3954** [comment]
Unless I'm completely mistaken, you won't be able to display anything in a font other than your console font. The idea of a feature within a project like quickget which requires the user to change their font is ridiculous. Realistically, the only way to make this work for all users would be to display ASCII art instead.

**Comment by zen0bit** [comment]
ASCII art already implemented (not pushed?)

```
#!/bin/bash

# Set variables for fonts
TEXT_FONT="Arial.ttf"  # Name of the text font
ICON_FONT="FontAwesome.ttf"  # Name of the icon font

# Set variables for icons
ICON_HOME='\uf015'  # Home icon from the icon font

# Print text with icons
echo -e "Text with home icon: $ICON_HOME"

# Set font for echo command output
echo -e "\033[11mText with specified font\033[0m"
```

Don't know what you mean, this works for me...

**Comment by zen0bit** [comment]
respektive this:
![vhstest](https://github.com/quickemu-project/quickemu/assets/6384793/e065c61b-7b83-4ce8-95c6-ff470f943234)

**Comment by lj3954** [comment]
Intriguing.

**Comment by zen0bit** [comment]
Do you like the idea @flexiondotorg?

**Comment by flexiondotorg** [comment]
It is an interesting idea. How are the distro font glyphs provided exactly?

**Comment by zen0bit** [comment]
Currently is only two options
- Nerd Fonts - incomplete
  - respektive https://github.com/lukas-w/font-logos including some distros and apps. Source for Nerd Icons with what we want
  (Already involved there and raised PRs etc.)
- create own font - I already started... (currently dormant and bit broken) I hope I find older version on drive, since I force pushed 😳
https://github.com/oSoWoSo/quickemu-font-and-logos
(excuse for using quickemu in name without asking)

This I think could be quicker to acomplish (and push it all to font-logos or nerd-fonts later)

I need gather complete specification of svg needed for conversion.
(Mainly setup of colors/transparency)
Broke some icons.
As source I am using mentioned font-logos quickemu-svg icons simple icon font and rest I gathered or recreated from what I found anywhere.

**Comment by zen0bit** [comment]
# And here is screenshot of actual font:
![icons](https://github.com/quickemu-project/quickemu/assets/6384793/ba1bc20e-b11f-4d1d-92c1-cb95a40cb48c)

**Comment by Finii** [comment]
> Unless I'm completely mistaken, you won't be able to display anything in a font other than your console font.

I guess zen0bit's idea is to ask users to either install an additional font with the OS logos as glyphs that is selected via fontfallback, or switch their terminal's font to a different font with that glyphs.

> like quickget which requires the user to change their font is ridiculous

I would not use such harsh words, but 100% ACK ;) I would be annoyed if some application throws codepoints at me that are displayed as [Tofu](https://fonts.google.com/knowledge/glossary/tofu) unless I install some additional font and/or switch fonts.

**Comment by flexiondotorg** [comment]
I have similar concerns to those expressed by @Finii. Closing this as out of scope.
